
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class AffyAnnoStg
{
  private String alignments;

  private String chromosomalLocation;

  private String ec;

  private String ensembl;

  private String genechipArray;

  private String geneSymbol;

  private String geneTitle;

  private String genomeVersion;

  private Object gontoBioProc;

  private Object gontoCellComp;

  private Object gontoMolecuFunc;

  private String locuslink;

  private String omim;

  private String pathwayName;

  private String probesetName;

  private String refseqproteinId;

  private String refseqTranscriptId;

  private String speciesName;

  private String swissprotId;

  private String unigeneId;

  public String getAlignments()
  {
     return this.alignments;
  }
  public void setAlignments(String param)
  {
    this.alignments = param;
  }


  public String getChromosomalLocation()
  {
     return this.chromosomalLocation;
  }
  public void setChromosomalLocation(String param)
  {
    this.chromosomalLocation = param;
  }


  public String getEc()
  {
     return this.ec;
  }
  public void setEc(String param)
  {
    this.ec = param;
  }


  public String getEnsembl()
  {
     return this.ensembl;
  }
  public void setEnsembl(String param)
  {
    this.ensembl = param;
  }


  public String getGenechipArray()
  {
     return this.genechipArray;
  }
  public void setGenechipArray(String param)
  {
    this.genechipArray = param;
  }


  public String getGeneSymbol()
  {
     return this.geneSymbol;
  }
  public void setGeneSymbol(String param)
  {
    this.geneSymbol = param;
  }


  public String getGeneTitle()
  {
     return this.geneTitle;
  }
  public void setGeneTitle(String param)
  {
    this.geneTitle = param;
  }


  public String getGenomeVersion()
  {
     return this.genomeVersion;
  }
  public void setGenomeVersion(String param)
  {
    this.genomeVersion = param;
  }


  public Object getGontoBioProc()
  {
     return this.gontoBioProc;
  }
  public void setGontoBioProc(Object param)
  {
    this.gontoBioProc = param;
  }


  public Object getGontoCellComp()
  {
     return this.gontoCellComp;
  }
  public void setGontoCellComp(Object param)
  {
    this.gontoCellComp = param;
  }


  public Object getGontoMolecuFunc()
  {
     return this.gontoMolecuFunc;
  }
  public void setGontoMolecuFunc(Object param)
  {
    this.gontoMolecuFunc = param;
  }


  public String getLocuslink()
  {
     return this.locuslink;
  }
  public void setLocuslink(String param)
  {
    this.locuslink = param;
  }


  public String getOmim()
  {
     return this.omim;
  }
  public void setOmim(String param)
  {
    this.omim = param;
  }


  public String getPathwayName()
  {
     return this.pathwayName;
  }
  public void setPathwayName(String param)
  {
    this.pathwayName = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public String getRefseqproteinId()
  {
     return this.refseqproteinId;
  }
  public void setRefseqproteinId(String param)
  {
    this.refseqproteinId = param;
  }


  public String getRefseqTranscriptId()
  {
     return this.refseqTranscriptId;
  }
  public void setRefseqTranscriptId(String param)
  {
    this.refseqTranscriptId = param;
  }


  public String getSpeciesName()
  {
     return this.speciesName;
  }
  public void setSpeciesName(String param)
  {
    this.speciesName = param;
  }


  public String getSwissprotId()
  {
     return this.swissprotId;
  }
  public void setSwissprotId(String param)
  {
    this.swissprotId = param;
  }


  public String getUnigeneId()
  {
     return this.unigeneId;
  }
  public void setUnigeneId(String param)
  {
    this.unigeneId = param;
  }


}

