
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class AgeGroupDx
{
  private String ageGroup;

  private String ageGroupDesc;

  private Long lowerbound;

  private Long upperbound;

  private java.util.Vector collDifferentialExpressionSfact;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collDifferentialExpressionGfact;

  public String getAgeGroup()
  {
     return this.ageGroup;
  }
  public void setAgeGroup(String param)
  {
    this.ageGroup = param;
  }


  public String getAgeGroupDesc()
  {
     return this.ageGroupDesc;
  }
  public void setAgeGroupDesc(String param)
  {
    this.ageGroupDesc = param;
  }


  public Long getLowerbound()
  {
     return this.lowerbound;
  }
  public void setLowerbound(Long param)
  {
    this.lowerbound = param;
  }


  public Long getUpperbound()
  {
     return this.upperbound;
  }
  public void setUpperbound(Long param)
  {
    this.upperbound = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionGfact()
  {
     return this.collDifferentialExpressionGfact;
  }
  public void setCollDifferentialExpressionGfact(java.util.Vector param)
  {
    this.collDifferentialExpressionGfact = param;
  }


}

