
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class AjTest
{
  private String dose;

  private Long doseId;

  public String getDose()
  {
     return this.dose;
  }
  public void setDose(String param)
  {
    this.dose = param;
  }


  public Long getDoseId()
  {
     return this.doseId;
  }
  public void setDoseId(Long param)
  {
    this.doseId = param;
  }


}

