
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class ArrayCghStg
{
  private String bacId;

  private Object channelRatio;

  private String chromosomeName;

  private String lossGain;

  public String getBacId()
  {
     return this.bacId;
  }
  public void setBacId(String param)
  {
    this.bacId = param;
  }


  public Object getChannelRatio()
  {
     return this.channelRatio;
  }
  public void setChannelRatio(Object param)
  {
    this.channelRatio = param;
  }


  public String getChromosomeName()
  {
     return this.chromosomeName;
  }
  public void setChromosomeName(String param)
  {
    this.chromosomeName = param;
  }


  public String getLossGain()
  {
     return this.lossGain;
  }
  public void setLossGain(String param)
  {
    this.lossGain = param;
  }


}

