
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class ArrayGenoAbnFact
{
  private Long agaId;

  private Long agentId;

  private String ageGroup;

  private Long biospecimenId;

  private Object channelRatio;

  private String chromosome;

  private Long cloneId;

  private Object copyNumber;

  private String cytoband;

  private Long datasetId;

  private Long diseaseHistoryId;

  private Long diseaseTypeId;

  private Long expPlatformId;

  private String genderCode;

  private Long geneId;

  private Long institutionId;

  private String loh;

  private String lossGain;

  private Long probesetId;

  private String survivalLengthRange;

  private Long timecourseId;

  private Long treatmentHistoryId;

  private gov.nih.nci.nautilus.data.StudyDatasetDim aStudyDatasetDim;

  private gov.nih.nci.nautilus.data.AgeGroupDx aAgeGroupDx;

  private gov.nih.nci.nautilus.data.DiseaseTypeDim aDiseaseTypeDim;

  private gov.nih.nci.nautilus.data.DiseaseHistory aDiseaseHistory;

  private gov.nih.nci.nautilus.data.BiospecimenDim aBiospecimenDim;

  private gov.nih.nci.nautilus.data.TreatmentHistory aTreatmentHistory;

  private gov.nih.nci.nautilus.data.ExpPlatformDim aExpPlatformDim;

  private gov.nih.nci.nautilus.data.Agent aAgent;

  private gov.nih.nci.nautilus.data.ProbesetDim aProbesetDim;

  private gov.nih.nci.nautilus.data.Gender aGender;

  private gov.nih.nci.nautilus.data.GeneDimOld aGeneDimOld;

  private gov.nih.nci.nautilus.data.InstitutionDim aInstitutionDim;

  private gov.nih.nci.nautilus.data.StudyTimecourseDim aStudyTimecourseDim;

  private gov.nih.nci.nautilus.data.SurvivalLengthRange aSurvivalLengthRange;

  private gov.nih.nci.nautilus.data.CloneDim aCloneDim;

  public Long getAgaId()
  {
     return this.agaId;
  }
  public void setAgaId(Long param)
  {
    this.agaId = param;
  }


  public Long getAgentId()
  {
     return this.agentId;
  }
  public void setAgentId(Long param)
  {
    this.agentId = param;
  }


  public String getAgeGroup()
  {
     return this.ageGroup;
  }
  public void setAgeGroup(String param)
  {
    this.ageGroup = param;
  }


  public Long getBiospecimenId()
  {
     return this.biospecimenId;
  }
  public void setBiospecimenId(Long param)
  {
    this.biospecimenId = param;
  }


  public Object getChannelRatio()
  {
     return this.channelRatio;
  }
  public void setChannelRatio(Object param)
  {
    this.channelRatio = param;
  }


  public String getChromosome()
  {
     return this.chromosome;
  }
  public void setChromosome(String param)
  {
    this.chromosome = param;
  }


  public Long getCloneId()
  {
     return this.cloneId;
  }
  public void setCloneId(Long param)
  {
    this.cloneId = param;
  }


  public Object getCopyNumber()
  {
     return this.copyNumber;
  }
  public void setCopyNumber(Object param)
  {
    this.copyNumber = param;
  }


  public String getCytoband()
  {
     return this.cytoband;
  }
  public void setCytoband(String param)
  {
    this.cytoband = param;
  }


  public Long getDatasetId()
  {
     return this.datasetId;
  }
  public void setDatasetId(Long param)
  {
    this.datasetId = param;
  }


  public Long getDiseaseHistoryId()
  {
     return this.diseaseHistoryId;
  }
  public void setDiseaseHistoryId(Long param)
  {
    this.diseaseHistoryId = param;
  }


  public Long getDiseaseTypeId()
  {
     return this.diseaseTypeId;
  }
  public void setDiseaseTypeId(Long param)
  {
    this.diseaseTypeId = param;
  }


  public Long getExpPlatformId()
  {
     return this.expPlatformId;
  }
  public void setExpPlatformId(Long param)
  {
    this.expPlatformId = param;
  }


  public String getGenderCode()
  {
     return this.genderCode;
  }
  public void setGenderCode(String param)
  {
    this.genderCode = param;
  }


  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public Long getInstitutionId()
  {
     return this.institutionId;
  }
  public void setInstitutionId(Long param)
  {
    this.institutionId = param;
  }


  public String getLoh()
  {
     return this.loh;
  }
  public void setLoh(String param)
  {
    this.loh = param;
  }


  public String getLossGain()
  {
     return this.lossGain;
  }
  public void setLossGain(String param)
  {
    this.lossGain = param;
  }


  public Long getProbesetId()
  {
     return this.probesetId;
  }
  public void setProbesetId(Long param)
  {
    this.probesetId = param;
  }


  public String getSurvivalLengthRange()
  {
     return this.survivalLengthRange;
  }
  public void setSurvivalLengthRange(String param)
  {
    this.survivalLengthRange = param;
  }


  public Long getTimecourseId()
  {
     return this.timecourseId;
  }
  public void setTimecourseId(Long param)
  {
    this.timecourseId = param;
  }


  public Long getTreatmentHistoryId()
  {
     return this.treatmentHistoryId;
  }
  public void setTreatmentHistoryId(Long param)
  {
    this.treatmentHistoryId = param;
  }


  public gov.nih.nci.nautilus.data.StudyDatasetDim getAStudyDatasetDim()
  {
     return this.aStudyDatasetDim;
  }
  public void setAStudyDatasetDim(gov.nih.nci.nautilus.data.StudyDatasetDim param)
  {
    this.aStudyDatasetDim = param;
  }


  public gov.nih.nci.nautilus.data.AgeGroupDx getAAgeGroupDx()
  {
     return this.aAgeGroupDx;
  }
  public void setAAgeGroupDx(gov.nih.nci.nautilus.data.AgeGroupDx param)
  {
    this.aAgeGroupDx = param;
  }


  public gov.nih.nci.nautilus.data.DiseaseTypeDim getADiseaseTypeDim()
  {
     return this.aDiseaseTypeDim;
  }
  public void setADiseaseTypeDim(gov.nih.nci.nautilus.data.DiseaseTypeDim param)
  {
    this.aDiseaseTypeDim = param;
  }


  public gov.nih.nci.nautilus.data.DiseaseHistory getADiseaseHistory()
  {
     return this.aDiseaseHistory;
  }
  public void setADiseaseHistory(gov.nih.nci.nautilus.data.DiseaseHistory param)
  {
    this.aDiseaseHistory = param;
  }


  public gov.nih.nci.nautilus.data.BiospecimenDim getABiospecimenDim()
  {
     return this.aBiospecimenDim;
  }
  public void setABiospecimenDim(gov.nih.nci.nautilus.data.BiospecimenDim param)
  {
    this.aBiospecimenDim = param;
  }


  public gov.nih.nci.nautilus.data.TreatmentHistory getATreatmentHistory()
  {
     return this.aTreatmentHistory;
  }
  public void setATreatmentHistory(gov.nih.nci.nautilus.data.TreatmentHistory param)
  {
    this.aTreatmentHistory = param;
  }


  public gov.nih.nci.nautilus.data.ExpPlatformDim getAExpPlatformDim()
  {
     return this.aExpPlatformDim;
  }
  public void setAExpPlatformDim(gov.nih.nci.nautilus.data.ExpPlatformDim param)
  {
    this.aExpPlatformDim = param;
  }


  public gov.nih.nci.nautilus.data.Agent getAAgent()
  {
     return this.aAgent;
  }
  public void setAAgent(gov.nih.nci.nautilus.data.Agent param)
  {
    this.aAgent = param;
  }


  public gov.nih.nci.nautilus.data.ProbesetDim getAProbesetDim()
  {
     return this.aProbesetDim;
  }
  public void setAProbesetDim(gov.nih.nci.nautilus.data.ProbesetDim param)
  {
    this.aProbesetDim = param;
  }


  public gov.nih.nci.nautilus.data.Gender getAGender()
  {
     return this.aGender;
  }
  public void setAGender(gov.nih.nci.nautilus.data.Gender param)
  {
    this.aGender = param;
  }


  public gov.nih.nci.nautilus.data.GeneDimOld getAGeneDimOld()
  {
     return this.aGeneDimOld;
  }
  public void setAGeneDimOld(gov.nih.nci.nautilus.data.GeneDimOld param)
  {
    this.aGeneDimOld = param;
  }


  public gov.nih.nci.nautilus.data.InstitutionDim getAInstitutionDim()
  {
     return this.aInstitutionDim;
  }
  public void setAInstitutionDim(gov.nih.nci.nautilus.data.InstitutionDim param)
  {
    this.aInstitutionDim = param;
  }


  public gov.nih.nci.nautilus.data.StudyTimecourseDim getAStudyTimecourseDim()
  {
     return this.aStudyTimecourseDim;
  }
  public void setAStudyTimecourseDim(gov.nih.nci.nautilus.data.StudyTimecourseDim param)
  {
    this.aStudyTimecourseDim = param;
  }


  public gov.nih.nci.nautilus.data.SurvivalLengthRange getASurvivalLengthRange()
  {
     return this.aSurvivalLengthRange;
  }
  public void setASurvivalLengthRange(gov.nih.nci.nautilus.data.SurvivalLengthRange param)
  {
    this.aSurvivalLengthRange = param;
  }


  public gov.nih.nci.nautilus.data.CloneDim getACloneDim()
  {
     return this.aCloneDim;
  }
  public void setACloneDim(gov.nih.nci.nautilus.data.CloneDim param)
  {
    this.aCloneDim = param;
  }


}

