
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class ArrayGenoAbnFact
{
  public final static String SNP_PROBESET_ID = "snpProbesetId";
    public final static String DISEASE_TYPE = "diseaseType";


  private Long agaId;

  private Long agentId;

  private String ageGroup;

  private Long biospecimenId;

  private Double channelRatio;

  private String chromosome;

  private Double copyNumber;
 private Double copynoPval;

    public String getSampleId() {
        return sampleId;
    }

    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }

    private String sampleId;

  private String cytoband;

  private Long datasetId;

  private Long diseaseHistoryId;

  private Long diseaseTypeId;
    private String diseaseType;


  private Long expPlatformId;

  private String genderCode;



  private Long institutionId;

  private Double loh;

  private String lossGain;

  private Long snpProbesetId;
    private String snpProbesetName ;

  private Long physicalPosition;

  private String survivalLengthRange;

  private Long timecourseId;

  private Long treatmentHistoryId;

    public Long getAgaId() {
        return agaId;
    }

    public void setAgaId(Long agaId) {
        this.agaId = agaId;
    }

    public Long getAgentId() {
        return agentId;
    }

    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }

    public String getAgeGroup() {
        return ageGroup;
    }

    public void setAgeGroup(String ageGroup) {
        this.ageGroup = ageGroup;
    }

    public Long getBiospecimenId() {
        return biospecimenId;
    }

    public void setBiospecimenId(Long biospecimenId) {
        this.biospecimenId = biospecimenId;
    }

    public Double getChannelRatio() {
        return channelRatio;
    }

    public void setChannelRatio(Double channelRatio) {
        this.channelRatio = channelRatio;
    }

    public String getChromosome() {
        return chromosome;
    }

    public void setChromosome(String chromosome) {
        this.chromosome = chromosome;
    }

    public Double getCopyNumber() {
        return copyNumber;
    }

    public void setCopyNumber(Double copyNumber) {
        this.copyNumber = copyNumber;
    }

    public Double getCopynoPval() {
        return copynoPval;
    }

    public void setCopynoPval(Double copynoPval) {
        this.copynoPval = copynoPval;
    }

    public String getCytoband() {
        return cytoband;
    }

    public void setCytoband(String cytoband) {
        this.cytoband = cytoband;
    }

    public Long getDatasetId() {
        return datasetId;
    }

    public void setDatasetId(Long datasetId) {
        this.datasetId = datasetId;
    }

    public Long getDiseaseHistoryId() {
        return diseaseHistoryId;
    }

    public void setDiseaseHistoryId(Long diseaseHistoryId) {
        this.diseaseHistoryId = diseaseHistoryId;
    }

    public Long getDiseaseTypeId() {
        return diseaseTypeId;
    }

    public void setDiseaseTypeId(Long diseaseTypeId) {
        this.diseaseTypeId = diseaseTypeId;
    }

    public String getDiseaseType() {
        return diseaseType;
    }

    public void setDiseaseType(String diseaseType) {
        this.diseaseType = diseaseType;
    }

    public Long getExpPlatformId() {
        return expPlatformId;
    }

    public void setExpPlatformId(Long expPlatformId) {
        this.expPlatformId = expPlatformId;
    }

    public String getGenderCode() {
        return genderCode;
    }

    public void setGenderCode(String genderCode) {
        this.genderCode = genderCode;
    }



    public Long getInstitutionId() {
        return institutionId;
    }

    public void setInstitutionId(Long institutionId) {
        this.institutionId = institutionId;
    }

    public Double getLoh() {
        return loh;
    }

    public void setLoh(Double loh) {
        this.loh = loh;
    }

    public String getLossGain() {
        return lossGain;
    }

    public void setLossGain(String lossGain) {
        this.lossGain = lossGain;
    }

    public Long getSnpProbesetId() {
        return snpProbesetId;
    }

    public void setSnpProbesetId(Long snpProbesetId) {
        this.snpProbesetId = snpProbesetId;
    }

    public String getSnpProbesetName() {
        return snpProbesetName;
    }

    public void setSnpProbesetName(String snpProbesetName) {
        this.snpProbesetName = snpProbesetName;
    }

    public Long getPhysicalPosition() {
        return physicalPosition;
    }

    public void setPhysicalPosition(Long physicalPosition) {
        this.physicalPosition = physicalPosition;
    }

    public String getSurvivalLengthRange() {
        return survivalLengthRange;
    }

    public void setSurvivalLengthRange(String survivalLengthRange) {
        this.survivalLengthRange = survivalLengthRange;
    }

    public Long getTimecourseId() {
        return timecourseId;
    }

    public void setTimecourseId(Long timecourseId) {
        this.timecourseId = timecourseId;
    }

    public Long getTreatmentHistoryId() {
        return treatmentHistoryId;
    }

    public void setTreatmentHistoryId(Long treatmentHistoryId) {
        this.treatmentHistoryId = treatmentHistoryId;
    }

}

