
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class BacGeneStg
{
  private String bacId;

  private Long geneId;

  private String geneSymbol;

  public String getBacId()
  {
     return this.bacId;
  }
  public void setBacId(String param)
  {
    this.bacId = param;
  }


  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public String getGeneSymbol()
  {
     return this.geneSymbol;
  }
  public void setGeneSymbol(String param)
  {
    this.geneSymbol = param;
  }


}

