
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;


public class CloneDim
{
  public final static String CLONE_ID = "cloneId";
  public final static String GENE_SYMBOL = "geneSymbol";
  public final static String CYTOBAND = "cytoband";
  public final static String ACCESSION_NUMBER = "accessionNumber";

  private String accessionNumber;

  private String cloneDesc;

  private Long cloneId;

  private String cloneLocation;

  private String cloneName;

    public String getCytoband() {
        return cytoband;
    }

    public void setCytoband(String cytoband) {
        this.cytoband = cytoband;
    }

    private String cytoband;

  private String cloneType;

  private String library;

  private String unigeneId;

  private Long unigeneLibrary;

  private Long utr;

  //private java.util.Vector collDifferentialExpressionSfact;

  //private java.util.Vector collGeneClone;

  //private java.util.Vector collArrayGenoAbnFact;

 // private java.util.Vector collDifferentialExpressionGfact;

  public String getAccessionNumber()
  {
     return this.accessionNumber;
  }
  public void setAccessionNumber(String param)
  {
    this.accessionNumber = param;
  }


  public String getCloneDesc()
  {
     return this.cloneDesc;
  }
  public void setCloneDesc(String param)
  {
    this.cloneDesc = param;
  }


  public Long getCloneId()
  {
     return this.cloneId;
  }
  public void setCloneId(Long param)
  {
    this.cloneId = param;
  }


  public String getCloneLocation()
  {
     return this.cloneLocation;
  }
  public void setCloneLocation(String param)
  {
    this.cloneLocation = param;
  }


  public String getCloneName()
  {
     return this.cloneName;
  }
  public void setCloneName(String param)
  {
    this.cloneName = param;
  }


  public String getCloneType()
  {
     return this.cloneType;
  }
  public void setCloneType(String param)
  {
    this.cloneType = param;
  }


  public String getLibrary()
  {
     return this.library;
  }
  public void setLibrary(String param)
  {
    this.library = param;
  }


  public String getUnigeneId()
  {
     return this.unigeneId;
  }
  public void setUnigeneId(String param)
  {
    this.unigeneId = param;
  }


  public Long getUnigeneLibrary()
  {
     return this.unigeneLibrary;
  }
  public void setUnigeneLibrary(Long param)
  {
    this.unigeneLibrary = param;
  }


  public Long getUtr()
  {
     return this.utr;
  }
  public void setUtr(Long param)
  {
    this.utr = param;
  }


 /* public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


  public java.util.Vector getCollGeneClone()
  {
     return this.collGeneClone;
  }
  public void setCollGeneClone(java.util.Vector param)
  {
    this.collGeneClone = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionGfact()
  {
     return this.collDifferentialExpressionGfact;
  }
  public void setCollDifferentialExpressionGfact(java.util.Vector param)
  {
    this.collDifferentialExpressionGfact = param;
  }
*/

}

