
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class CytogeneticMap
{
  private String chromosome;

  private String cytogeneticMap;

  private Long cytogeneticMapId;

  private String organism;

  public String getChromosome()
  {
     return this.chromosome;
  }
  public void setChromosome(String param)
  {
    this.chromosome = param;
  }


  public String getCytogeneticMap()
  {
     return this.cytogeneticMap;
  }
  public void setCytogeneticMap(String param)
  {
    this.cytogeneticMap = param;
  }


  public Long getCytogeneticMapId()
  {
     return this.cytogeneticMapId;
  }
  public void setCytogeneticMapId(Long param)
  {
    this.cytogeneticMapId = param;
  }


  public String getOrganism()
  {
     return this.organism;
  }
  public void setOrganism(String param)
  {
    this.organism = param;
  }


}

