
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class DetectionType
{
  private String detectionType;

  private String detectionTypeDesc;

  private Long detectionTypeId;

  public String getDetectionType()
  {
     return this.detectionType;
  }
  public void setDetectionType(String param)
  {
    this.detectionType = param;
  }


  public String getDetectionTypeDesc()
  {
     return this.detectionTypeDesc;
  }
  public void setDetectionTypeDesc(String param)
  {
    this.detectionTypeDesc = param;
  }


  public Long getDetectionTypeId()
  {
     return this.detectionTypeId;
  }
  public void setDetectionTypeId(Long param)
  {
    this.detectionTypeId = param;
  }


}

