
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class DifferentialExpressionGfact
{
  private String ageGroup;

  private Long biospecimenId;

  private Long cloneId;

  private Long datasetId;

  private Long degId;

  private Long diseaseTypeId;

  private Object expressionRatio;

  private Long expPlatformId;

  private String genderCode;

  private Long geneId;

  private Long institutionId;

  private Object normalIntensity;

  private Long probesetId;

  private String ratioPval;

  private Object sampleGIntensity;

  private String survivalLengthRange;

  private Long timecourseId;

  private gov.nih.nci.nautilus.data.StudyDatasetDim aStudyDatasetDim;

  private gov.nih.nci.nautilus.data.AgeGroupDx aAgeGroupDx;

  private gov.nih.nci.nautilus.data.GeneDimOld aGeneDimOld;

  private gov.nih.nci.nautilus.data.InstitutionDim aInstitutionDim;

  private gov.nih.nci.nautilus.data.StudyTimecourseDim aStudyTimecourseDim;

  private gov.nih.nci.nautilus.data.DiseaseTypeDim aDiseaseTypeDim;

  private gov.nih.nci.nautilus.data.SurvivalLengthRange aSurvivalLengthRange;

  private gov.nih.nci.nautilus.data.ExpPlatformDim aExpPlatformDim;

  private gov.nih.nci.nautilus.data.ProbesetDim aProbesetDim;

  private gov.nih.nci.nautilus.data.CloneDim aCloneDim;

  private gov.nih.nci.nautilus.data.Gender aGender;

  public String getAgeGroup()
  {
     return this.ageGroup;
  }
  public void setAgeGroup(String param)
  {
    this.ageGroup = param;
  }


  public Long getBiospecimenId()
  {
     return this.biospecimenId;
  }
  public void setBiospecimenId(Long param)
  {
    this.biospecimenId = param;
  }


  public Long getCloneId()
  {
     return this.cloneId;
  }
  public void setCloneId(Long param)
  {
    this.cloneId = param;
  }


  public Long getDatasetId()
  {
     return this.datasetId;
  }
  public void setDatasetId(Long param)
  {
    this.datasetId = param;
  }


  public Long getDegId()
  {
     return this.degId;
  }
  public void setDegId(Long param)
  {
    this.degId = param;
  }


  public Long getDiseaseTypeId()
  {
     return this.diseaseTypeId;
  }
  public void setDiseaseTypeId(Long param)
  {
    this.diseaseTypeId = param;
  }


  public Object getExpressionRatio()
  {
     return this.expressionRatio;
  }
  public void setExpressionRatio(Object param)
  {
    this.expressionRatio = param;
  }


  public Long getExpPlatformId()
  {
     return this.expPlatformId;
  }
  public void setExpPlatformId(Long param)
  {
    this.expPlatformId = param;
  }


  public String getGenderCode()
  {
     return this.genderCode;
  }
  public void setGenderCode(String param)
  {
    this.genderCode = param;
  }


  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public Long getInstitutionId()
  {
     return this.institutionId;
  }
  public void setInstitutionId(Long param)
  {
    this.institutionId = param;
  }


  public Object getNormalIntensity()
  {
     return this.normalIntensity;
  }
  public void setNormalIntensity(Object param)
  {
    this.normalIntensity = param;
  }


  public Long getProbesetId()
  {
     return this.probesetId;
  }
  public void setProbesetId(Long param)
  {
    this.probesetId = param;
  }


  public String getRatioPval()
  {
     return this.ratioPval;
  }
  public void setRatioPval(String param)
  {
    this.ratioPval = param;
  }


  public Object getSampleGIntensity()
  {
     return this.sampleGIntensity;
  }
  public void setSampleGIntensity(Object param)
  {
    this.sampleGIntensity = param;
  }


  public String getSurvivalLengthRange()
  {
     return this.survivalLengthRange;
  }
  public void setSurvivalLengthRange(String param)
  {
    this.survivalLengthRange = param;
  }


  public Long getTimecourseId()
  {
     return this.timecourseId;
  }
  public void setTimecourseId(Long param)
  {
    this.timecourseId = param;
  }


  public gov.nih.nci.nautilus.data.StudyDatasetDim getAStudyDatasetDim()
  {
     return this.aStudyDatasetDim;
  }
  public void setAStudyDatasetDim(gov.nih.nci.nautilus.data.StudyDatasetDim param)
  {
    this.aStudyDatasetDim = param;
  }


  public gov.nih.nci.nautilus.data.AgeGroupDx getAAgeGroupDx()
  {
     return this.aAgeGroupDx;
  }
  public void setAAgeGroupDx(gov.nih.nci.nautilus.data.AgeGroupDx param)
  {
    this.aAgeGroupDx = param;
  }


  public gov.nih.nci.nautilus.data.GeneDimOld getAGeneDimOld()
  {
     return this.aGeneDimOld;
  }
  public void setAGeneDimOld(gov.nih.nci.nautilus.data.GeneDimOld param)
  {
    this.aGeneDimOld = param;
  }


  public gov.nih.nci.nautilus.data.InstitutionDim getAInstitutionDim()
  {
     return this.aInstitutionDim;
  }
  public void setAInstitutionDim(gov.nih.nci.nautilus.data.InstitutionDim param)
  {
    this.aInstitutionDim = param;
  }


  public gov.nih.nci.nautilus.data.StudyTimecourseDim getAStudyTimecourseDim()
  {
     return this.aStudyTimecourseDim;
  }
  public void setAStudyTimecourseDim(gov.nih.nci.nautilus.data.StudyTimecourseDim param)
  {
    this.aStudyTimecourseDim = param;
  }


  public gov.nih.nci.nautilus.data.DiseaseTypeDim getADiseaseTypeDim()
  {
     return this.aDiseaseTypeDim;
  }
  public void setADiseaseTypeDim(gov.nih.nci.nautilus.data.DiseaseTypeDim param)
  {
    this.aDiseaseTypeDim = param;
  }


  public gov.nih.nci.nautilus.data.SurvivalLengthRange getASurvivalLengthRange()
  {
     return this.aSurvivalLengthRange;
  }
  public void setASurvivalLengthRange(gov.nih.nci.nautilus.data.SurvivalLengthRange param)
  {
    this.aSurvivalLengthRange = param;
  }


  public gov.nih.nci.nautilus.data.ExpPlatformDim getAExpPlatformDim()
  {
     return this.aExpPlatformDim;
  }
  public void setAExpPlatformDim(gov.nih.nci.nautilus.data.ExpPlatformDim param)
  {
    this.aExpPlatformDim = param;
  }


  public gov.nih.nci.nautilus.data.ProbesetDim getAProbesetDim()
  {
     return this.aProbesetDim;
  }
  public void setAProbesetDim(gov.nih.nci.nautilus.data.ProbesetDim param)
  {
    this.aProbesetDim = param;
  }


  public gov.nih.nci.nautilus.data.CloneDim getACloneDim()
  {
     return this.aCloneDim;
  }
  public void setACloneDim(gov.nih.nci.nautilus.data.CloneDim param)
  {
    this.aCloneDim = param;
  }


  public gov.nih.nci.nautilus.data.Gender getAGender()
  {
     return this.aGender;
  }
  public void setAGender(gov.nih.nci.nautilus.data.Gender param)
  {
    this.aGender = param;
  }


}

