
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

import gov.nih.nci.nautilus.util.HashCodeUtil;

public class DifferentialExpressionSfact
{
    public final static String DES_ID = "desId";
    public final static String CLONE_ID = "cloneId";
    public final static String PROBESET_ID= "probesetId";
    public final static String CLONE_NAME = "cloneName";
    public final static String PROBE_NAME = "probesetName";
    public final static String GENE_SYMBOL = "geneSymbol";
    public final static String BIOSPECIMEN_ID = "biospecimenId";
    public final static String EXPRESSION_RATIO = "expressionRatio";


  private Long agentId;

  private String ageGroup;

  private Long biospecimenId;

  private Long cloneId;

  private Long datasetId;

  private Long desId;

  private Long diseaseHistoryId;

  private Long diseaseTypeId;

  private Double expressionRatio;

  private Long expPlatformId;

  private String genderCode;
  private String probesetName;

    public String getCloneName() {
        return cloneName;
    }

    private String cloneName;

    public String getProbesetName() {
        return probesetName;
    }

  private String geneSymbol;

    public String getGeneSymbol() {
        return geneSymbol;
    }

    public void setGeneSymbol(String geneSymbol) {
        this.geneSymbol = geneSymbol;
    }

  private Long institutionId;

  private Double normalIntensity;

  private Long probesetId;

  private Double sampleIntensity;

  private String survivalLengthRange;

  private Long timecourseId;

  private Long treatmentHistoryId;

  private StudyDatasetDim aStudyDatasetDim;

  private AgeGroupDx aAgeGroupDx;

  private DiseaseTypeDim aDiseaseTypeDim;

  private DiseaseHistory aDiseaseHistory;

  private BiospecimenDim aBiospecimenDim;

  private TreatmentHistory aTreatmentHistory;

  private ExpPlatformDim aExpPlatformDim;

  private Agent aAgent;

  private ProbesetDim aProbesetDim;

  private Gender aGender;

  private InstitutionDim aInstitutionDim;

  private StudyTimecourseDim aStudyTimecourseDim;

  private SurvivalLengthRange aSurvivalLengthRange;

  private ProbesetDim aGeneDim;

  private CloneDim aCloneDim;

  public Long getAgentId()
  {
     return this.agentId;
  }
  public void setAgentId(Long param)
  {
    this.agentId = param;
  }


  public String getAgeGroup()
  {
     return this.ageGroup;
  }
  public void setAgeGroup(String param)
  {
    this.ageGroup = param;
  }


  public Long getBiospecimenId()
  {
     return this.biospecimenId;
  }
  public void setBiospecimenId(Long param)
  {
    this.biospecimenId = param;
  }


  public Long getCloneId()
  {
     return this.cloneId;
  }
  public void setCloneId(Long param)
  {
    this.cloneId = param;
  }


  public Long getDatasetId()
  {
     return this.datasetId;
  }
  public void setDatasetId(Long param)
  {
    this.datasetId = param;
  }


  public Long getDesId()
  {
     return this.desId;
  }
  public void setDesId(Long param)
  {
    this.desId = param;
  }


  public Long getDiseaseHistoryId()
  {
     return this.diseaseHistoryId;
  }
  public void setDiseaseHistoryId(Long param)
  {
    this.diseaseHistoryId = param;
  }


  public Long getDiseaseTypeId()
  {
     return this.diseaseTypeId;
  }
  public void setDiseaseTypeId(Long param)
  {
    this.diseaseTypeId = param;
  }


  public Double getExpressionRatio()
  {
     return this.expressionRatio;
  }
  public void setExpressionRatio(Double param)
  {
    this.expressionRatio = param;
  }


  public Long getExpPlatformId()
  {
     return this.expPlatformId;
  }
  public void setExpPlatformId(Long param)
  {
    this.expPlatformId = param;
  }


  public String getGenderCode()
  {
     return this.genderCode;
  }
  public void setGenderCode(String param)
  {
    this.genderCode = param;
  }

  public Long getInstitutionId()
  {
     return this.institutionId;
  }
  public void setInstitutionId(Long param)
  {
    this.institutionId = param;
  }


  public Double getNormalIntensity()
  {
     return this.normalIntensity;
  }
  public void setNormalIntensity(Double param)
  {
    this.normalIntensity = param;
  }


  public Long getProbesetId()
  {
     return this.probesetId;
  }
  public void setProbesetId(Long param)
  {
    this.probesetId = param;
  }


  public Double getSampleIntensity()
  {
     return this.sampleIntensity;
  }
  public void setSampleIntensity(Double param)
  {
    this.sampleIntensity = param;
  }


  public String getSurvivalLengthRange()
  {
     return this.survivalLengthRange;
  }
  public void setSurvivalLengthRange(String param)
  {
    this.survivalLengthRange = param;
  }


  public Long getTimecourseId()
  {
     return this.timecourseId;
  }
  public void setTimecourseId(Long param)
  {
    this.timecourseId = param;
  }


  public Long getTreatmentHistoryId()
  {
     return this.treatmentHistoryId;
  }
  public void setTreatmentHistoryId(Long param)
  {
    this.treatmentHistoryId = param;
  }


  public StudyDatasetDim getAStudyDatasetDim()
  {
     return this.aStudyDatasetDim;
  }
  public void setAStudyDatasetDim(StudyDatasetDim param)
  {
    this.aStudyDatasetDim = param;
  }


  public AgeGroupDx getAAgeGroupDx()
  {
     return this.aAgeGroupDx;
  }
  public void setAAgeGroupDx(AgeGroupDx param)
  {
    this.aAgeGroupDx = param;
  }


  public DiseaseTypeDim getADiseaseTypeDim()
  {
     return this.aDiseaseTypeDim;
  }
  public void setADiseaseTypeDim(DiseaseTypeDim param)
  {
    this.aDiseaseTypeDim = param;
  }


  public DiseaseHistory getADiseaseHistory()
  {
     return this.aDiseaseHistory;
  }
  public void setADiseaseHistory(DiseaseHistory param)
  {
    this.aDiseaseHistory = param;
  }


  public BiospecimenDim getABiospecimenDim()
  {
     return this.aBiospecimenDim;
  }
  public void setABiospecimenDim(BiospecimenDim param)
  {
    this.aBiospecimenDim = param;
  }


  public TreatmentHistory getATreatmentHistory()
  {
     return this.aTreatmentHistory;
  }
  public void setATreatmentHistory(TreatmentHistory param)
  {
    this.aTreatmentHistory = param;
  }


  public ExpPlatformDim getAExpPlatformDim()
  {
     return this.aExpPlatformDim;
  }
  public void setAExpPlatformDim(ExpPlatformDim param)
  {
    this.aExpPlatformDim = param;
  }


  public Agent getAAgent()
  {
     return this.aAgent;
  }
  public void setAAgent(Agent param)
  {
    this.aAgent = param;
  }


  public ProbesetDim getAProbesetDim()
  {
     return this.aProbesetDim;
  }
  public void setAProbesetDim(ProbesetDim param)
  {
    this.aProbesetDim = param;
  }


  public Gender getAGender()
  {
     return this.aGender;
  }
  public void setAGender(Gender param)
  {
    this.aGender = param;
  }


  public InstitutionDim getAInstitutionDim()
  {
     return this.aInstitutionDim;
  }
  public void setAInstitutionDim(InstitutionDim param)
  {
    this.aInstitutionDim = param;
  }


  public StudyTimecourseDim getAStudyTimecourseDim()
  {
     return this.aStudyTimecourseDim;
  }
  public void setAStudyTimecourseDim(StudyTimecourseDim param)
  {
    this.aStudyTimecourseDim = param;
  }


  public SurvivalLengthRange getASurvivalLengthRange()
  {
     return this.aSurvivalLengthRange;
  }
  public void setASurvivalLengthRange(SurvivalLengthRange param)
  {
    this.aSurvivalLengthRange = param;
  }


  public ProbesetDim getAGeneDim()
  {
     return this.aGeneDim;
  }
  public void setAGeneDim(ProbesetDim param)
  {
    this.aGeneDim = param;
  }


  public CloneDim getACloneDim()
  {
     return this.aCloneDim;
  }
  public void setACloneDim(CloneDim param)
  {
    this.aCloneDim = param;
  }

  public int hashCode() {
        int result = HashCodeUtil.SEED;
        result = HashCodeUtil.hash( result, cloneId);
        result = HashCodeUtil.hash( result, probesetId);

        //TODO: complete this
        return result;
    }
}

