
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class DiseaseGrade
{
  private String grade;

  private String gradeDesc;

  private Long gradeId;

  public String getGrade()
  {
     return this.grade;
  }
  public void setGrade(String param)
  {
    this.grade = param;
  }


  public String getGradeDesc()
  {
     return this.gradeDesc;
  }
  public void setGradeDesc(String param)
  {
    this.gradeDesc = param;
  }


  public Long getGradeId()
  {
     return this.gradeId;
  }
  public void setGradeId(Long param)
  {
    this.gradeId = param;
  }


}

