
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

import gov.nih.nci.nautilus.lookup.DiseaseTypeLookup;

public class DiseaseTypeDim implements DiseaseTypeLookup
{
  private String diseaseDesc;

  private String diseaseType;

  private Long diseaseTypeId;

  private java.util.Vector collDifferentialExpressionSfact;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collDifferentialExpressionGfact;

  public String getDiseaseDesc()
  {
     return this.diseaseDesc;
  }
  public void setDiseaseDesc(String param)
  {
    this.diseaseDesc = param;
  }


  public String getDiseaseType()
  {
     return this.diseaseType;
  }
  public void setDiseaseType(String param)
  {
    this.diseaseType = param;
  }


  public Long getDiseaseTypeId()
  {
     return this.diseaseTypeId;
  }
  public void setDiseaseTypeId(Long param)
  {
    this.diseaseTypeId = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionGfact()
  {
     return this.collDifferentialExpressionGfact;
  }
  public void setCollDifferentialExpressionGfact(java.util.Vector param)
  {
    this.collDifferentialExpressionGfact = param;
  }


}

