
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class GeneLlAcc
{
  public final static String GENE_SYMBOL = "geneSymbol";
  public final static String START_POSITION = "cStart";
  public final static String END_POSITION = "cEnd";
  public final static String ACCESSION = "accession";
  public final static String CHROMOSOME = "chromosome";

  private String accession;

  private String chromosome;

  private String cytoband;

  private Long cEnd;

  private Long cStart;

  private String geneSymbol;

  private String geneTitle;

  private String imageId;

  private String llId;

  private String omimId;

  private String tname;

  public String getAccession()
  {
     return this.accession;
  }
  public void setAccession(String param)
  {
    this.accession = param;
  }


  public String getChromosome()
  {
     return this.chromosome;
  }
  public void setChromosome(String param)
  {
    this.chromosome = param;
  }


  public String getCytoband()
  {
     return this.cytoband;
  }
  public void setCytoband(String param)
  {
    this.cytoband = param;
  }


  public Long getCEnd()
  {
     return this.cEnd;
  }
  public void setCEnd(Long param)
  {
    this.cEnd = param;
  }


  public Long getCStart()
  {
     return this.cStart;
  }
  public void setCStart(Long param)
  {
    this.cStart = param;
  }


  public String getGeneSymbol()
  {
     return this.geneSymbol;
  }
  public void setGeneSymbol(String param)
  {
    this.geneSymbol = param;
  }


  public String getGeneTitle()
  {
     return this.geneTitle;
  }
  public void setGeneTitle(String param)
  {
    this.geneTitle = param;
  }


  public String getImageId()
  {
     return this.imageId;
  }
  public void setImageId(String param)
  {
    this.imageId = param;
  }


  public String getLlId()
  {
     return this.llId;
  }
  public void setLlId(String param)
  {
    this.llId = param;
  }


  public String getOmimId()
  {
     return this.omimId;
  }
  public void setOmimId(String param)
  {
    this.omimId = param;
  }


  public String getTname()
  {
     return this.tname;
  }
  public void setTname(String param)
  {
    this.tname = param;
  }


}

