
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class GeneOntologyStg
{
  private String goDesc;

  private String goId;

  private String probesetName;

  public String getGoDesc()
  {
     return this.goDesc;
  }
  public void setGoDesc(String param)
  {
    this.goDesc = param;
  }


  public String getGoId()
  {
     return this.goId;
  }
  public void setGoId(String param)
  {
    this.goId = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


}

