
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class GenePathway
{
  private Long geneId;

  private Long pathwayId;

  private gov.nih.nci.nautilus.data.GeneDimOld aGeneDimOld;

  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public Long getPathwayId()
  {
     return this.pathwayId;
  }
  public void setPathwayId(Long param)
  {
    this.pathwayId = param;
  }


  public gov.nih.nci.nautilus.data.GeneDimOld getAGeneDimOld()
  {
     return this.aGeneDimOld;
  }
  public void setAGeneDimOld(gov.nih.nci.nautilus.data.GeneDimOld param)
  {
    this.aGeneDimOld = param;
  }


}

