// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;


public class GeneClone {
	public final static String CLONE_ID = "cloneId";

	public final static String CHROMOSOME = "chromosome";

	public final static String LOCUS_LINK = "llId";

	public final static String ACCESSION_NUMBER = "accessionNumber";

	private String accessionNumber;

	private Long accEnd;

	private Long accStart;

	private Long cloneId;

	private String ec;

	private String geneCloneId;

	public String getChromosome() {
		return chromosome;
	}

	public void setChromosome(String chromosome) {
		this.chromosome = chromosome;
	}

	private String chromosome;

	private String geneSymbol;

	private String geneTitle;

	private String llId;

	private String ominId;

	private String unigeneId;

	private String unigeneLibrary;

	public String getAccessionNumber() {
		return this.accessionNumber;
	}

	public void setAccessionNumber(String param) {
		this.accessionNumber = param;
	}

	public Long getAccEnd() {
		return this.accEnd;
	}

	public void setAccEnd(Long param) {
		this.accEnd = param;
	}

	public Long getAccStart() {
		return this.accStart;
	}

	public void setAccStart(Long param) {
		this.accStart = param;
	}

	public Long getCloneId() {
		return this.cloneId;
	}

	public void setCloneId(Long param) {
		this.cloneId = param;
	}

	public String getEc() {
		return this.ec;
	}

	public void setEc(String param) {
		this.ec = param;
	}

	public String getGeneCloneId() {
		return this.geneCloneId;
	}

	public void setGeneCloneId(String param) {
		this.geneCloneId = param;
	}

	public String getGeneSymbol() {
		return this.geneSymbol;
	}

	public void setGeneSymbol(String param) {
		this.geneSymbol = param;
	}

	public String getGeneTitle() {
		return this.geneTitle;
	}

	public void setGeneTitle(String param) {
		this.geneTitle = param;
	}

	public String getLlId() {
		return this.llId;
	}

	public void setLlId(String param) {
		this.llId = param;
	}

	public String getOminId() {
		return this.ominId;
	}

	public void setOminId(String param) {
		this.ominId = param;
	}

	public String getUnigeneId() {
		return this.unigeneId;
	}

	public void setUnigeneId(String param) {
		this.unigeneId = param;
	}

	public String getUnigeneLibrary() {
		return this.unigeneLibrary;
	}

	public void setUnigeneLibrary(String param) {
		this.unigeneLibrary = param;
	}

}

