
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class GenePathway
{
     public final static String PATHWAY_NAME = "pathwayName";
    public final static String GENE_SYMBOL = "geneSymbol";

  private String geneSymbol;

  private String pathwayName;
    private String dataSource;
    private String pathwayDesc;

    public String getGeneSymbol() {
        return geneSymbol;
    }

    public void setGeneSymbol(String geneSymbol) {
        this.geneSymbol = geneSymbol;
    }

    public String getPathwayName() {
        return pathwayName;
    }

    public void setPathwayName(String pathwayName) {
        this.pathwayName = pathwayName;
    }

    public String getDataSource() {
        return dataSource;
    }

    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    public String getPathwayDesc() {
        return pathwayDesc;
    }

    public void setPathwayDesc(String pathwayDesc) {
        this.pathwayDesc = pathwayDesc;
    }


}

