
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class GeneExpressionSignalSstg
{
  private String dataSet;

  private String institutionName;

  private Object normalIntensity;

  private String probesetName;

  private Object ratio;

  private String sampleId;

  private Object sampleIntensity;

  public String getDataSet()
  {
     return this.dataSet;
  }
  public void setDataSet(String param)
  {
    this.dataSet = param;
  }


  public String getInstitutionName()
  {
     return this.institutionName;
  }
  public void setInstitutionName(String param)
  {
    this.institutionName = param;
  }


  public Object getNormalIntensity()
  {
     return this.normalIntensity;
  }
  public void setNormalIntensity(Object param)
  {
    this.normalIntensity = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public Object getRatio()
  {
     return this.ratio;
  }
  public void setRatio(Object param)
  {
    this.ratio = param;
  }


  public String getSampleId()
  {
     return this.sampleId;
  }
  public void setSampleId(String param)
  {
    this.sampleId = param;
  }


  public Object getSampleIntensity()
  {
     return this.sampleIntensity;
  }
  public void setSampleIntensity(Object param)
  {
    this.sampleIntensity = param;
  }


}

