
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class GeneExpressionSignalGstg
{
  private String dataSet;

  private String institutionName;

  private Object normalIntensity;

  private String probesetName;

  private Object ratio;

  private Object ratioPval;

  private Object sampleIntensity;

  private String sampleType;

  public String getDataSet()
  {
     return this.dataSet;
  }
  public void setDataSet(String param)
  {
    this.dataSet = param;
  }


  public String getInstitutionName()
  {
     return this.institutionName;
  }
  public void setInstitutionName(String param)
  {
    this.institutionName = param;
  }


  public Object getNormalIntensity()
  {
     return this.normalIntensity;
  }
  public void setNormalIntensity(Object param)
  {
    this.normalIntensity = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public Object getRatio()
  {
     return this.ratio;
  }
  public void setRatio(Object param)
  {
    this.ratio = param;
  }


  public Object getRatioPval()
  {
     return this.ratioPval;
  }
  public void setRatioPval(Object param)
  {
    this.ratioPval = param;
  }


  public Object getSampleIntensity()
  {
     return this.sampleIntensity;
  }
  public void setSampleIntensity(Object param)
  {
    this.sampleIntensity = param;
  }


  public String getSampleType()
  {
     return this.sampleType;
  }
  public void setSampleType(String param)
  {
    this.sampleType = param;
  }


}

