
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class GeneStgVw
{
  private String alignments;

  private String chrom;

  private String cytoband;

  private String ec;

  private String geneSymbol;

  private String geneTitle;

  private String genomeVersion;

  private Long kbend;

  private Long kbstart;

  private String locuslink;

  private String omim;

  private String unigeneId;

  public String getAlignments()
  {
     return this.alignments;
  }
  public void setAlignments(String param)
  {
    this.alignments = param;
  }


  public String getChrom()
  {
     return this.chrom;
  }
  public void setChrom(String param)
  {
    this.chrom = param;
  }


  public String getCytoband()
  {
     return this.cytoband;
  }
  public void setCytoband(String param)
  {
    this.cytoband = param;
  }


  public String getEc()
  {
     return this.ec;
  }
  public void setEc(String param)
  {
    this.ec = param;
  }


  public String getGeneSymbol()
  {
     return this.geneSymbol;
  }
  public void setGeneSymbol(String param)
  {
    this.geneSymbol = param;
  }


  public String getGeneTitle()
  {
     return this.geneTitle;
  }
  public void setGeneTitle(String param)
  {
    this.geneTitle = param;
  }


  public String getGenomeVersion()
  {
     return this.genomeVersion;
  }
  public void setGenomeVersion(String param)
  {
    this.genomeVersion = param;
  }


  public Long getKbend()
  {
     return this.kbend;
  }
  public void setKbend(Long param)
  {
    this.kbend = param;
  }


  public Long getKbstart()
  {
     return this.kbstart;
  }
  public void setKbstart(Long param)
  {
    this.kbstart = param;
  }


  public String getLocuslink()
  {
     return this.locuslink;
  }
  public void setLocuslink(String param)
  {
    this.locuslink = param;
  }


  public String getOmim()
  {
     return this.omim;
  }
  public void setOmim(String param)
  {
    this.omim = param;
  }


  public String getUnigeneId()
  {
     return this.unigeneId;
  }
  public void setUnigeneId(String param)
  {
    this.unigeneId = param;
  }


}

