
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class GeneDimOld
{
  private String alignments;

  private String chromosome;

  private String cytogeneticMap;

  private String ec;

  private Long geneId;

  private String geneSymbol;

  private String geneTitle;

  private String genomeVersion;

  private Long kbEnd;

  private Long kbStart;

  private String llId;

  private String ominId;

  private String unigeneId;

  private java.util.Vector collRefseqProteinId;

  private java.util.Vector collGeneOntology;

  private java.util.Vector collGeneClone;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collSwissprot;

  private java.util.Vector collRefseqMrnaId;

  private java.util.Vector collDifferentialExpressionGfact;

  private java.util.Vector collGeneProbeset;

  private java.util.Vector collDifferentialExpressionSfact;

  private java.util.Vector collProteinFamily;

  private java.util.Vector collGenePathway;

  public String getAlignments()
  {
     return this.alignments;
  }
  public void setAlignments(String param)
  {
    this.alignments = param;
  }


  public String getChromosome()
  {
     return this.chromosome;
  }
  public void setChromosome(String param)
  {
    this.chromosome = param;
  }


  public String getCytogeneticMap()
  {
     return this.cytogeneticMap;
  }
  public void setCytogeneticMap(String param)
  {
    this.cytogeneticMap = param;
  }


  public String getEc()
  {
     return this.ec;
  }
  public void setEc(String param)
  {
    this.ec = param;
  }


  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public String getGeneSymbol()
  {
     return this.geneSymbol;
  }
  public void setGeneSymbol(String param)
  {
    this.geneSymbol = param;
  }


  public String getGeneTitle()
  {
     return this.geneTitle;
  }
  public void setGeneTitle(String param)
  {
    this.geneTitle = param;
  }


  public String getGenomeVersion()
  {
     return this.genomeVersion;
  }
  public void setGenomeVersion(String param)
  {
    this.genomeVersion = param;
  }


  public Long getKbEnd()
  {
     return this.kbEnd;
  }
  public void setKbEnd(Long param)
  {
    this.kbEnd = param;
  }


  public Long getKbStart()
  {
     return this.kbStart;
  }
  public void setKbStart(Long param)
  {
    this.kbStart = param;
  }


  public String getLlId()
  {
     return this.llId;
  }
  public void setLlId(String param)
  {
    this.llId = param;
  }


  public String getOminId()
  {
     return this.ominId;
  }
  public void setOminId(String param)
  {
    this.ominId = param;
  }


  public String getUnigeneId()
  {
     return this.unigeneId;
  }
  public void setUnigeneId(String param)
  {
    this.unigeneId = param;
  }


  public java.util.Vector getCollRefseqProteinId()
  {
     return this.collRefseqProteinId;
  }
  public void setCollRefseqProteinId(java.util.Vector param)
  {
    this.collRefseqProteinId = param;
  }


  public java.util.Vector getCollGeneOntology()
  {
     return this.collGeneOntology;
  }
  public void setCollGeneOntology(java.util.Vector param)
  {
    this.collGeneOntology = param;
  }


  public java.util.Vector getCollGeneClone()
  {
     return this.collGeneClone;
  }
  public void setCollGeneClone(java.util.Vector param)
  {
    this.collGeneClone = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollSwissprot()
  {
     return this.collSwissprot;
  }
  public void setCollSwissprot(java.util.Vector param)
  {
    this.collSwissprot = param;
  }


  public java.util.Vector getCollRefseqMrnaId()
  {
     return this.collRefseqMrnaId;
  }
  public void setCollRefseqMrnaId(java.util.Vector param)
  {
    this.collRefseqMrnaId = param;
  }


  public java.util.Vector getCollDifferentialExpressionGfact()
  {
     return this.collDifferentialExpressionGfact;
  }
  public void setCollDifferentialExpressionGfact(java.util.Vector param)
  {
    this.collDifferentialExpressionGfact = param;
  }


  public java.util.Vector getCollGeneProbeset()
  {
     return this.collGeneProbeset;
  }
  public void setCollGeneProbeset(java.util.Vector param)
  {
    this.collGeneProbeset = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


  public java.util.Vector getCollProteinFamily()
  {
     return this.collProteinFamily;
  }
  public void setCollProteinFamily(java.util.Vector param)
  {
    this.collProteinFamily = param;
  }


  public java.util.Vector getCollGenePathway()
  {
     return this.collGenePathway;
  }
  public void setCollGenePathway(java.util.Vector param)
  {
    this.collGenePathway = param;
  }


}

