
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class GeneClone
{
  private Long cloneId;

  private String cloneType;

  private Long geneId;

  private String geneSymbol;

  private gov.nih.nci.nautilus.data.CloneDim aCloneDim;

  private gov.nih.nci.nautilus.data.GeneDimOld aGeneDimOld;

  public Long getCloneId()
  {
     return this.cloneId;
  }
  public void setCloneId(Long param)
  {
    this.cloneId = param;
  }


  public String getCloneType()
  {
     return this.cloneType;
  }
  public void setCloneType(String param)
  {
    this.cloneType = param;
  }


  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public String getGeneSymbol()
  {
     return this.geneSymbol;
  }
  public void setGeneSymbol(String param)
  {
    this.geneSymbol = param;
  }


  public gov.nih.nci.nautilus.data.CloneDim getACloneDim()
  {
     return this.aCloneDim;
  }
  public void setACloneDim(gov.nih.nci.nautilus.data.CloneDim param)
  {
    this.aCloneDim = param;
  }


  public gov.nih.nci.nautilus.data.GeneDimOld getAGeneDimOld()
  {
     return this.aGeneDimOld;
  }
  public void setAGeneDimOld(gov.nih.nci.nautilus.data.GeneDimOld param)
  {
    this.aGeneDimOld = param;
  }


}

