
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class GenoAbnType
{
  private String genoAbnType;

  private String genoAbnTypeDesc;

  public String getGenoAbnType()
  {
     return this.genoAbnType;
  }
  public void setGenoAbnType(String param)
  {
    this.genoAbnType = param;
  }


  public String getGenoAbnTypeDesc()
  {
     return this.genoAbnTypeDesc;
  }
  public void setGenoAbnTypeDesc(String param)
  {
    this.genoAbnTypeDesc = param;
  }


}

