
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class InstitutionDim
{
  private String institutionDesc;

  private Long institutionId;

  private String institutionName;

  private java.util.Vector collDifferentialExpressionSfact;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collDifferentialExpressionGfact;

  public String getInstitutionDesc()
  {
     return this.institutionDesc;
  }
  public void setInstitutionDesc(String param)
  {
    this.institutionDesc = param;
  }


  public Long getInstitutionId()
  {
     return this.institutionId;
  }
  public void setInstitutionId(Long param)
  {
    this.institutionId = param;
  }


  public String getInstitutionName()
  {
     return this.institutionName;
  }
  public void setInstitutionName(String param)
  {
    this.institutionName = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionGfact()
  {
     return this.collDifferentialExpressionGfact;
  }
  public void setCollDifferentialExpressionGfact(java.util.Vector param)
  {
    this.collDifferentialExpressionGfact = param;
  }


}

