
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class LlSnp
{
  private String llId;

  private String probesetName;

  private Long snpProbesetId;

  public String getLlId()
  {
     return this.llId;
  }
  public void setLlId(String param)
  {
    this.llId = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public Long getSnpProbesetId()
  {
     return this.snpProbesetId;
  }
  public void setSnpProbesetId(Long param)
  {
    this.snpProbesetId = param;
  }


}

