
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class LossGainCode
{
  private Long geneId;

  private String lossGain;

  private String lossGainDesc;

  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public String getLossGain()
  {
     return this.lossGain;
  }
  public void setLossGain(String param)
  {
    this.lossGain = param;
  }


  public String getLossGainDesc()
  {
     return this.lossGainDesc;
  }
  public void setLossGainDesc(String param)
  {
    this.lossGainDesc = param;
  }


}

