
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class PathwayStg
{
  private String pathwayName;

  private String probesetName;

  public String getPathwayName()
  {
     return this.pathwayName;
  }
  public void setPathwayName(String param)
  {
    this.pathwayName = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


}

