
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class Patient
{
  private Long age;

  private Long patientDid;

  private Long populationTypeId;

  private Long survivalLength;

  private gov.nih.nci.nautilus.data.PopulationType aPopulationType;

  private java.util.Vector collBiospecimenDim;

  public Long getAge()
  {
     return this.age;
  }
  public void setAge(Long param)
  {
    this.age = param;
  }


  public Long getPatientDid()
  {
     return this.patientDid;
  }
  public void setPatientDid(Long param)
  {
    this.patientDid = param;
  }


  public Long getPopulationTypeId()
  {
     return this.populationTypeId;
  }
  public void setPopulationTypeId(Long param)
  {
    this.populationTypeId = param;
  }


  public Long getSurvivalLength()
  {
     return this.survivalLength;
  }
  public void setSurvivalLength(Long param)
  {
    this.survivalLength = param;
  }


  public gov.nih.nci.nautilus.data.PopulationType getAPopulationType()
  {
     return this.aPopulationType;
  }
  public void setAPopulationType(gov.nih.nci.nautilus.data.PopulationType param)
  {
    this.aPopulationType = param;
  }


  public java.util.Vector getCollBiospecimenDim()
  {
     return this.collBiospecimenDim;
  }
  public void setCollBiospecimenDim(java.util.Vector param)
  {
    this.collBiospecimenDim = param;
  }


}

