
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class ProbesetDim
{
    public final static String PROBESET_ID = "probesetId";
    public final static String PROBESET_NAME = "probesetName";
    public final static String GENE_SYMBOL = "geneSymbol";
    public final static String CYTOBAND = "cytoband";
    public final static String ACCESSION_NUMBER = "accessionNumber";
    private Long probesetId;
 private String probesetName;

    public String getChromosome() {
        return chromosome;
    }

    public void setChromosome(String chromosome) {
        this.chromosome = chromosome;
    }

    private String chromosome;

    public String getArrayName() {
        return arrayName;
    }

    public void setArrayName(String arrayName) {
        this.arrayName = arrayName;
    }

    private String arrayName;

    public String getChormosome() {
        return chormosome;
    }

    public void setChormosome(String chormosome) {
        this.chormosome = chormosome;
    }

    private String chormosome;

    public Long getProbesetId() {
        return probesetId;
    }

    public void setProbesetId(Long probesetId) {
        this.probesetId = probesetId;
    }

    public String getProbesetName() {
        return probesetName;
    }

    public void setProbesetName(String probesetName) {
        this.probesetName = probesetName;
    }

  private String alignments;

    public String getCytoband() {
        return cytoband;
    }

    public void setCytoband(String cytoband) {
        this.cytoband = cytoband;
    }

    private String cytoband;

    public String getAccessionNumber() {
        return accessionNumber;
    }

    public void setAccessionNumber(String accessionNumber) {
        this.accessionNumber = accessionNumber;
    }

    private String accessionNumber;
  private String ec;

  private Long geneId;

  private String geneSymbol;

  private String geneTitle;

  private String genomeVersion;

  private Long kbEnd;

  private Long kbStart;

  private String llId;

  private String ominId;

  private String unigeneId;

    public ProbesetDim() {
    }

  public String getAlignments()
  {
     return this.alignments;
  }
  public void setAlignments(String param)
  {
    this.alignments = param;
  }





  public String getEc()
  {
     return this.ec;
  }
  public void setEc(String param)
  {
    this.ec = param;
  }


  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public String getGeneSymbol()
  {
     return this.geneSymbol;
  }
  public void setGeneSymbol(String param)
  {
    this.geneSymbol = param;
  }


  public String getGeneTitle()
  {
     return this.geneTitle;
  }
  public void setGeneTitle(String param)
  {
    this.geneTitle = param;
  }


  public String getGenomeVersion()
  {
     return this.genomeVersion;
  }
  public void setGenomeVersion(String param)
  {
    this.genomeVersion = param;
  }


  public Long getKbEnd()
  {
     return this.kbEnd;
  }
  public void setKbEnd(Long param)
  {
    this.kbEnd = param;
  }


  public Long getKbStart()
  {
     return this.kbStart;
  }
  public void setKbStart(Long param)
  {
    this.kbStart = param;
  }


  public String getLlId()
  {
     return this.llId;
  }
  public void setLlId(String param)
  {
    this.llId = param;
  }


  public String getOminId()
  {
     return this.ominId;
  }
  public void setOminId(String param)
  {
    this.ominId = param;
  }


  public String getUnigeneId()
  {
     return this.unigeneId;
  }
  public void setUnigeneId(String param)
  {
    this.unigeneId = param;
  }


}

