
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class RefseqMrnaIdStg
{
  private String ensm;

  private String probesetName;

  private String refseqMrnaId;

  public String getEnsm()
  {
     return this.ensm;
  }
  public void setEnsm(String param)
  {
    this.ensm = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public String getRefseqMrnaId()
  {
     return this.refseqMrnaId;
  }
  public void setRefseqMrnaId(String param)
  {
    this.refseqMrnaId = param;
  }


}

