
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class RefseqMrnaId
{
  private Long geneId;

  private String refseqMrnaId;

  private gov.nih.nci.nautilus.data.GeneDimOld aGeneDimOld;

  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public String getRefseqMrnaId()
  {
     return this.refseqMrnaId;
  }
  public void setRefseqMrnaId(String param)
  {
    this.refseqMrnaId = param;
  }


  public gov.nih.nci.nautilus.data.GeneDimOld getAGeneDimOld()
  {
     return this.aGeneDimOld;
  }
  public void setAGeneDimOld(gov.nih.nci.nautilus.data.GeneDimOld param)
  {
    this.aGeneDimOld = param;
  }


}

