
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;


public class ReporterAll
{
  public final static String CLONE_ID = "cloneId";
  public final static String PROBESET_ID = "probesetId";
  public final static String GENE_SYMBOL = "geneSymbol";
  public final static String CYTOBAND = "cytoband";

  private String accessionNumber;

  private String alignments;

  private String chromosome;

  private Long cloneId;

  private String cloneLocation;

  private String cloneType;

  private String cytoband;

  private String ec;

  private String geneSymbol;

  private String geneTitle;

  private String genomeVersion;

  private Long kbEnd;

  private Long kbStart;

  private String library;

  private String llId;

  private String ominId;

  private Long probesetId;

  private String reporterDesc;

  private String reporterName;

  private String unigeneId;

  private Long unigeneLibrary;

  private Long utr;

  public String getAccessionNumber()
  {
     return this.accessionNumber;
  }
  public void setAccessionNumber(String param)
  {
    this.accessionNumber = param;
  }


  public String getAlignments()
  {
     return this.alignments;
  }
  public void setAlignments(String param)
  {
    this.alignments = param;
  }


  public String getChromosome()
  {
     return this.chromosome;
  }
  public void setChromosome(String param)
  {
    this.chromosome = param;
  }


  public Long getCloneId()
  {
     return this.cloneId;
  }
  public void setCloneId(Long param)
  {
    this.cloneId = param;
  }


  public String getCloneLocation()
  {
     return this.cloneLocation;
  }
  public void setCloneLocation(String param)
  {
    this.cloneLocation = param;
  }


  public String getCloneType()
  {
     return this.cloneType;
  }
  public void setCloneType(String param)
  {
    this.cloneType = param;
  }


  public String getCytoband()
  {
     return this.cytoband;
  }
  public void setCytoband(String param)
  {
    this.cytoband = param;
  }


  public String getEc()
  {
     return this.ec;
  }
  public void setEc(String param)
  {
    this.ec = param;
  }


  public String getGeneSymbol()
  {
     return this.geneSymbol;
  }
  public void setGeneSymbol(String param)
  {
    this.geneSymbol = param;
  }


  public String getGeneTitle()
  {
     return this.geneTitle;
  }
  public void setGeneTitle(String param)
  {
    this.geneTitle = param;
  }


  public String getGenomeVersion()
  {
     return this.genomeVersion;
  }
  public void setGenomeVersion(String param)
  {
    this.genomeVersion = param;
  }


  public Long getKbEnd()
  {
     return this.kbEnd;
  }
  public void setKbEnd(Long param)
  {
    this.kbEnd = param;
  }


  public Long getKbStart()
  {
     return this.kbStart;
  }
  public void setKbStart(Long param)
  {
    this.kbStart = param;
  }


  public String getLibrary()
  {
     return this.library;
  }
  public void setLibrary(String param)
  {
    this.library = param;
  }


  public String getLlId()
  {
     return this.llId;
  }
  public void setLlId(String param)
  {
    this.llId = param;
  }


  public String getOminId()
  {
     return this.ominId;
  }
  public void setOminId(String param)
  {
    this.ominId = param;
  }


  public Long getProbesetId()
  {
     return this.probesetId;
  }
  public void setProbesetId(Long param)
  {
    this.probesetId = param;
  }


  public String getReporterDesc()
  {
     return this.reporterDesc;
  }
  public void setReporterDesc(String param)
  {
    this.reporterDesc = param;
  }


  public String getReporterName()
  {
     return this.reporterName;
  }
  public void setReporterName(String param)
  {
    this.reporterName = param;
  }


  public String getUnigeneId()
  {
     return this.unigeneId;
  }
  public void setUnigeneId(String param)
  {
    this.unigeneId = param;
  }


  public Long getUnigeneLibrary()
  {
     return this.unigeneLibrary;
  }
  public void setUnigeneLibrary(Long param)
  {
    this.unigeneLibrary = param;
  }


  public Long getUtr()
  {
     return this.utr;
  }
  public void setUtr(Long param)
  {
    this.utr = param;
  }


}

