
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class SNPProbesetDim
{
  public final static String PHYSICAL_POSITION = "physicalPosition";
  public final static String SNP_PROBESET_ID = "snpProbesetId";
  public final static String CHROMOSOME = "chr";


  private String alleleFrequencyAf;

  private String alleleFrequencyAs;

  private String alleleFrequencyCa;

  private String arrayName;

  private String chr;

  private String cytoband;

  private String dbSnpId;

  private Long physicalPosition;

  private String probesetName;

  private Long snpProbesetId;



  public String getAlleleFrequencyAf()
  {
     return this.alleleFrequencyAf;
  }
  public void setAlleleFrequencyAf(String param)
  {
    this.alleleFrequencyAf = param;
  }


  public String getAlleleFrequencyAs()
  {
     return this.alleleFrequencyAs;
  }
  public void setAlleleFrequencyAs(String param)
  {
    this.alleleFrequencyAs = param;
  }


  public String getAlleleFrequencyCa()
  {
     return this.alleleFrequencyCa;
  }
  public void setAlleleFrequencyCa(String param)
  {
    this.alleleFrequencyCa = param;
  }


  public String getArrayName()
  {
     return this.arrayName;
  }
  public void setArrayName(String param)
  {
    this.arrayName = param;
  }


  public String getChr()
  {
     return this.chr;
  }
  public void setChr(String param)
  {
    this.chr = param;
  }


  public String getCytoband()
  {
     return this.cytoband;
  }
  public void setCytoband(String param)
  {
    this.cytoband = param;
  }


  public String getDbSnpId()
  {
     return this.dbSnpId;
  }
  public void setDbSnpId(String param)
  {
    this.dbSnpId = param;
  }


  public Long getPhysicalPosition()
  {
     return this.physicalPosition;
  }
  public void setPhysicalPosition(Long param)
  {
    this.physicalPosition = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public Long getSnpProbesetId()
  {
     return this.snpProbesetId;
  }
  public void setSnpProbesetId(Long param)
  {
    this.snpProbesetId = param;
  }




}

