
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class SwissprotStg
{
  private String ensm;

  private String probesetName;

  private String swissprot;

  public String getEnsm()
  {
     return this.ensm;
  }
  public void setEnsm(String param)
  {
    this.ensm = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public String getSwissprot()
  {
     return this.swissprot;
  }
  public void setSwissprot(String param)
  {
    this.swissprot = param;
  }


}

