
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.data;

public class TreatmentHistory
{
  private Long treatmentHistoryId;

  private String treatmentType;

  private String treatmentTypeDesc;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collDifferentialExpressionSfact;

  public Long getTreatmentHistoryId()
  {
     return this.treatmentHistoryId;
  }
  public void setTreatmentHistoryId(Long param)
  {
    this.treatmentHistoryId = param;
  }


  public String getTreatmentType()
  {
     return this.treatmentType;
  }
  public void setTreatmentType(String param)
  {
    this.treatmentType = param;
  }


  public String getTreatmentTypeDesc()
  {
     return this.treatmentTypeDesc;
  }
  public void setTreatmentTypeDesc(String param)
  {
    this.treatmentTypeDesc = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


}

