
// Generated by OJB SchemeGenerator

package gov.nih.nci.nautilus.queryprocessing.cgh;

import gov.nih.nci.nautilus.resultset.ResultSet;

import java.util.ArrayList;

public class CopyNumber implements ResultSet
{
  private String ageGroup;
  private Long biospecimenId;
  private Double channelRatio;
  private Double copyNumber;
  private Double copynoPval;
  private String sampleId;
  private String cytoband;
  private String diseaseType;
  private String genderCode;
  private Double loh;
  private String lossGain;
  private Long snpProbesetId;
  private String snpProbesetName ;
  private String survivalLengthRange;
  private Long timecourseId;
  private Annotation annotations;

   public static class Annotation {
        ArrayList geneSymbols;
        ArrayList accessions;
        Long snpProbesetID;

       public Annotation(ArrayList geneSymbols, ArrayList accessions, Long snpProbesetID) {
           this.geneSymbols = geneSymbols;
           this.accessions = accessions;
           this.snpProbesetID = snpProbesetID;
       }
   }

    public Annotation getAnnotations() {
        return annotations;
    }

    public void setAnnotations(Annotation annotations) {
        this.annotations = annotations;
    }
    public String getAgeGroup() {
        return ageGroup;
    }

    public void setAgeGroup(String ageGroup) {
        this.ageGroup = ageGroup;
    }

    public Long getBiospecimenId() {
        return biospecimenId;
    }

    public void setBiospecimenId(Long biospecimenId) {
        this.biospecimenId = biospecimenId;
    }

    public Double getChannelRatio() {
        return channelRatio;
    }

    public void setChannelRatio(Double channelRatio) {
        this.channelRatio = channelRatio;
    }

    public Double getCopyNumber() {
        return copyNumber;
    }

    public void setCopyNumber(Double copyNumber) {
        this.copyNumber = copyNumber;
    }

    public Double getCopynoPval() {
        return copynoPval;
    }

    public void setCopynoPval(Double copynoPval) {
        this.copynoPval = copynoPval;
    }

    public String getSampleId() {
        return sampleId;
    }

    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }

    public String getCytoband() {
        return cytoband;
    }

    public void setCytoband(String cytoband) {
        this.cytoband = cytoband;
    }

    public String getDiseaseType() {
        return diseaseType;
    }

    public void setDiseaseType(String diseaseType) {
        this.diseaseType = diseaseType;
    }

    public String getGenderCode() {
        return genderCode;
    }

    public void setGenderCode(String genderCode) {
        this.genderCode = genderCode;
    }

    public Double getLoh() {
        return loh;
    }

    public void setLoh(Double loh) {
        this.loh = loh;
    }

    public String getLossGain() {
        return lossGain;
    }

    public void setLossGain(String lossGain) {
        this.lossGain = lossGain;
    }

    public Long getSnpProbesetId() {
        return snpProbesetId;
    }

    public void setSnpProbesetId(Long snpProbesetId) {
        this.snpProbesetId = snpProbesetId;
    }

    public String getSnpProbesetName() {
        return snpProbesetName;
    }

    public void setSnpProbesetName(String snpProbesetName) {
        this.snpProbesetName = snpProbesetName;
    }

    public String getSurvivalLengthRange() {
        return survivalLengthRange;
    }

    public void setSurvivalLengthRange(String survivalLengthRange) {
        this.survivalLengthRange = survivalLengthRange;
    }

    public Long getTimecourseId() {
        return timecourseId;
    }

    public void setTimecourseId(Long timecourseId) {
        this.timecourseId = timecourseId;
    }
}

