
DROP TABLE ACC_CHR_POSITION CASCADE CONSTRAINTS;

CREATE TABLE ACC_CHR_POSITION
(
  ACCESSION_NUM  VARCHAR2(40),
  CHROMOSOME     VARCHAR2(40),
  ACC_START      VARCHAR2(40),
  ACC_END        VARCHAR2(40)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE AGENT_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE AGENT_DIM CASCADE CONSTRAINTS;

CREATE TABLE AGENT_DIM
(
  AGENT_ID    NUMBER                            NOT NULL,
  AGENT_NAME  VARCHAR2(120),
  AGENT_TYPE  VARCHAR2(100),
  NSC_NUMBER  NUMBER,
  EVS_ID      VARCHAR2(50)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE AGE_GROUP_DX_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE AGE_GROUP_DX_DIM CASCADE CONSTRAINTS;

CREATE TABLE AGE_GROUP_DX_DIM
(
  AGE_GROUP_DESC  VARCHAR2(50)                  NOT NULL,
  AGE_GROUP       VARCHAR2(20)                  NOT NULL,
  LOWERBOUND      NUMBER(3),
  UPPERBOUND      NUMBER(3)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE ARRAY_GENO_ABN_FACT DROP PRIMARY KEY CASCADE;
DROP TABLE ARRAY_GENO_ABN_FACT CASCADE CONSTRAINTS;

CREATE TABLE ARRAY_GENO_ABN_FACT
(
  CHROMOSOME             VARCHAR2(20),
  CHANNEL_RATIO          FLOAT(126),
  LOSS_GAIN              VARCHAR2(20),
  DATASET_ID             NUMBER,
  INSTITUTION_ID         NUMBER,
  AGA_ID                 NUMBER                 NOT NULL,
  CYTOBAND               VARCHAR2(50),
  DISEASE_TYPE_ID        NUMBER                 NOT NULL,
  COPYNO_PVAL            FLOAT(126),
  GENDER_CODE            VARCHAR2(1),
  COPY_NUMBER            FLOAT(126),
  EXP_PLATFORM_ID        NUMBER,
  TIMECOURSE_ID          NUMBER,
  BIOSPECIMEN_ID         NUMBER,
  SURVIVAL_LENGTH_RANGE  VARCHAR2(15),
  AGE_GROUP              VARCHAR2(20),
  TREATMENT_HISTORY_ID   NUMBER,
  AGENT_ID               NUMBER,
  DISEASE_HISTORY_ID     NUMBER,
  SNP_PROBESET_ID        NUMBER,
  SNP_PROBESET_NAME      VARCHAR2(200),
  LOH                    FLOAT(126),
  PHYSICAL_POSITION      NUMBER,
  DISEASE_TYPE           VARCHAR2(100),
  SAMPLE_ID              VARCHAR2(20)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          655544K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE BIOSPECIMEN_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE BIOSPECIMEN_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIOSPECIMEN_DIM
(
  SAMPLE_ID       VARCHAR2(50)                  NOT NULL,
  SPECIMEN_NAME   VARCHAR2(100),
  SPECIMEN_DESC   VARCHAR2(255),
  BIOSPECIMEN_ID  NUMBER                        NOT NULL,
  PATIENT_DID     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE CLONE_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE CLONE_DIM CASCADE CONSTRAINTS;

CREATE TABLE CLONE_DIM
(
  CLONE_ID         NUMBER                       NOT NULL,
  CLONE_NAME       VARCHAR2(200),
  CLONE_DESC       VARCHAR2(4000),
  UTR              NUMBER(1),
  UNIGENE_LIBRARY  VARCHAR2(50),
  UNIGENE_ID       VARCHAR2(50),
  CLONE_TYPE       VARCHAR2(20),
  CYTOBAND         VARCHAR2(50),
  CHROMOSOME       VARCHAR2(20)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE CYTOBAND_POSITION DROP PRIMARY KEY CASCADE;
DROP TABLE CYTOBAND_POSITION CASCADE CONSTRAINTS;

CREATE TABLE CYTOBAND_POSITION
(
  CHROMOSOME            VARCHAR2(10)            NOT NULL,
  CYTOBAND              VARCHAR2(50)            NOT NULL,
  ORGANISM              VARCHAR2(200),
  CB_START              NUMBER,
  CB_END_POS            NUMBER,
  CYTOBAND_POSITION_ID  NUMBER                  NOT NULL,
  CHR_CYTOBAND          VARCHAR2(60)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE DETECTION_TYPE DROP PRIMARY KEY CASCADE;
DROP TABLE DETECTION_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DETECTION_TYPE
(
  DETECTION_TYPE_ID    NUMBER                   NOT NULL,
  DETECTION_TYPE       VARCHAR2(100),
  DETECTION_TYPE_DESC  VARCHAR2(255)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE DIFFERENTIAL_EXPRESSION_GFACT DROP PRIMARY KEY CASCADE;
DROP TABLE DIFFERENTIAL_EXPRESSION_GFACT CASCADE CONSTRAINTS;

CREATE TABLE DIFFERENTIAL_EXPRESSION_GFACT
(
  DEG_ID            NUMBER                      NOT NULL,
  EXPRESSION_RATIO  FLOAT(126),
  NORMAL_INTENSITY  FLOAT(126),
  RATIO_PVAL        FLOAT(126),
  DISEASE_TYPE_ID   NUMBER,
  PROBESET_ID       NUMBER,
  CLONE_ID          NUMBER,
  DATASET_ID        NUMBER,
  INSTITUTION_ID    NUMBER,
  EXP_PLATFORM_ID   NUMBER,
  PROBESET_NAME     VARCHAR2(200),
  CLONE_NAME        VARCHAR2(200),
  TIMECOURSE_ID     NUMBER,
  GENE_SYMBOL       VARCHAR2(50),
  SAMPLE_INTENSITY  FLOAT(126),
  DISEASE_TYPE      VARCHAR2(100)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          38440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT DROP PRIMARY KEY CASCADE;
DROP TABLE DIFFERENTIAL_EXPRESSION_SFACT CASCADE CONSTRAINTS;

CREATE TABLE DIFFERENTIAL_EXPRESSION_SFACT
(
  DES_ID                NUMBER                  NOT NULL,
  PROBESET_ID           NUMBER,
  CLONE_ID              NUMBER,
  EXPRESSION_RATIO      FLOAT(126),
  SAMPLE_INTENSITY      FLOAT(126),
  NORMAL_INTENSITY      FLOAT(126),
  GENE_SYMBOL           VARCHAR2(50),
  DATASET_ID            NUMBER,
  EXP_PLATFORM_ID       NUMBER,
  INSTITUTION_ID        NUMBER,
  BIOSPECIMEN_ID        NUMBER                  NOT NULL,
  DISEASE_TYPE_ID       NUMBER                  NOT NULL,
  GENDER_CODE           VARCHAR2(1),
  AGE_GROUP             VARCHAR2(20),
  SURVIV_LENGTH_RANGE   VARCHAR2(15),
  TREATMENT_HISTORY_ID  NUMBER,
  AGENT_ID              NUMBER,
  DISEASE_HISTORY_ID    NUMBER,
  TIMECOURSE_ID         NUMBER,
  CLONE_NAME            VARCHAR2(200),
  PROBESET_NAME         VARCHAR2(200),
  CYTOBAND              VARCHAR2(500),
  DISEASE_TYPE          VARCHAR2(100),
  SAMPLE_ID             VARCHAR2(20)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          655640K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE DISEASE_GRADE CASCADE CONSTRAINTS;

CREATE TABLE DISEASE_GRADE
(
  GRADE_ID    NUMBER,
  GRADE       VARCHAR2(5),
  GRADE_DESC  VARCHAR2(20)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE DISEASE_HISTORY_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE DISEASE_HISTORY_DIM CASCADE CONSTRAINTS;

CREATE TABLE DISEASE_HISTORY_DIM
(
  DISEASE_HISTORY_ID      NUMBER                NOT NULL,
  OCCURRENCE_STATUS       VARCHAR2(10),
  OCCURRENCE_STATUS_DESC  VARCHAR2(50)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE DISEASE_TYPE_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE DISEASE_TYPE_DIM CASCADE CONSTRAINTS;

CREATE TABLE DISEASE_TYPE_DIM
(
  DISEASE_TYPE_ID  NUMBER                       NOT NULL,
  DISEASE_TYPE     VARCHAR2(100)                NOT NULL,
  DISEASE_DESC     VARCHAR2(200)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE EXP_PLATFORM_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE EXP_PLATFORM_DIM CASCADE CONSTRAINTS;

CREATE TABLE EXP_PLATFORM_DIM
(
  EXP_PLATFORM_ID    NUMBER                     NOT NULL,
  EXP_PLATFORM_NAME  VARCHAR2(50),
  EXP_PLATFORM_DESC  VARCHAR2(200)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE GENDER_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE GENDER_DIM CASCADE CONSTRAINTS;

CREATE TABLE GENDER_DIM
(
  GENDER_CODE  VARCHAR2(1)                      NOT NULL,
  GENDER_DESC  VARCHAR2(30)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE GENE_CLONE DROP PRIMARY KEY CASCADE;
DROP TABLE GENE_CLONE CASCADE CONSTRAINTS;

CREATE TABLE GENE_CLONE
(
  GENE_CLONE_ID     NUMBER                      NOT NULL,
  UNIGENE_LIBRARY   VARCHAR2(50),
  GENE_TITLE        VARCHAR2(2000),
  UNIGENE_ID        VARCHAR2(50),
  LL_ID             VARCHAR2(50),
  EC                VARCHAR2(100),
  ACCESSION_NUMBER  VARCHAR2(100),
  ACC_START         NUMBER,
  ACC_END           NUMBER,
  CLONE_ID          NUMBER,
  GENE_SYMBOL       VARCHAR2(50),
  IMAGE_ID          VARCHAR2(50),
  OMIM_ID           VARCHAR2(50),
  CHROMOSOME        VARCHAR2(20),
  UP_GENE_SYMBOL    VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_LL_ACC_SNP CASCADE CONSTRAINTS;

CREATE TABLE GENE_LL_ACC_SNP
(
  GENE_SYMBOL        VARCHAR2(100),
  ACCESSION          VARCHAR2(50),
  LL_ID              VARCHAR2(50),
  CHROMOSOME         VARCHAR2(100),
  UP_GENE_SYMBOL     VARCHAR2(50),
  SNP_PROBESET_ID    NUMBER,
  PROBESET_NAME      VARCHAR2(200),
  PHYSICAL_POSITION  NUMBER
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_ONTOLOGY CASCADE CONSTRAINTS;

CREATE TABLE GENE_ONTOLOGY
(
  GO_NAME         VARCHAR2(200),
  GENE_SYMBOL     VARCHAR2(100),
  GO_DESC         VARCHAR2(4000),
  GO_ID           VARCHAR2(15),
  UP_GENE_SYMBOL  VARCHAR2(50)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_PATHWAY CASCADE CONSTRAINTS;

CREATE TABLE GENE_PATHWAY
(
  PATHWAY_NAME    VARCHAR2(200),
  DATA_SOURCE     VARCHAR2(30),
  GENE_SYMBOL     VARCHAR2(50),
  PATHWAY_DESC    VARCHAR2(4000),
  UP_GENE_SYMBOL  VARCHAR2(50)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_SNP CASCADE CONSTRAINTS;

CREATE TABLE GENE_SNP
(
  GENE_SYMBOL      VARCHAR2(100),
  UP_GENE_SYMBOL   VARCHAR2(50),
  SNP_PROBESET_ID  NUMBER,
  PROBESET_NAME    VARCHAR2(200)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE GENO_ABN_TYPE DROP PRIMARY KEY CASCADE;
DROP TABLE GENO_ABN_TYPE CASCADE CONSTRAINTS;

CREATE TABLE GENO_ABN_TYPE
(
  GENO_ABN_TYPE_DESC  VARCHAR2(200),
  GENO_ABN_TYPE       VARCHAR2(20)              NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE INSTITUTION_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE INSTITUTION_DIM CASCADE CONSTRAINTS;

CREATE TABLE INSTITUTION_DIM
(
  INSTITUTION_ID    NUMBER                      NOT NULL,
  INSTITUTION_NAME  VARCHAR2(100),
  INSTITUTION_DESC  VARCHAR2(200)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE LL_SNP CASCADE CONSTRAINTS;

CREATE TABLE LL_SNP
(
  LL_ID            VARCHAR2(50),
  SNP_PROBESET_ID  NUMBER,
  PROBESET_NAME    VARCHAR2(200)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE LOSS_GAIN_CODE DROP PRIMARY KEY CASCADE;
DROP TABLE LOSS_GAIN_CODE CASCADE CONSTRAINTS;

CREATE TABLE LOSS_GAIN_CODE
(
  LOSS_GAIN_DESC  VARCHAR2(100),
  LOSS_GAIN       VARCHAR2(20)                  NOT NULL,
  GENE_ID         NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE MLOG$_BIOSPECIMEN_DIM CASCADE CONSTRAINTS;

CREATE TABLE MLOG$_BIOSPECIMEN_DIM
(
  BIOSPECIMEN_ID   NUMBER,
  M_ROW$$          VARCHAR2(255),
  SNAPTIME$$       DATE,
  DMLTYPE$$        VARCHAR2(1),
  OLD_NEW$$        VARCHAR2(1),
  CHANGE_VECTOR$$  RAW(255)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    60
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON TABLE MLOG$_BIOSPECIMEN_DIM IS 'snapshot log for master table NAUTILUSDEV.BIOSPECIMEN_DIM';


DROP TABLE MLOG$_PATIENT CASCADE CONSTRAINTS;

CREATE TABLE MLOG$_PATIENT
(
  PATIENT_DID      NUMBER,
  M_ROW$$          VARCHAR2(255),
  SNAPTIME$$       DATE,
  DMLTYPE$$        VARCHAR2(1),
  OLD_NEW$$        VARCHAR2(1),
  CHANGE_VECTOR$$  RAW(255)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    60
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON TABLE MLOG$_PATIENT IS 'snapshot log for master table NAUTILUSDEV.PATIENT';


ALTER TABLE PATIENT DROP PRIMARY KEY CASCADE;
DROP TABLE PATIENT CASCADE CONSTRAINTS;

CREATE TABLE PATIENT
(
  PATIENT_DID         NUMBER                    NOT NULL,
  POPULATION_TYPE_ID  NUMBER,
  AGE                 NUMBER,
  SURVIVAL_LENGTH     NUMBER,
  CENSORING_STATUS    VARCHAR2(5),
  GENDER              VARCHAR2(5)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE PATIENT_DATA CASCADE CONSTRAINTS;

CREATE TABLE PATIENT_DATA
(
  SAMPLE_ID           VARCHAR2(50)              NOT NULL,
  BIOSPECIMEN_ID      NUMBER                    NOT NULL,
  PATIENT_DID         NUMBER,
  POPULATION_TYPE_ID  NUMBER,
  AGE                 NUMBER,
  SURVIVAL_LENGTH     NUMBER,
  GENDER              VARCHAR2(5),
  CENSORING_STATUS    VARCHAR2(5)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON TABLE PATIENT_DATA IS 'snapshot table for snapshot NAUTILUSDEV.PATIENT_DATA';


ALTER TABLE POPULATION_TYPE DROP PRIMARY KEY CASCADE;
DROP TABLE POPULATION_TYPE CASCADE CONSTRAINTS;

CREATE TABLE POPULATION_TYPE
(
  POPULATION_TYPE_ID    NUMBER                  NOT NULL,
  POPULATION_TYPE_NAME  VARCHAR2(50),
  POPULATION_TYPE_DESC  VARCHAR2(200)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE PROBESET_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE PROBESET_DIM CASCADE CONSTRAINTS;

CREATE TABLE PROBESET_DIM
(
  PROBESET_ID       NUMBER                      NOT NULL,
  PROBESET_NAME     VARCHAR2(200)               NOT NULL,
  ARRAY_NAME        VARCHAR2(100)               NOT NULL,
  GENE_SYMBOL       VARCHAR2(50),
  GENOME_VERSION    VARCHAR2(100),
  GENE_TITLE        VARCHAR2(2000),
  ALIGNMENTS        VARCHAR2(255),
  LL_ID             VARCHAR2(50),
  UNIGENE_ID        VARCHAR2(50),
  EC                VARCHAR2(100),
  KB_START          NUMBER,
  KB_END            NUMBER,
  CHROMOSOME        VARCHAR2(20),
  CYTOBAND          VARCHAR2(50),
  ACCESSION_NUMBER  VARCHAR2(100),
  OMIM_ID           VARCHAR2(50),
  UP_GENE_SYMBOL    VARCHAR2(50)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          21360K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE PROTEIN_FAMILY CASCADE CONSTRAINTS;

CREATE TABLE PROTEIN_FAMILY
(
  PROTEIN_FAMILY  VARCHAR2(1000),
  PROBESET_ID     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          5M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE REFSEQ_MRNA_ID CASCADE CONSTRAINTS;

CREATE TABLE REFSEQ_MRNA_ID
(
  REFSEQ_MRNA_ID  VARCHAR2(50),
  PROBESET_ID     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE REFSEQ_PROTEIN_ID CASCADE CONSTRAINTS;

CREATE TABLE REFSEQ_PROTEIN_ID
(
  REFSEQ_PROTEIN_ID  NUMBER,
  PROBESET_ID        NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE RUPD$_BIOSPECIMEN_DIM CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE RUPD$_BIOSPECIMEN_DIM
(
  BIOSPECIMEN_ID   NUMBER,
  DMLTYPE$$        VARCHAR2(1),
  SNAPID           INTEGER,
  CHANGE_VECTOR$$  RAW(255)
)
ON COMMIT PRESERVE ROWS;

COMMENT ON TABLE RUPD$_BIOSPECIMEN_DIM IS 'temporary updatable snapshot log';


DROP TABLE RUPD$_PATIENT CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE RUPD$_PATIENT
(
  PATIENT_DID      NUMBER,
  DMLTYPE$$        VARCHAR2(1),
  SNAPID           INTEGER,
  CHANGE_VECTOR$$  RAW(255)
)
ON COMMIT PRESERVE ROWS;

COMMENT ON TABLE RUPD$_PATIENT IS 'temporary updatable snapshot log';


ALTER TABLE SNP_PROBESET_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE SNP_PROBESET_DIM CASCADE CONSTRAINTS;

CREATE TABLE SNP_PROBESET_DIM
(
  ARRAY_NAME           VARCHAR2(50)             NOT NULL,
  PROBESET_NAME        VARCHAR2(200)            NOT NULL,
  SNP_PROBESET_ID      NUMBER                   NOT NULL,
  DB_SNP_ID            VARCHAR2(18),
  PHYSICAL_POSITION    NUMBER,
  CYTOBAND             VARCHAR2(50),
  ALLELE_FREQUENCY_AS  VARCHAR2(100),
  ALLELE_FREQUENCY_AF  VARCHAR2(100),
  ALLELE_FREQUENCY_CA  VARCHAR2(100),
  CHROMOSOME           VARCHAR2(20)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          25624K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE STUDY_DATASET_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE STUDY_DATASET_DIM CASCADE CONSTRAINTS;

CREATE TABLE STUDY_DATASET_DIM
(
  DATASET_ID    NUMBER                          NOT NULL,
  DATASET_NAME  VARCHAR2(100),
  DATASET_DESC  VARCHAR2(255)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE STUDY_TIMECOURSE_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE STUDY_TIMECOURSE_DIM CASCADE CONSTRAINTS;

CREATE TABLE STUDY_TIMECOURSE_DIM
(
  TIMECOURSE_ID    NUMBER                       NOT NULL,
  TIMECOURSE_NAME  VARCHAR2(50),
  TIMECOURSE_DESC  VARCHAR2(200)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE SURVIVAL_LENGTH_RANGE_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE SURVIVAL_LENGTH_RANGE_DIM CASCADE CONSTRAINTS;

CREATE TABLE SURVIVAL_LENGTH_RANGE_DIM
(
  SURVIVAL_LENGTH_RANGE  VARCHAR2(15)           NOT NULL,
  GROUP_DESC             VARCHAR2(100),
  LOWERBOUND             NUMBER(5),
  UPPERBOUND             NUMBER(8)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE SWISSPROT CASCADE CONSTRAINTS;

CREATE TABLE SWISSPROT
(
  SWISSPROT    VARCHAR2(50),
  PROBESET_ID  NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2320K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE TREATMENT_HISTORY_DIM DROP PRIMARY KEY CASCADE;
DROP TABLE TREATMENT_HISTORY_DIM CASCADE CONSTRAINTS;

CREATE TABLE TREATMENT_HISTORY_DIM
(
  TREATMENT_HISTORY_ID  NUMBER                  NOT NULL,
  TREATMENT_TYPE        VARCHAR2(30),
  TREATMENT_TYPE_DESC   VARCHAR2(200)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX ACCNNB_IDX ON PROBESET_DIM
(ACCESSION_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1720K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ACP_ACCNUM_IDX ON ACC_CHR_POSITION
(ACCESSION_NUM)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ACP_CHROMOSOME_IDX ON ACC_CHR_POSITION
(CHROMOSOME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AFAG_DISHIST_BIDX ON ARRAY_GENO_ABN_FACT
(DISEASE_HISTORY_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AGAF_AGEGRP_BIDX ON ARRAY_GENO_ABN_FACT
(AGE_GROUP)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AGAF_CPNO_IDX ON ARRAY_GENO_ABN_FACT
(COPY_NUMBER)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          129520K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AGAF_CPV_IDX ON ARRAY_GENO_ABN_FACT
(COPYNO_PVAL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AGAF_DATASET_BIDX ON ARRAY_GENO_ABN_FACT
(DATASET_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AGAF_DISTYPE_BIDX ON ARRAY_GENO_ABN_FACT
(DISEASE_TYPE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AGAF_EXPPLAT_BIDX ON ARRAY_GENO_ABN_FACT
(EXP_PLATFORM_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AGAF_INST_BIDX ON ARRAY_GENO_ABN_FACT
(INSTITUTION_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AGAF_LOH_IDX ON ARRAY_GENO_ABN_FACT
(LOH)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AGAF_SNPID_IDX ON ARRAY_GENO_ABN_FACT
(SNP_PROBESET_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          129504K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AGAF_SNPNM_IDX ON ARRAY_GENO_ABN_FACT
(SNP_PROBESET_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          194232K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AGAF_SURLEG_BIDX ON ARRAY_GENO_ABN_FACT
(SURVIVAL_LENGTH_RANGE)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AGF_CHROM_IDX ON ARRAY_GENO_ABN_FACT
(CHROMOSOME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AGF_CYTOBAND_IDX ON ARRAY_GENO_ABN_FACT
(CYTOBAND)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          129560K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX AGF_SAM_IDX ON ARRAY_GENO_ABN_FACT
(BIOSPECIMEN_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          129520K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX AGF_SEX_BIDX ON ARRAY_GENO_ABN_FACT
(GENDER_CODE)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2320K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BIOS_SAM_IDX ON BIOSPECIMEN_DIM
(SAMPLE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BIO_PTDID_IDX ON BIOSPECIMEN_DIM
(PATIENT_DID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CB_CYTOBAND_IDX ON CYTOBAND_POSITION
(CYTOBAND)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CB_END_IDX ON CYTOBAND_POSITION
(CB_END_POS)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CB_START_IDX ON CYTOBAND_POSITION
(CB_START)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CD_CYTOBAND_IDX ON CLONE_DIM
(CYTOBAND)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CD_UPPER_CLONENM_IDX ON CLONE_DIM
(UPPER("CLONE_NAME"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CD_UPPER_CYTOBAND_IDX ON CLONE_DIM
(UPPER("CYTOBAND"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CLONENM_IDX ON CLONE_DIM
(CLONE_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          680K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CP_CHRCYTOBAND_IDX ON CYTOBAND_POSITION
(CHR_CYTOBAND)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CP_CHROM_IDX ON CYTOBAND_POSITION
(CHROMOSOME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CYTOBAND_IDX ON PROBESET_DIM
(CYTOBAND)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1920K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DATANM_IDX ON STUDY_DATASET_DIM
(DATASET_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_CLONEID_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(CLONE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_CLONENM_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(CLONE_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DEGF_DISEASETYPE_BIDX ON DIFFERENTIAL_EXPRESSION_GFACT
(DISEASE_TYPE)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DEGF_DISTYPE_BIDX ON DIFFERENTIAL_EXPRESSION_GFACT
(DISEASE_TYPE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DEGF_DTATSET_BIDX ON DIFFERENTIAL_EXPRESSION_GFACT
(DATASET_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DEGF_EXPPLAT_BIDX ON DIFFERENTIAL_EXPRESSION_GFACT
(EXP_PLATFORM_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_EXPR_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(EXPRESSION_RATIO)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_GSYMBOL_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DEGF_INST_BIDX ON DIFFERENTIAL_EXPRESSION_GFACT
(INSTITUTION_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_NORMI_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(NORMAL_INTENSITY)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_PROID_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(PROBESET_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_PRONM_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(PROBESET_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_RPV_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(RATIO_PVAL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_UPPER_CLONENM_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(UPPER("CLONE_NAME"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_UPPER_GSYMBOL_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(UPPER("GENE_SYMBOL"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DEGF_UPPER_PROBNM_IDX ON DIFFERENTIAL_EXPRESSION_GFACT
(UPPER("PROBESET_NAME"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DESF_AGEGRP_BIDX ON DIFFERENTIAL_EXPRESSION_SFACT
(AGE_GROUP)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_BIOSPID_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(BIOSPECIMEN_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_CLONEID_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(CLONE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_CLONENM_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(CLONE_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_CYTOBAND_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(CYTOBAND)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DESF_DATASET_BIDX ON DIFFERENTIAL_EXPRESSION_SFACT
(DATASET_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DESF_DISEASETYPE_BIDX ON DIFFERENTIAL_EXPRESSION_SFACT
(DISEASE_TYPE)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DESF_DISHISTO_BIDX ON DIFFERENTIAL_EXPRESSION_SFACT
(DISEASE_HISTORY_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DESF_DISTYPE_BIDX ON DIFFERENTIAL_EXPRESSION_SFACT
(DISEASE_TYPE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DESF_EXPPLAT_BIDX ON DIFFERENTIAL_EXPRESSION_SFACT
(EXP_PLATFORM_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_EXPR_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(EXPRESSION_RATIO)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DESF_GENDER_BIDX ON DIFFERENTIAL_EXPRESSION_SFACT
(GENDER_CODE)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_GSYMBOL_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DESF_INST_BIDX ON DIFFERENTIAL_EXPRESSION_SFACT
(INSTITUTION_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_NORMI_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(NORMAL_INTENSITY)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_PROSETID_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(PROBESET_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_PROSETNM_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(PROBESET_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_SAMI_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(SAMPLE_INTENSITY)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_SAMPLEID_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(SAMPLE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX DESF_SURLENG_BIDX ON DIFFERENTIAL_EXPRESSION_SFACT
(SURVIV_LENGTH_RANGE)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_UPPER_CLONENM_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(UPPER("CLONE_NAME"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_UPPER_GSYMBOL_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(UPPER("GENE_SYMBOL"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DESF_UPPER_PROBNM_IDX ON DIFFERENTIAL_EXPRESSION_SFACT
(UPPER("PROBESET_NAME"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DG_GRADEID_IDX ON DISEASE_GRADE
(GRADE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX DG_GRADE_IDX ON DISEASE_GRADE
(GRADE)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX EXPNM_IDX ON EXP_PLATFORM_DIM
(EXP_PLATFORM_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GC_ACC_IDX ON GENE_CLONE
(ACCESSION_NUMBER)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1560K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GC_GSYMBOL_IDX ON GENE_CLONE
(GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1040K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GC_IMAGEID_IDX ON GENE_CLONE
(IMAGE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1560K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GC_LLID_IDX ON GENE_CLONE
(LL_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          680K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GC_UPGENE_IDX ON GENE_CLONE
(UP_GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GC_UPPER_GSYMBOL_IDX ON GENE_CLONE
(UPPER("GENE_SYMBOL"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GENE_CLONE_IND ON GENE_CLONE
(CLONE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1056K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLACS_ACC_IDX ON GENE_LL_ACC_SNP
(ACCESSION)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLAS_CHR_BIDX ON GENE_LL_ACC_SNP
(CHROMOSOME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLAS_GENE_IDX ON GENE_LL_ACC_SNP
(GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLAS_LLID_IDX ON GENE_LL_ACC_SNP
(LL_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLAS_SNPID_IDX ON GENE_LL_ACC_SNP
(SNP_PROBESET_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLAS_SNPNM_IDX ON GENE_LL_ACC_SNP
(PROBESET_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLAS_UPGENE_IDX ON GENE_LL_ACC_SNP
(UP_GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GO_GONM_IDX ON GENE_ONTOLOGY
(GO_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GO_NGOIDX_IDX ON GENE_ONTOLOGY
(GO_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GO_SYMBOL_IDX ON GENE_ONTOLOGY
(GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1560K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GO_UPGENE_IDX ON GENE_ONTOLOGY
(UP_GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GO_UPPER_GSYMBOL_IDX ON GENE_ONTOLOGY
(UPPER("GENE_SYMBOL"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GP_GSYMBOL_IDX ON GENE_PATHWAY
(GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GP_PATHNM_IDX ON GENE_PATHWAY
(PATHWAY_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GP_UPPER_GSYMBOL_IDX ON GENE_PATHWAY
(UPPER("GENE_SYMBOL"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GP_UPPER_PATHWAY_IDX ON GENE_PATHWAY
(UPPER("PATHWAY_NAME"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GS_GENE_IDX ON GENE_SNP
(GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GS_SNPID_IDX ON GENE_SNP
(SNP_PROBESET_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GS_SNPNM_IDX ON GENE_SNP
(PROBESET_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GS_UPGENE_IDX ON GENE_SNP
(UP_GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX INSD_INSTNM_IDX ON INSTITUTION_DIM
(INSTITUTION_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX LS_LLID_IDX ON LL_SNP
(LL_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX LS_SNPID_IDX ON LL_SNP
(SNP_PROBESET_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX LS_SNPNM_IDX ON LL_SNP
(PROBESET_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PD_CHROM_IDX ON PROBESET_DIM
(CHROMOSOME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1040K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PD_KBEND_IDX ON PROBESET_DIM
(KB_END)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1040K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PD_KBSTART_IDX ON PROBESET_DIM
(KB_START)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1040K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PD_LLID_IDX ON PROBESET_DIM
(LL_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1040K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PD_UPGENE_IDX ON PROBESET_DIM
(UP_GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PD_UPPER_CYTOBAND_IDX ON PROBESET_DIM
(UPPER("CYTOBAND"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PD_UPPER_GSYMBOL_IDX ON PROBESET_DIM
(UPPER("GENE_SYMBOL"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PD_UPPER_PROBNM_IDX ON PROBESET_DIM
(UPPER("PROBESET_NAME"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PROBENM_IDX ON PROBESET_DIM
(PROBESET_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1560K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PS_SYMBOL_IDX ON PROBESET_DIM
(GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1536K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PTD_AGE_IDX ON PATIENT_DATA
(AGE)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PTD_BIOID_IDX ON PATIENT_DATA
(BIOSPECIMEN_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PTD_SUR_IDX ON PATIENT_DATA
(SURVIVAL_LENGTH)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SNPDM_PRONM_IDX ON SNP_PROBESET_DIM
(PROBESET_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SNPPD_CYTOBAND_IDX ON SNP_PROBESET_DIM
(CYTOBAND)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3472K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SNPPD_DBSNP_IDX ON SNP_PROBESET_DIM
(DB_SNP_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          5M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SNPPD_PHYSPOS_IDX ON SNP_PROBESET_DIM
(PHYSICAL_POSITION)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2320K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SNPPD_UPPER_CYTOBAND_IDX ON SNP_PROBESET_DIM
(UPPER("CYTOBAND"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SNPPD_UPPER_PROBNM_IDX ON SNP_PROBESET_DIM
(UPPER("PROBESET_NAME"))
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKAGENT ON AGENT_DIM
(AGENT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKAGE_GROUP_DX ON AGE_GROUP_DX_DIM
(AGE_GROUP)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKARRAY_PLATFORM_DIM ON EXP_PLATFORM_DIM
(EXP_PLATFORM_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKBIOSPECIMEN_DIM ON BIOSPECIMEN_DIM
(BIOSPECIMEN_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKCLONE_DIM ON CLONE_DIM
(CLONE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKCYTOBAND_POSITION ON CYTOBAND_POSITION
(CYTOBAND_POSITION_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKDETECTION_TYPE_STG ON DETECTION_TYPE
(DETECTION_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKDIFFERENTIAL_EXPRESSION_FAC ON DIFFERENTIAL_EXPRESSION_GFACT
(DEG_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          7640K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKDISEASE_HISTORY ON DISEASE_HISTORY_DIM
(DISEASE_HISTORY_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKDISEASE_TYPE_DIM ON DISEASE_TYPE_DIM
(DISEASE_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKGENDER ON GENDER_DIM
(GENDER_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKINSTITUTION_DIM ON INSTITUTION_DIM
(INSTITUTION_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKPATIENT ON PATIENT
(PATIENT_DID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKPOPULATION_TYPE ON POPULATION_TYPE
(POPULATION_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKSTUDY_DATASET_DIM ON STUDY_DATASET_DIM
(DATASET_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKSTUDY_PHASE ON STUDY_TIMECOURSE_DIM
(TIMECOURSE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKSURVIVAL_LENGTH_RANGE ON SURVIVAL_LENGTH_RANGE_DIM
(SURVIVAL_LENGTH_RANGE)
NOLOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKTREATMENT_HISTORY ON TREATMENT_HISTORY_DIM
(TREATMENT_HISTORY_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE AGENT_DIM ADD (
  PRIMARY KEY (AGENT_ID));


ALTER TABLE AGE_GROUP_DX_DIM ADD (
  PRIMARY KEY (AGE_GROUP));


ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  PRIMARY KEY (AGA_ID)
    USING INDEX 
    TABLESPACE NAUTILUS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          129560K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE BIOSPECIMEN_DIM ADD (
  PRIMARY KEY (BIOSPECIMEN_ID));


ALTER TABLE CLONE_DIM ADD (
  PRIMARY KEY (CLONE_ID));


ALTER TABLE CYTOBAND_POSITION ADD (
  PRIMARY KEY (CYTOBAND_POSITION_ID));


ALTER TABLE DETECTION_TYPE ADD (
  PRIMARY KEY (DETECTION_TYPE_ID));


ALTER TABLE DIFFERENTIAL_EXPRESSION_GFACT ADD (
  PRIMARY KEY (DEG_ID));


ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  PRIMARY KEY (DES_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          86440K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE DISEASE_HISTORY_DIM ADD (
  PRIMARY KEY (DISEASE_HISTORY_ID));


ALTER TABLE DISEASE_TYPE_DIM ADD (
  PRIMARY KEY (DISEASE_TYPE_ID));


ALTER TABLE EXP_PLATFORM_DIM ADD (
  PRIMARY KEY (EXP_PLATFORM_ID));


ALTER TABLE GENDER_DIM ADD (
  PRIMARY KEY (GENDER_CODE));


ALTER TABLE GENE_CLONE ADD (
  PRIMARY KEY (GENE_CLONE_ID)
    USING INDEX 
    TABLESPACE NAUTILUS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          680K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE GENO_ABN_TYPE ADD (
  PRIMARY KEY (GENO_ABN_TYPE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          40K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE INSTITUTION_DIM ADD (
  PRIMARY KEY (INSTITUTION_ID));


ALTER TABLE LOSS_GAIN_CODE ADD (
  PRIMARY KEY (LOSS_GAIN)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          40K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE PATIENT ADD (
  PRIMARY KEY (PATIENT_DID));


ALTER TABLE POPULATION_TYPE ADD (
  PRIMARY KEY (POPULATION_TYPE_ID));


ALTER TABLE PROBESET_DIM ADD (
  PRIMARY KEY (PROBESET_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          1320K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE SNP_PROBESET_DIM ADD (
  PRIMARY KEY (SNP_PROBESET_ID)
    USING INDEX 
    TABLESPACE NAUTILUS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          2320K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE STUDY_DATASET_DIM ADD (
  PRIMARY KEY (DATASET_ID));


ALTER TABLE STUDY_TIMECOURSE_DIM ADD (
  PRIMARY KEY (TIMECOURSE_ID));


ALTER TABLE SURVIVAL_LENGTH_RANGE_DIM ADD (
  PRIMARY KEY (SURVIVAL_LENGTH_RANGE));


ALTER TABLE TREATMENT_HISTORY_DIM ADD (
  PRIMARY KEY (TREATMENT_HISTORY_ID));


ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (TIMECOURSE_ID) 
    REFERENCES STUDY_TIMECOURSE_DIM (TIMECOURSE_ID));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (EXP_PLATFORM_ID) 
    REFERENCES EXP_PLATFORM_DIM (EXP_PLATFORM_ID));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (GENDER_CODE) 
    REFERENCES GENDER_DIM (GENDER_CODE));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (DATASET_ID) 
    REFERENCES STUDY_DATASET_DIM (DATASET_ID));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (INSTITUTION_ID) 
    REFERENCES INSTITUTION_DIM (INSTITUTION_ID));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (DISEASE_TYPE_ID) 
    REFERENCES DISEASE_TYPE_DIM (DISEASE_TYPE_ID));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (SNP_PROBESET_ID) 
    REFERENCES SNP_PROBESET_DIM (SNP_PROBESET_ID));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (AGENT_ID) 
    REFERENCES AGENT_DIM (AGENT_ID));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (TREATMENT_HISTORY_ID) 
    REFERENCES TREATMENT_HISTORY_DIM (TREATMENT_HISTORY_ID));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (DISEASE_HISTORY_ID) 
    REFERENCES DISEASE_HISTORY_DIM (DISEASE_HISTORY_ID));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (AGE_GROUP) 
    REFERENCES AGE_GROUP_DX_DIM (AGE_GROUP));

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (SURVIVAL_LENGTH_RANGE) 
    REFERENCES SURVIVAL_LENGTH_RANGE_DIM (SURVIVAL_LENGTH_RANGE) DISABLE);

ALTER TABLE ARRAY_GENO_ABN_FACT ADD (
  FOREIGN KEY (BIOSPECIMEN_ID) 
    REFERENCES BIOSPECIMEN_DIM (BIOSPECIMEN_ID));


ALTER TABLE BIOSPECIMEN_DIM ADD (
  FOREIGN KEY (PATIENT_DID) 
    REFERENCES PATIENT (PATIENT_DID));


ALTER TABLE DIFFERENTIAL_EXPRESSION_GFACT ADD (
  FOREIGN KEY (CLONE_ID) 
    REFERENCES CLONE_DIM (CLONE_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_GFACT ADD (
  FOREIGN KEY (EXP_PLATFORM_ID) 
    REFERENCES EXP_PLATFORM_DIM (EXP_PLATFORM_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_GFACT ADD (
  FOREIGN KEY (INSTITUTION_ID) 
    REFERENCES INSTITUTION_DIM (INSTITUTION_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_GFACT ADD (
  FOREIGN KEY (DATASET_ID) 
    REFERENCES STUDY_DATASET_DIM (DATASET_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_GFACT ADD (
  FOREIGN KEY (DISEASE_TYPE_ID) 
    REFERENCES DISEASE_TYPE_DIM (DISEASE_TYPE_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_GFACT ADD (
  FOREIGN KEY (PROBESET_ID) 
    REFERENCES PROBESET_DIM (PROBESET_ID));


ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (AGENT_ID) 
    REFERENCES AGENT_DIM (AGENT_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (TREATMENT_HISTORY_ID) 
    REFERENCES TREATMENT_HISTORY_DIM (TREATMENT_HISTORY_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (DISEASE_HISTORY_ID) 
    REFERENCES DISEASE_HISTORY_DIM (DISEASE_HISTORY_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (AGE_GROUP) 
    REFERENCES AGE_GROUP_DX_DIM (AGE_GROUP));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (BIOSPECIMEN_ID) 
    REFERENCES BIOSPECIMEN_DIM (BIOSPECIMEN_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (TIMECOURSE_ID) 
    REFERENCES STUDY_TIMECOURSE_DIM (TIMECOURSE_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (EXP_PLATFORM_ID) 
    REFERENCES EXP_PLATFORM_DIM (EXP_PLATFORM_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (GENDER_CODE) 
    REFERENCES GENDER_DIM (GENDER_CODE));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (DATASET_ID) 
    REFERENCES STUDY_DATASET_DIM (DATASET_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (INSTITUTION_ID) 
    REFERENCES INSTITUTION_DIM (INSTITUTION_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (PROBESET_ID) 
    REFERENCES PROBESET_DIM (PROBESET_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (CLONE_ID) 
    REFERENCES CLONE_DIM (CLONE_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (DISEASE_TYPE_ID) 
    REFERENCES DISEASE_TYPE_DIM (DISEASE_TYPE_ID));

ALTER TABLE DIFFERENTIAL_EXPRESSION_SFACT ADD (
  FOREIGN KEY (SURVIV_LENGTH_RANGE) 
    REFERENCES SURVIVAL_LENGTH_RANGE_DIM (SURVIVAL_LENGTH_RANGE) DISABLE);


ALTER TABLE PATIENT ADD (
  FOREIGN KEY (POPULATION_TYPE_ID) 
    REFERENCES POPULATION_TYPE (POPULATION_TYPE_ID));


ALTER TABLE PROTEIN_FAMILY ADD (
  FOREIGN KEY (PROBESET_ID) 
    REFERENCES PROBESET_DIM (PROBESET_ID));


ALTER TABLE SWISSPROT ADD (
  FOREIGN KEY (PROBESET_ID) 
    REFERENCES PROBESET_DIM (PROBESET_ID));


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  AGENT_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  AGE_GROUP_DX_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  ARRAY_GENO_ABN_FACT TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  BIOSPECIMEN_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  CLONE_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  CYTOBAND_POSITION TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  DETECTION_TYPE TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  DIFFERENTIAL_EXPRESSION_GFACT TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  DIFFERENTIAL_EXPRESSION_SFACT TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  DISEASE_GRADE TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  DISEASE_HISTORY_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  DISEASE_TYPE_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  EXP_PLATFORM_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENDER_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_CLONE TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_ONTOLOGY TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_PATHWAY TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENO_ABN_TYPE TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  INSTITUTION_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  LOSS_GAIN_CODE TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  PATIENT TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  POPULATION_TYPE TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  PROBESET_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  PROTEIN_FAMILY TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  REFSEQ_MRNA_ID TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  REFSEQ_PROTEIN_ID TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SNP_PROBESET_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  STUDY_DATASET_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  STUDY_TIMECOURSE_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SURVIVAL_LENGTH_RANGE_DIM TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SWISSPROT TO NAUTILUSDEV2;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  TREATMENT_HISTORY_DIM TO NAUTILUSDEV2;


