/*L
  Copyright (c) 2006 SAIC, SAIC-F.

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/rembrandt/LICENSE.txt for details.
L*/

DROP TABLE ACCESSION_BP_POSITION CASCADE CONSTRAINTS;

CREATE TABLE ACCESSION_BP_POSITION
(
  QNAME   VARCHAR2(40),
  TNAME   VARCHAR2(40),
  TSTART  VARCHAR2(40),
  TEND    VARCHAR2(40)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          291480K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE ACC_GENE_LL_STARTEND CASCADE CONSTRAINTS;

CREATE TABLE ACC_GENE_LL_STARTEND
(
  ACC          VARCHAR2(40),
  CHROMOSOME   VARCHAR2(40),
  C_START      VARCHAR2(40),
  C_END        VARCHAR2(40),
  GENE_SYMBOL  VARCHAR2(100),
  LL_ID        VARCHAR2(100),
  CYTOBAND     VARCHAR2(100),
  OMIM_ID      VARCHAR2(100),
  GENE_TITLE   VARCHAR2(1000)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          291480K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE AFFY_ANNO_STG CASCADE CONSTRAINTS;

CREATE TABLE AFFY_ANNO_STG
(
  PROBESET_NAME         VARCHAR2(200),
  GENECHIP_ARRAY        VARCHAR2(200),
  SPECIES_NAME          VARCHAR2(255),
  GENOME_VERSION        VARCHAR2(200),
  ALIGNMENTS            VARCHAR2(255),
  GENE_TITLE            VARCHAR2(4000),
  GENE_SYMBOL           VARCHAR2(200),
  CHROMOSOMAL_LOCATION  VARCHAR2(200),
  UNIGENE_ID            VARCHAR2(500),
  ENSEMBL               VARCHAR2(2000),
  LOCUSLINK             VARCHAR2(500),
  SWISSPROT_ID          VARCHAR2(4000),
  EC                    VARCHAR2(500),
  OMIM                  VARCHAR2(500),
  REFSEQPROTEIN_ID      VARCHAR2(1000),
  REFSEQ_TRANSCRIPT_ID  VARCHAR2(1000),
  GONTO_BIO_PROC        CLOB,
  GONTO_CELL_COMP       CLOB,
  GONTO_MOLECU_FUNC     CLOB,
  PATHWAY_NAME          VARCHAR2(4000),
  ACCESSION_NUM         VARCHAR2(100)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE ARRAY_CGH_STG DROP PRIMARY KEY CASCADE;
DROP TABLE ARRAY_CGH_STG CASCADE CONSTRAINTS;

CREATE TABLE ARRAY_CGH_STG
(
  BAC_ID           VARCHAR2(50)                 NOT NULL,
  CHROMOSOME_NAME  VARCHAR2(20),
  CHANNEL_RATIO    FLOAT(126),
  LOSS_GAIN        VARCHAR2(20)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE BAC_GENE_STG CASCADE CONSTRAINTS;

CREATE TABLE BAC_GENE_STG
(
  GENE_SYMBOL  VARCHAR2(50),
  BAC_ID       VARCHAR2(50)                     NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE CB_POSITION_STG CASCADE CONSTRAINTS;

CREATE TABLE CB_POSITION_STG
(
  CHROMOSOME  VARCHAR2(10),
  CB_START    NUMBER,
  CB_END_POS  NUMBER,
  CYTOBAND    VARCHAR2(50),
  GIESTAIN    VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE CDNA_SINFO CASCADE CONSTRAINTS;

CREATE TABLE CDNA_SINFO
(
  SAMPLE_ID        VARCHAR2(50),
  CLONE_ID         NUMBER                       NOT NULL,
  CLONE_NAME       VARCHAR2(200)                NOT NULL,
  SN_RATIO         FLOAT(126),
  SAMPLE_RATIO     FLOAT(126),
  NORMAL_RATIO     FLOAT(126),
  GENE_SYMBOL      VARCHAR2(50),
  CYTOBAND         VARCHAR2(500),
  DATASET_ID       NUMBER,
  EXP_PLATFORM_ID  NUMBER
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          242840K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE CLINICAL_INFO_STG CASCADE CONSTRAINTS;

CREATE TABLE CLINICAL_INFO_STG
(
  ROW_NAMES         VARCHAR2(20)                NOT NULL,
  HF                VARCHAR2(20),
  DIAGNOSIS         VARCHAR2(50),
  WHO_GRADE         VARCHAR2(5),
  MIB               VARCHAR2(10),
  AGE_DX            NUMBER,
  SEX               VARCHAR2(20),
  DATE_CUT          VARCHAR2(20),
  DOD               VARCHAR2(20),
  DODX              VARCHAR2(20),
  DLFU              VARCHAR2(20),
  SURVIVAL_TIME     NUMBER,
  TUMOR             VARCHAR2(10),
  INSTITUTION_NAME  VARCHAR2(100),
  DISEASE_HISTORY   VARCHAR2(50),
  CENSORING_STATUS  VARCHAR2(5)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE CLININFO CASCADE CONSTRAINTS;

CREATE TABLE CLININFO
(
  SAMPLE_ID              VARCHAR2(50)           NOT NULL,
  BIOSPECIMEN_ID         NUMBER                 NOT NULL,
  DISEASE_TYPE_ID        NUMBER                 NOT NULL,
  GENDER                 VARCHAR2(20),
  INSTITUTION_ID         NUMBER                 NOT NULL,
  AGE                    NUMBER,
  AGE_GROUP              VARCHAR2(20)           NOT NULL,
  SURVIVAL_LENGTH        NUMBER,
  SURVIVAL_LENGTH_RANGE  VARCHAR2(15)           NOT NULL,
  DISEASE_HISTORY_ID     NUMBER                 NOT NULL
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE CLONE_ACCESSION CASCADE CONSTRAINTS;

CREATE TABLE CLONE_ACCESSION
(
  CLONE_ID          NUMBER                      NOT NULL,
  ACCESSION_NUMBER  VARCHAR2(100),
  IMAGE_ID          VARCHAR2(50)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1720K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE EXP_GENE_SINFO CASCADE CONSTRAINTS;

CREATE TABLE EXP_GENE_SINFO
(
  SAMPLE_ID         VARCHAR2(50),
  PROBESET_ID       NUMBER                      NOT NULL,
  PROBESET_NAME     VARCHAR2(200)               NOT NULL,
  S_RATIO           FLOAT(126),
  SAMPLE_INTENSITY  FLOAT(126),
  NORMAL_INTENSITY  FLOAT(126),
  GENE_SYMBOL       VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          194232K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE CASCADE CONSTRAINTS;

CREATE TABLE GENE
(
  GENE_SYMBOL  VARCHAR2(100)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_ACCESSION CASCADE CONSTRAINTS;

CREATE TABLE GENE_ACCESSION
(
  GENE_SYMBOL       VARCHAR2(100),
  ACCESSION_NUMBER  VARCHAR2(100),
  ACC_START         NUMBER,
  ACC_END           NUMBER
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_CDNA_LOAD_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_CDNA_LOAD_STG
(
  WELL_ID     NUMBER,
  CLONE       VARCHAR2(500),
  CLONE_DESC  VARCHAR2(2000),
  UNIGENE     VARCHAR2(500),
  GENE        VARCHAR2(1000),
  MAP         VARCHAR2(1000)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_CLONE_NR_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_CLONE_NR_STG
(
  CLONE_NAME    VARCHAR2(200),
  NORMAL_RATIO  FLOAT(126)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_CLONE_SNR_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_CLONE_SNR_STG
(
  SAMPLE_ID   VARCHAR2(50),
  CLONE_NAME  VARCHAR2(200),
  SN_RATIO    FLOAT(126)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_CLONE_SR_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_CLONE_SR_STG
(
  SAMPLE_ID          VARCHAR2(50),
  CLONE_NAME         VARCHAR2(200),
  SAMPLE_RATIO       FLOAT(126),
  DATA_SET           VARCHAR2(100),
  INSTITUTION_NAME   VARCHAR2(100),
  EXP_PLATFORM_NAME  VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_CLONE_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_CLONE_STG
(
  WELL_ID     NUMBER,
  CLONE       VARCHAR2(500),
  CLONE_DESC  VARCHAR2(2000),
  UNIGENE     VARCHAR2(500),
  GENE        VARCHAR2(1000),
  MAP         VARCHAR2(1000)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2320K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_EXPRESSION_SIGNAL_GSTG CASCADE CONSTRAINTS;

CREATE TABLE GENE_EXPRESSION_SIGNAL_GSTG
(
  PROBESET_NAME      VARCHAR2(200),
  PVALUE             FLOAT(126),
  RATIO              FLOAT(126),
  SAMPLE_INTENSITY   FLOAT(126),
  NORMAL_INTENSITY   FLOAT(126),
  DISEASE_TYPE       VARCHAR2(100),
  DATA_SET           VARCHAR2(100),
  INSTITUTION_NAME   VARCHAR2(100),
  EXP_PLATFORM_NAME  VARCHAR2(50)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40560K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_EXP_CDNA_GSTG CASCADE CONSTRAINTS;

CREATE TABLE GENE_EXP_CDNA_GSTG
(
  CLONE_NAME         VARCHAR2(200),
  PVALUE             FLOAT(126),
  RATIO              FLOAT(126),
  SAMPLE_INTENSITY   FLOAT(126),
  NORMAL_INTENSITY   FLOAT(126),
  DISEASE_TYPE       VARCHAR2(100),
  DATA_SET           VARCHAR2(100),
  INSTITUTION_NAME   VARCHAR2(100),
  EXP_PLATFORM_NAME  VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_EXP_SI_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_EXP_SI_STG
(
  SAMPLE_ID          VARCHAR2(50),
  PROBESET_NAME      VARCHAR2(200),
  SAMPLE_INTENSITY   FLOAT(126),
  DATA_SET           VARCHAR2(100),
  INSTITUTION_NAME   VARCHAR2(100),
  EXP_PLATFORM_NAME  VARCHAR2(50)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          291480K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_EXP_SN_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_EXP_SN_STG
(
  PROBESET_NAME     VARCHAR2(200),
  NORMAL_INTENSITY  FLOAT(126)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1560K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_EXP_SR_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_EXP_SR_STG
(
  SAMPLE_ID      VARCHAR2(50),
  PROBESET_NAME  VARCHAR2(200),
  S_RATIO        FLOAT(126)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          86440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_GO_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_GO_STG
(
  GENE_SYMBOL  VARCHAR2(50),
  GO_NAME      VARCHAR2(250),
  GO_ID        NUMBER                           NOT NULL
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_LL_ACC_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_LL_ACC_STG
(
  IMAGE_ID        VARCHAR2(20),
  ACCESSION       VARCHAR2(50),
  LL_ID           VARCHAR2(50),
  GENE_SYMBOL     VARCHAR2(100),
  C_START         NUMBER,
  C_END           NUMBER,
  CHROMOSOME      VARCHAR2(100),
  CYTOBAND        VARCHAR2(100),
  OMIM_ID         VARCHAR2(100),
  GENE_TITLE      VARCHAR2(4000),
  TNAME           VARCHAR2(40),
  UP_GENE_SYMBOL  VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_LL_ACC_TRAN CASCADE CONSTRAINTS;

CREATE TABLE GENE_LL_ACC_TRAN
(
  GENE_SYMBOL     VARCHAR2(100),
  ACCESSION       VARCHAR2(50),
  LL_ID           VARCHAR2(50),
  CHROMOSOME      VARCHAR2(100),
  C_START         NUMBER,
  C_END           NUMBER,
  UP_GENE_SYMBOL  VARCHAR2(50),
  C_STARTM        NUMBER,
  C_ENDP          NUMBER
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_LL_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_LL_STG
(
  LOCUSLINK_ID  VARCHAR2(50),
  GENE_SYMBOL   VARCHAR2(100),
  OMIM_ID       VARCHAR2(100),
  CHROMOSOME    VARCHAR2(100),
  CYTOBAND      VARCHAR2(100),
  GENE_TITLE    VARCHAR2(4000)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_ONTOLOGY_BIOMART CASCADE CONSTRAINTS;

CREATE TABLE GENE_ONTOLOGY_BIOMART
(
  GO_ID          VARCHAR2(100),
  GO_DESC        VARCHAR2(4000),
  PROBESET_NAME  VARCHAR2(200)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          11440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE GENE_PATHWAY_STG CASCADE CONSTRAINTS;

CREATE TABLE GENE_PATHWAY_STG
(
  PATHWAY_NAME     VARCHAR2(30),
  PATHWAY_DISPLAY  VARCHAR2(200),
  GENE_SYMBOL      VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE IMAGE_ACC CASCADE CONSTRAINTS;

CREATE TABLE IMAGE_ACC
(
  IMAGE_CLONEID     VARCHAR2(200),
  CLONE_COLLECTION  VARCHAR2(200),
  PLATE_NUMBER      VARCHAR2(200),
  PLATE_ROW         VARCHAR2(200),
  PLATE_COLUMN      VARCHAR2(200),
  IMAGE_LIBRARY_ID  VARCHAR2(200),
  SPECIES           VARCHAR2(200),
  ACCESSION         VARCHAR2(200)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          436976K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE IMAGE_ACCP_STG CASCADE CONSTRAINTS;

CREATE TABLE IMAGE_ACCP_STG
(
  IMAGE_ID   VARCHAR2(20),
  ACCESSION  VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          194264K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE IMAGE_ACC_LL_GENE_CB_OM_SE_UN CASCADE CONSTRAINTS;

CREATE TABLE IMAGE_ACC_LL_GENE_CB_OM_SE_UN
(
  IMAGE_ID     VARCHAR2(20),
  ACCESSION    VARCHAR2(50),
  LL_ID        VARCHAR2(50),
  GENE_SYMBOL  VARCHAR2(100),
  C_START      VARCHAR2(40),
  C_END        VARCHAR2(40),
  CHROMOSOME   VARCHAR2(100),
  CYTOBAND     VARCHAR2(100),
  OMIM_ID      VARCHAR2(100),
  GENE_TITLE   VARCHAR2(4000),
  TNAME        VARCHAR2(40)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          436992K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE LL2ACC_UNI2 CASCADE CONSTRAINTS;

CREATE TABLE LL2ACC_UNI2
(
  LL_ID  VARCHAR2(10),
  ACC    VARCHAR2(15)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE LOCULINK_ACCESSION CASCADE CONSTRAINTS;

CREATE TABLE LOCULINK_ACCESSION
(
  LL_ID  VARCHAR2(50),
  ACC    VARCHAR2(100)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE PROTEIN_FAMILY_STG CASCADE CONSTRAINTS;

CREATE TABLE PROTEIN_FAMILY_STG
(
  PROTEIN_FAMILY     VARCHAR2(1000),
  PROBESET_NAME      VARCHAR2(200),
  PROTEIN_FAMILY_ID  VARCHAR2(200)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          5M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE REFSEQ_MRNA_ID_STG CASCADE CONSTRAINTS;

CREATE TABLE REFSEQ_MRNA_ID_STG
(
  REFSEQ_MRNA_ID  VARCHAR2(50),
  PROBESET_NAME   VARCHAR2(200),
  ENSM            VARCHAR2(100)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          11440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE REFSEQ_PROTEIN_ID_STG CASCADE CONSTRAINTS;

CREATE TABLE REFSEQ_PROTEIN_ID_STG
(
  REFSEQ_PROTEIN_ID  VARCHAR2(30),
  PROBESET_NAME      VARCHAR2(200)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE SAMPLE_AGE_SURV_GRP CASCADE CONSTRAINTS;

CREATE TABLE SAMPLE_AGE_SURV_GRP
(
  SAMPLE_ID  VARCHAR2(20),
  AGE_GRP    VARCHAR2(20),
  SURV_GRP   VARCHAR2(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE SNP_ASSOCIATED_GENE CASCADE CONSTRAINTS;

CREATE TABLE SNP_ASSOCIATED_GENE
(
  SNP_PROBESET_ID   NUMBER,
  PROBESET_NAME     VARCHAR2(200),
  GENE_SYMBOL       VARCHAR2(50),
  ARRAY_NAME        VARCHAR2(50),
  ACCESSION_NUMBER  VARCHAR2(50),
  UP_GENE_SYMBOL    VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE SNP_ASSOCIATED_GENE_HSTG CASCADE CONSTRAINTS;

CREATE TABLE SNP_ASSOCIATED_GENE_HSTG
(
  SNP_PROBESET_NAME  VARCHAR2(200),
  GENE_SYMBOL        VARCHAR2(50),
  ACCESSION_NUMBER   VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE SNP_ASSOCIATED_GENE_XSTG CASCADE CONSTRAINTS;

CREATE TABLE SNP_ASSOCIATED_GENE_XSTG
(
  SNP_PROBESET_NAME  VARCHAR2(200),
  GENE_SYMBOL        VARCHAR2(50),
  ACCESSION_NUMBER   VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE SNP_PROBESET_STG CASCADE CONSTRAINTS;

CREATE TABLE SNP_PROBESET_STG
(
  PROBESET_NAME        VARCHAR2(200),
  DB_SNP_ID            CHAR(18),
  PHYSICAL_POSITION    VARCHAR2(50),
  CYTOBAND             VARCHAR2(50),
  ALLELE_FREQUENCY_AS  VARCHAR2(200),
  ALLELE_FREQUENCY_AF  VARCHAR2(200),
  ALLELE_FREQUENCY_CA  VARCHAR2(200),
  ARRAY_NAME           VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          17120K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE SNP_SAMPFACT_STG CASCADE CONSTRAINTS;

CREATE TABLE SNP_SAMPFACT_STG
(
  SAMPLE_ID     VARCHAR2(100),
  PROBEST_NAME  VARCHAR2(200),
  COPY_NUMBER   FLOAT(126),
  P_VALUE       FLOAT(126),
  LOH           FLOAT(126)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          420080K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE SWISSPROT_STG CASCADE CONSTRAINTS;

CREATE TABLE SWISSPROT_STG
(
  SWISSPROT      VARCHAR2(50),
  PROBESET_NAME  VARCHAR2(200)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE SWISSPROT_STG_BIOMART CASCADE CONSTRAINTS;

CREATE TABLE SWISSPROT_STG_BIOMART
(
  SWISSPROT      VARCHAR2(50),
  PROBESET_NAME  VARCHAR2(200)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


DROP TABLE Z_GENE_CLONE CASCADE CONSTRAINTS;

CREATE TABLE Z_GENE_CLONE
(
  GENE_CLONE_ID     NUMBER                      NOT NULL,
  UNIGENE_LIBRARY   VARCHAR2(50),
  GENE_TITLE        VARCHAR2(2000),
  UNIGENE_ID        VARCHAR2(50),
  LL_ID             VARCHAR2(50),
  EC                VARCHAR2(100),
  ACCESSION_NUMBER  VARCHAR2(100),
  ACC_START         NUMBER,
  ACC_END           NUMBER,
  CLONE_ID          NUMBER,
  GENE_SYMBOL       VARCHAR2(50),
  IMAGE_ID          VARCHAR2(50),
  OMIM_ID           VARCHAR2(50)
)
TABLESPACE NAUTILUS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;


CREATE INDEX ACCP_ACC_IDX ON IMAGE_ACCP_STG
(ACCESSION)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ACC_INDX ON IMAGE_ACC
(ACCESSION)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          129504K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CLOACC_ACC_IDX ON CLONE_ACCESSION
(ACCESSION_NUMBER)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1040K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CLOACC_CLOID_IDX ON CLONE_ACCESSION
(CLONE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1040K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CLOACC_IMAGEID_IDX ON CLONE_ACCESSION
(IMAGE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1040K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CLONE_IDX ON GENE_CDNA_LOAD_STG
(CLONE)
NOLOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1320K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CLONNM_IDX ON GENE_CLONE_SR_STG
(CLONE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          107960K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GACC_GSYMBOL_IDX ON GENE_ACCESSION
(GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1560K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GCLON_IDX ON GENE_CLONE_STG
(CLONE)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          680K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GCNDA_CLONENM_IDX ON GENE_CLONE_NR_STG
(CLONE_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLA_ACC_IDX ON GENE_LL_ACC_STG
(ACCESSION)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLA_CEND_IDX ON GENE_LL_ACC_STG
(C_END)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLA_CHR_BIDX ON GENE_LL_ACC_STG
(CHROMOSOME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLA_CSTART_IDX ON GENE_LL_ACC_STG
(C_START)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLA_GENETITLE_IDX ON GENE_LL_ACC_STG
(GENE_TITLE)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLA_GENE_IDX ON GENE_LL_ACC_STG
(GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLA_IMAGEID_IDX ON GENE_LL_ACC_STG
(IMAGE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLA_LLID_IDX ON GENE_LL_ACC_STG
(LL_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLA_OMID_IDX ON GENE_LL_ACC_STG
(OMIM_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX GLA_UPGENE_IDX ON GENE_LL_ACC_STG
(UP_GENE_SYMBOL)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IMAGE_ACC_P_ID_IDX ON IMAGE_ACCP_STG
(IMAGE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          194248K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDX1 ON EXP_GENE_SINFO
(SAMPLE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          57560K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDX2 ON CLININFO
(SAMPLE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX LL_ACC_ACC_IDX ON LOCULINK_ACCESSION
(ACC)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PROBSETNM_IDX ON GENE_EXP_SI_STG
(PROBESET_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          86440K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PROB_IDX ON GENE_EXP_SN_STG
(PROBESET_NAME)
NOLOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2840K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX PROTPROB_IDX ON PROTEIN_FAMILY_STG
(PROBESET_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1560K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SAGH_PRONM_IDX ON SNP_ASSOCIATED_GENE_HSTG
(SNP_PROBESET_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SAGX_SNPNM_IDX ON SNP_ASSOCIATED_GENE_XSTG
(SNP_PROBESET_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SAMAGESUR_AGE_IDX ON SAMPLE_AGE_SURV_GRP
(AGE_GRP)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SAMAGESUR_SUR_IDX ON SAMPLE_AGE_SURV_GRP
(SURV_GRP)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SAMAGSUR_SAMID_IDX ON SAMPLE_AGE_SURV_GRP
(SAMPLE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SAMCLONI_IDX ON GENE_CLONE_SR_STG
(SAMPLE_ID, CLONE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          97160K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SAMCLONR_IDX ON GENE_CLONE_SNR_STG
(SAMPLE_ID, CLONE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          97160K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SAMPROI_IDX ON GENE_EXP_SI_STG
(SAMPLE_ID, PROBESET_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          194360K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SAMPROR_IDX ON GENE_EXP_SR_STG
(SAMPLE_ID, PROBESET_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          194360K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SNPSTG_SAMID_IDX ON SNP_SAMPFACT_STG
(SAMPLE_ID)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          194360K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SNP_PRONM_IDX ON SNP_SAMPFACT_STG
(PROBEST_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          291480K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SNRCLONNM_IDX ON GENE_CLONE_SNR_STG
(CLONE_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          57640K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX SRDATASET_BIDX ON GENE_CLONE_SR_STG
(DATA_SET)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          680K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX SREXPLAT_BIDX ON GENE_CLONE_SR_STG
(EXP_PLATFORM_NAME)
LOGGING
TABLESPACE NAUTILUS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          680K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XPKARRAY_CGH_STG ON ARRAY_CGH_STG
(BAC_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ARRAY_CGH_STG ADD (
  PRIMARY KEY (BAC_ID));


ALTER TABLE CLONE_ACCESSION ADD (
  FOREIGN KEY (CLONE_ID) 
    REFERENCES NAUTILUSDEV.CLONE_DIM (CLONE_ID));


GRANT SELECT ON  ACCESSION_BP_POSITION TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  ACC_GENE_LL_STARTEND TO NAUTILUSDEV;

GRANT SELECT ON  ACC_GENE_LL_STARTEND TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  AFFY_ANNO_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  ARRAY_CGH_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  BAC_GENE_STG TO NAUTILUSDEV;

GRANT SELECT ON  CB_POSITION_STG TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  CDNA_SINFO TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  CLINICAL_INFO_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  CLININFO TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  CLONE_ACCESSION TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  EXP_GENE_SINFO TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE TO NAUTILUSDEV;

GRANT SELECT ON  GENE_ACCESSION TO PUBLIC;

GRANT SELECT ON  GENE_CDNA_LOAD_STG TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_CLONE_NR_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_CLONE_SNR_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_CLONE_SR_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_CLONE_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_EXPRESSION_SIGNAL_GSTG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_EXP_CDNA_GSTG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_EXP_SI_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_EXP_SN_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_EXP_SR_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_GO_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_LL_ACC_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_LL_ACC_TRAN TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_LL_STG TO NAUTILUSDEV;

GRANT SELECT ON  GENE_ONTOLOGY_BIOMART TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  GENE_PATHWAY_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  IMAGE_ACC TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  IMAGE_ACCP_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  IMAGE_ACC_LL_GENE_CB_OM_SE_UN TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  LL2ACC_UNI2 TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  LOCULINK_ACCESSION TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  PROTEIN_FAMILY_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  REFSEQ_MRNA_ID_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  REFSEQ_PROTEIN_ID_STG TO NAUTILUSDEV;

GRANT INSERT, UPDATE ON  SAMPLE_AGE_SURV_GRP TO NAUTILUSDEV;

GRANT SELECT ON  SAMPLE_AGE_SURV_GRP TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SNP_ASSOCIATED_GENE TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SNP_ASSOCIATED_GENE_HSTG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SNP_ASSOCIATED_GENE_XSTG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SNP_PROBESET_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SNP_SAMPFACT_STG TO NAUTILUSDEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  SWISSPROT_STG TO NAUTILUSDEV;

GRANT SELECT ON  SWISSPROT_STG_BIOMART TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  Z_GENE_CLONE TO NAUTILUSDEV;

GRANT SELECT ON  Z_GENE_CLONE TO PUBLIC;


