function FileData_Pairs(x)
{
x.t("lists","output");
x.t("generated:","class");
x.t("displays","query");
x.t("hierarchical","clustering");
x.t("back","forward");
x.t("results","back");
x.t("results","high");
x.t("results","viewing");
x.t("results","figure");
x.t("results","following");
x.t("high","order");
x.t("forward","high");
x.t("name","lists");
x.t("comparison","report");
x.t("component","analysis");
x.t("6.1","displays");
x.t("viewing","results");
x.t("report","principal");
x.t("report","view");
x.t("reports","generated:");
x.t("clustering","report");
x.t("principal","component");
x.t("figure","6.1");
x.t("view","results");
x.t("generated","query.");
x.t("output","generated");
x.t("query","name");
x.t("order","analysis");
x.t("following","high");
x.t("class","comparison");
x.t("plot","hierarchical");
x.t("analysis","results");
x.t("analysis","reports");
x.t("analysis","plot");
}
