function FileData_Pairs(x)
{
x.t("back","forward");
x.t("overview","rembrandt");
x.t("forward","rembrandt");
x.t("include:","rembrandt");
x.t("introduces","rembrandt");
x.t("provides","overview");
x.t("functions.","topics");
x.t("1.5","back");
x.t("1.5","section");
x.t("1.5","rembrandt");
x.t("section","include:");
x.t("section","introduces");
x.t("rembrandt","provides");
x.t("rembrandt","functions");
x.t("rembrandt","functions.");
x.t("rembrandt","1.5");
x.t("rembrandt","rembrandt");
x.t("topics","section");
}
