function FileData_Pairs(x)
{
x.t("table","describes");
x.t("describes","additional");
x.t("bar","graph");
x.t("back","forward");
x.t("details","back");
x.t("details","conducting");
x.t("details","point");
x.t("simple","search");
x.t("gene","expression");
x.t("forward","show");
x.t("conducting","simple");
x.t("search","gene");
x.t("search","understanding");
x.t("point","bar");
x.t("raw","gene");
x.t("information.","following");
x.t("additional","information.");
x.t("additional","information");
x.t("expression","simple");
x.t("expression","plot");
x.t("show","gene");
x.t("show","raw");
x.t("graph","additional");
x.t("information","details.");
x.t("information","item");
x.t("details.","show");
x.t("following","table");
x.t("special","instructions");
x.t("understanding","gene");
x.t("plot","details");
x.t("plot","additional");
x.t("plot","show");
x.t("item","special");
}
