function FileData_Pairs(x)
{
x.t("interfaces","navigation");
x.t("user","account");
x.t("back","forward");
x.t("getting","started");
x.t("getting","help");
x.t("features","used");
x.t("\u00adbrandt","1.5");
x.t("forward","getting");
x.t("common","features");
x.t("creating","user");
x.t("account","logging");
x.t("pages.","topics");
x.t("include:","creating");
x.t("logging","accepting");
x.t("introduces","rembrandt");
x.t("welcome","rembrandt");
x.t("started","rem\u00adbrandt");
x.t("started","rem");
x.t("rem\u00adbrandt","1.5");
x.t("provisions","welcome");
x.t("1.5","back");
x.t("1.5","getting");
x.t("1.5","section");
x.t("section","include:");
x.t("section","introduces");
x.t("rembrandt","interfaces");
x.t("rembrandt","pages.");
x.t("rembrandt","provisions");
x.t("rembrandt","1.5");
x.t("rem","\u00adbrandt");
x.t("accepting","rembrandt");
x.t("help","logging");
x.t("topics","section");
x.t("navigation","common");
x.t("used","rembrandt");
}
