function FileData_Pairs(x)
{
x.t("interfaces","navigation");
x.t("back","forward");
x.t("features","used");
x.t("forward","rembrandt");
x.t("common","features");
x.t("pages.","rembrandt");
x.t("include:","rembrandt");
x.t("described.","topics");
x.t("introduces","rembrandt");
x.t("find","additional");
x.t("queries","find");
x.t("1.5","back");
x.t("1.5","section");
x.t("1.5","rembrandt");
x.t("section","include:");
x.t("section","introduces");
x.t("rembrandt","interfaces");
x.t("rembrandt","pages.");
x.t("rembrandt","functions");
x.t("rembrandt","1.5");
x.t("rembrandt","rembrandt");
x.t("rembrandt","conduct");
x.t("conduct","queries");
x.t("additional","resources");
x.t("topics","section");
x.t("navigation","common");
x.t("used","rembrandt");
x.t("resources","described.");
}
