function FileData_Pairs(x)
{
x.t("lists","output");
x.t("displays","query");
x.t("hierarchical","clustering");
x.t("results","displays");
x.t("results","high");
x.t("results","viewing");
x.t("results","following");
x.t("high","order");
x.t("name","lists");
x.t("comparison","report");
x.t("component","analysis");
x.t("viewing","results");
x.t("report","principal");
x.t("report","genepattern");
x.t("reports","generated");
x.t("reports","view");
x.t("clustering","report");
x.t("principal","component");
x.t("generated","query");
x.t("generated","class");
x.t("view","results");
x.t("output","generated");
x.t("query","name");
x.t("order","analysis");
x.t("following","high");
x.t("genepattern","analysis");
x.t("class","comparison");
x.t("plot","hierarchical");
x.t("analysis","results");
x.t("analysis","reports");
x.t("analysis","plot");
}
