function FileData_Pairs(x)
{
x.t("survival","plot");
x.t("purposes.","click");
x.t("create","kaplan-meier");
x.t("sample","search");
x.t("sample","follow");
x.t("sample","drop-down");
x.t("sample","data");
x.t("kaplan-meier","survival");
x.t("button.","kaplan-meier");
x.t("list","comparison");
x.t("simple","search");
x.t("gene","expression");
x.t("conducting","simple");
x.t("comparison","purposes.");
x.t("search","create");
x.t("search","conducting");
x.t("search","k-m");
x.t("search","tab");
x.t("steps:","simple");
x.t("select","create");
x.t("select","sample");
x.t("appears","information");
x.t("k-m","survival");
x.t("k-m","sample");
x.t("follow","steps:");
x.t("click","button.");
x.t("drop-down","list");
x.t("expression","plot");
x.t("data","select");
x.t("data","k-m");
x.t("information","gene");
x.t("understanding","k-m");
x.t("plot","sample");
x.t("plot","appears");
x.t("plot","understanding");
x.t("tab","select");
}
