function FileData_Pairs(x)
{
x.t("managing","lists");
x.t("lists","managing");
x.t("lists","deleting");
x.t("lists","editing");
x.t("lists","back");
x.t("lists","overview");
x.t("lists","creating");
x.t("lists","section");
x.t("lists","existing");
x.t("lists","page");
x.t("lists","adding");
x.t("describes","manage");
x.t("deleting","items");
x.t("editing","existing");
x.t("back","forward");
x.t("new","lists");
x.t("new","custom");
x.t("items","lists");
x.t("overview","page");
x.t("forward","managing");
x.t("creating","new");
x.t("creating","custom");
x.t("include:","managing");
x.t("custom","lists");
x.t("lists.","topics");
x.t("section","describes");
x.t("section","include:");
x.t("existing","lists");
x.t("existing","lists.");
x.t("page","creating");
x.t("topics","section");
x.t("manage","lists");
x.t("adding","lists");
x.t("adding","new");
}
