function FileData_Pairs(x)
{
x.t("once","log");
x.t("back","forward");
x.t("getting","started");
x.t("appears.","reading");
x.t("link","lower");
x.t("clicking","link");
x.t("right-hand","corner.");
x.t("forward","accepting");
x.t("started","rem\u00adbrandt");
x.t("rem\u00adbrandt","1.5");
x.t("legal","rules");
x.t("provisions","once");
x.t("provisions","back");
x.t("provisions","getting");
x.t("provisions","click");
x.t("corner.","rembrandt");
x.t("workspace","appears.");
x.t("1.5","accepting");
x.t("rembrandt","provisions");
x.t("rembrandt","workspace");
x.t("lower","right-hand");
x.t("road","page");
x.t("click","clicking");
x.t("rules","road");
x.t("accepting","rembrandt");
x.t("page","appears.");
x.t("log","legal");
x.t("reading","provisions");
}
