function FileData_Pairs(x)
{
x.t("complex","queries");
x.t("study","advanced");
x.t("managing","advanced");
x.t("describes","create");
x.t("create","complex");
x.t("back","forward");
x.t("advanced","searches");
x.t("advanced","search");
x.t("refining","query");
x.t("overview","gene");
x.t("gene","expression");
x.t("forward","conducting");
x.t("conducting","advanced");
x.t("searches","back");
x.t("searches","refining");
x.t("searches","overview");
x.t("searches","conducting");
x.t("searches","section");
x.t("include:","advanced");
x.t("search","managing");
x.t("search","copy");
x.t("search","clinical");
x.t("queries","generate");
x.t("number","advanced");
x.t("section","describes");
x.t("section","include:");
x.t("generate","graphs.");
x.t("graphs.","topics");
x.t("expression","advanced");
x.t("topics","section");
x.t("copy","number");
x.t("clinical","study");
}
