function FileData_Pairs(x)
{
x.t("back","forward");
x.t("button.","continue");
x.t("button.","information");
x.t("indicates","genes");
x.t("found","follow");
x.t("simple","search");
x.t("gene","expression");
x.t("forward","eliminating");
x.t("conducting","simple");
x.t("cancel","button.");
x.t("continue","click");
x.t("search","gene");
x.t("search","eliminating");
x.t("search","click");
x.t("steps:","select");
x.t("select","appropriate");
x.t("aliases","back");
x.t("aliases","found");
x.t("aliases","conducting");
x.t("aliases","message");
x.t("eliminating","aliases");
x.t("follow","steps:");
x.t("end","search");
x.t("message","indicates");
x.t("option","drop-down");
x.t("click","button.");
x.t("click","cancel");
x.t("drop-down","list.");
x.t("expression","simple");
x.t("expression","plot");
x.t("genes","aliases");
x.t("information","gene");
x.t("appropriate","option");
x.t("understanding","gene");
x.t("plot","understanding");
x.t("list.","end");
}
