function FileData_Pairs(x)
{
x.t("managing","lists");
x.t("lists","managing");
x.t("lists","editing");
x.t("lists","overview");
x.t("lists","creating");
x.t("lists","viewing");
x.t("lists","section");
x.t("lists","existing");
x.t("lists","adding");
x.t("describes","manage");
x.t("deleting","entire");
x.t("editing","existing");
x.t("new","lists");
x.t("new","custom");
x.t("items","deleting");
x.t("items","list");
x.t("list","exporting");
x.t("list","removing");
x.t("overview","adding");
x.t("creating","new");
x.t("include:","managing");
x.t("custom","lists");
x.t("entire","list");
x.t("lists.","topics");
x.t("viewing","data");
x.t("section","describes");
x.t("section","include:");
x.t("existing","lists");
x.t("existing","lists.");
x.t("exporting","list");
x.t("data","items");
x.t("removing","data");
x.t("topics","section");
x.t("manage","lists");
x.t("adding","new");
}
