function FileData_Pairs(x)
{
x.t("study","advanced");
x.t("managing","individual");
x.t("describes","create");
x.t("create","compound");
x.t("advanced","searches");
x.t("advanced","search");
x.t("refining","query");
x.t("overview","gene");
x.t("gene","expression");
x.t("conducting","advanced");
x.t("searches","overview");
x.t("searches","conducting");
x.t("searches","section");
x.t("include:","advanced");
x.t("compound","queries");
x.t("search","managing");
x.t("search","copy");
x.t("search","clinical");
x.t("queries","refining");
x.t("queries","generate");
x.t("number","advanced");
x.t("section","describes");
x.t("section","include:");
x.t("generate","graphs.");
x.t("graphs.","topics");
x.t("expression","advanced");
x.t("topics","section");
x.t("copy","number");
x.t("individual","compound");
x.t("clinical","study");
}
