function FileData_Pairs(x)
{
x.t("once","select");
x.t("(go)","classification");
x.t("browser","button");
x.t("back","forward");
x.t("advanced","searches");
x.t("advanced","search");
x.t("appears.","add");
x.t("list","ids");
x.t("add","advanced");
x.t("gene","expression");
x.t("gene","ontology");
x.t("forward","selecting");
x.t("conducting","advanced");
x.t("searches","gene");
x.t("classification","once");
x.t("classification","back");
x.t("classification","conducting");
x.t("search","click");
x.t("search","selecting");
x.t("select","browser");
x.t("button","gene");
x.t("added","gene");
x.t("ids","appears.");
x.t("click","appropriate");
x.t("selecting","gene");
x.t("expression","page.");
x.t("expression","advanced");
x.t("expression","page");
x.t("page","list");
x.t("ontology","(go)");
x.t("appropriate","term.");
x.t("term.","added");
}
