function FileData_Pairs(x)
{
x.t("managing","lists");
x.t("lists","view");
x.t("icon","items");
x.t("type","list");
x.t("back","forward");
x.t("details","managing");
x.t("details","icon");
x.t("details","back");
x.t("details","view");
x.t("items","list");
x.t("items","list.");
x.t("reporter","category");
x.t("list","details");
x.t("list","menu");
x.t("list","follow");
x.t("list","view");
x.t("need","figure");
x.t("menu","beneath");
x.t("gene","reporter");
x.t("forward","view");
x.t("steps:","click");
x.t("beneath","tabbed");
x.t("menu.","click");
x.t("follow","steps:");
x.t("click","type");
x.t("click","details");
x.t("view","list");
x.t("view","patient");
x.t("view","individual");
x.t("data","items");
x.t("patient","gene");
x.t("individual","data");
x.t("category","list");
x.t("tabbed","menu.");
x.t("list.","need");
}
