function FileData_Pairs(x)
{
x.t("site.","access");
x.t("support","back");
x.t("support","getting");
x.t("support","link");
x.t("support","group");
x.t("support","find");
x.t("support","web");
x.t("support","ncicb");
x.t("back","forward");
x.t("getting","started");
x.t("getting","help");
x.t("access","site");
x.t("link","upper");
x.t("appears.","obtain");
x.t("upper","right-hand");
x.t("group","page");
x.t("right-hand","corner.");
x.t("forward","application");
x.t("obtain","help");
x.t("find","additional");
x.t("web","site.");
x.t("started","rem\u00adbrandt");
x.t("rem\u00adbrandt","1.5");
x.t("corner.","ncicb");
x.t("1.5","application");
x.t("rembrandt","getting");
x.t("click","support");
x.t("additional","support");
x.t("site","following:");
x.t("page","appears.");
x.t("help","rembrandt");
x.t("application","support");
x.t("ncicb","applications");
x.t("applications","support");
x.t("following:","click");
}
