function FileData_Pairs(x)
{
x.t("download","overview");
x.t("download","data");
x.t("center","biomedical");
x.t("caarray","application");
x.t("branch","national");
x.t("overview","rembrandt");
x.t("overview","data");
x.t("overview","downloading");
x.t("analyze","data");
x.t("enables","download");
x.t("enables","analyze");
x.t("biomedical","informatics");
x.t("cancer","institute");
x.t("national","cancer");
x.t("brb-arraytools","created");
x.t("developed","nci");
x.t("rembrandt","enables");
x.t("technology","enables");
x.t("research","branch");
x.t("data","download");
x.t("data","caarray");
x.t("data","data");
x.t("data","using");
x.t("information","technology");
x.t("application","developed");
x.t("briometric","research");
x.t("downloading","data");
x.t("nci","center");
x.t("created","briometric");
x.t("using","brb-arraytools");
x.t("informatics","information");
}
