function FileData_Pairs(x)
{
x.t("interfaces","navigation");
x.t("user","account");
x.t("support","logging");
x.t("back","forward");
x.t("getting","started");
x.t("getting","help");
x.t("features","used");
x.t("forward","getting");
x.t("common","features");
x.t("creating","user");
x.t("account","logging");
x.t("pages.","topics");
x.t("include:","creating");
x.t("logging","accepting");
x.t("introduces","rembrandt");
x.t("started","back");
x.t("started","getting");
x.t("started","section");
x.t("provisions","rembrandt");
x.t("workspace","getting");
x.t("1.5","workspace");
x.t("section","include:");
x.t("section","introduces");
x.t("rembrandt","interfaces");
x.t("rembrandt","pages.");
x.t("rembrandt","provisions");
x.t("rembrandt","1.5");
x.t("accepting","rembrandt");
x.t("help","application");
x.t("application","support");
x.t("topics","section");
x.t("navigation","common");
x.t("used","rembrandt");
}
