function FileData_Pairs(x)
{
x.t("interfaces","navigation");
x.t("user","registration");
x.t("bar","application");
x.t("support","logging");
x.t("getting","started");
x.t("new","user");
x.t("menu","rembrandt");
x.t("features","used");
x.t("common","features");
x.t("pages.","topics");
x.t("include:","rembrandt");
x.t("logging","rembrandt");
x.t("introduces","rembrandt");
x.t("started","rembrandt");
x.t("rembrandtrembrandtrembrandt\u2019s","opening");
x.t("side","bar");
x.t("section","include:");
x.t("section","introduces");
x.t("rembrandt","interfaces");
x.t("rembrandt","getting");
x.t("rembrandt","menu");
x.t("rembrandt","pages.");
x.t("rembrandt","rembrandtrembrandtrembrandt\u2019s");
x.t("rembrandt","side");
x.t("rembrandt","section");
x.t("rembrandt","rembrandt");
x.t("rembrandt","tabs");
x.t("registration","logging");
x.t("opening","page");
x.t("page","new");
x.t("application","support");
x.t("topics","section");
x.t("navigation","common");
x.t("used","rembrandt");
x.t("tabs","rembrandt");
}
