function FileData_Pairs(x)
{
x.t("included","results");
x.t("columns","hide");
x.t("sample","report");
x.t("diseases","toolbar");
x.t("advanced","search");
x.t("results","advanced");
x.t("results","gene");
x.t("remove","disease");
x.t("disease","included");
x.t("disease","hide");
x.t("disease","report");
x.t("check","box");
x.t("gene","expression");
x.t("box","disease");
x.t("search","query");
x.t("select","check");
x.t("viewing","results");
x.t("hide","diseases");
x.t("report","select");
x.t("report","removing");
x.t("expression","sample");
x.t("query","results");
x.t("removing","columns");
x.t("toolbar","remove");
x.t("toolbar","viewing");
x.t("toolbar","removing");
x.t("toolbar","checked");
x.t("checked","disease");
}
