function FileData_Pairs(x)
{
x.t("referencing","rembrandt");
x.t("example","national");
x.t("institute","source");
x.t("institute","2005");
x.t("2007","september");
x.t("source","including");
x.t("home","page");
x.t("http://rembrandt.nci.nih.gov","accessed");
x.t("year","first");
x.t("please","cite");
x.t("(2005)","rembrandt");
x.t("getting","started");
x.t("started","rembrandt");
x.t("accessed","2007");
x.t("accessed","date");
x.t("cancer","institute");
x.t("national","cancer");
x.t("first","production");
x.t("cite","national");
x.t("cite","rembrandt");
x.t("release","(2005)");
x.t("rembrandt","home");
x.t("rembrandt","cite");
x.t("rembrandt","rembrandt");
x.t("rembrandt","website");
x.t("rembrandt","data");
x.t("website","http://rembrandt.nci.nih.gov");
x.t("page","http://rembrandt.nci.nih.gov");
x.t("data","referencing");
x.t("data","please");
x.t("data","getting");
x.t("data","cite");
x.t("production","release");
x.t("date","example");
x.t("including","year");
x.t("2005","rembrandt");
}
