function FileData_Pairs(x)
{
x.t("describes","rembrandt");
x.t("comparisons","hierarchical");
x.t("hierarchical","clustering");
x.t("overview","performing");
x.t("high","order");
x.t("include:","high");
x.t("component","analyses.");
x.t("component","analysis");
x.t("comparison","performing");
x.t("section","describes");
x.t("section","include:");
x.t("rembrandt","run");
x.t("analyses","including");
x.t("clustering","principal");
x.t("clustering","analysis");
x.t("performing","hierarchical");
x.t("performing","principal");
x.t("performing","class");
x.t("principal","component");
x.t("analyses.","topics");
x.t("topics","section");
x.t("order","analyses");
x.t("order","analysis");
x.t("run","higher");
x.t("class","comparisons");
x.t("class","comparison");
x.t("analysis","overview");
x.t("analysis","high");
x.t("analysis","section");
x.t("analysis","performing");
x.t("including","class");
x.t("higher","order");
}
