
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class AffyAnno
{
  private String alignments;

  private Long arrayName;

  private String chromosomalLocation;

  private String ec;

  private String geneSymbol;

  private String geneTitle;

  private String genomeVersion;

  private String locuslink;

  private Long omim;

  private String probesetName;

  private String speciesName;

  private String unigeneId;

  public String getAlignments()
  {
     return this.alignments;
  }
  public void setAlignments(String param)
  {
    this.alignments = param;
  }


  public Long getArrayName()
  {
     return this.arrayName;
  }
  public void setArrayName(Long param)
  {
    this.arrayName = param;
  }


  public String getChromosomalLocation()
  {
     return this.chromosomalLocation;
  }
  public void setChromosomalLocation(String param)
  {
    this.chromosomalLocation = param;
  }


  public String getEc()
  {
     return this.ec;
  }
  public void setEc(String param)
  {
    this.ec = param;
  }


  public String getGeneSymbol()
  {
     return this.geneSymbol;
  }
  public void setGeneSymbol(String param)
  {
    this.geneSymbol = param;
  }


  public String getGeneTitle()
  {
     return this.geneTitle;
  }
  public void setGeneTitle(String param)
  {
    this.geneTitle = param;
  }


  public String getGenomeVersion()
  {
     return this.genomeVersion;
  }
  public void setGenomeVersion(String param)
  {
    this.genomeVersion = param;
  }


  public String getLocuslink()
  {
     return this.locuslink;
  }
  public void setLocuslink(String param)
  {
    this.locuslink = param;
  }


  public Long getOmim()
  {
     return this.omim;
  }
  public void setOmim(Long param)
  {
    this.omim = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public String getSpeciesName()
  {
     return this.speciesName;
  }
  public void setSpeciesName(String param)
  {
    this.speciesName = param;
  }


  public String getUnigeneId()
  {
     return this.unigeneId;
  }
  public void setUnigeneId(String param)
  {
    this.unigeneId = param;
  }


}

