
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class Agent
{
  private Long agentId;

  private String agentName;

  private String agentType;

  private String evsId;

  private Long nscNumber;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collDifferentialExpressionSfact;

  public Long getAgentId()
  {
     return this.agentId;
  }
  public void setAgentId(Long param)
  {
    this.agentId = param;
  }


  public String getAgentName()
  {
     return this.agentName;
  }
  public void setAgentName(String param)
  {
    this.agentName = param;
  }


  public String getAgentType()
  {
     return this.agentType;
  }
  public void setAgentType(String param)
  {
    this.agentType = param;
  }


  public String getEvsId()
  {
     return this.evsId;
  }
  public void setEvsId(String param)
  {
    this.evsId = param;
  }


  public Long getNscNumber()
  {
     return this.nscNumber;
  }
  public void setNscNumber(Long param)
  {
    this.nscNumber = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


}

