/*L
 * Copyright (c) 2006 SAIC, SAIC-F.
 *
 * Distributed under the OSI-approved BSD 3-Clause License.
 * See http://ncip.github.com/rembrandt/LICENSE.txt for details.
 */

// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;



/**
* caIntegrator License
* 
* Copyright 2001-2005 Science Applications International Corporation ("SAIC"). 
* The software subject to this notice and license includes both human readable source code form and machine readable, 
* binary, object code form ("the caIntegrator Software"). The caIntegrator Software was developed in conjunction with 
* the National Cancer Institute ("NCI") by NCI employees and employees of SAIC. 
* To the extent government employees are authors, any rights in such works shall be subject to Title 17 of the United States
* Code, section 105. 
* This caIntegrator Software License (the "License") is between NCI and You. "You (or "Your") shall mean a person or an 
* entity, and all other entities that control, are controlled by, or are under common control with the entity. "Control" 
* for purposes of this definition means (i) the direct or indirect power to cause the direction or management of such entity,
*  whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) 
* beneficial ownership of such entity. 
* This License is granted provided that You agree to the conditions described below. NCI grants You a non-exclusive, 
* worldwide, perpetual, fully-paid-up, no-charge, irrevocable, transferable and royalty-free right and license in its rights 
* in the caIntegrator Software to (i) use, install, access, operate, execute, copy, modify, translate, market, publicly 
* display, publicly perform, and prepare derivative works of the caIntegrator Software; (ii) distribute and have distributed 
* to and by third parties the caIntegrator Software and any modifications and derivative works thereof; 
* and (iii) sublicense the foregoing rights set out in (i) and (ii) to third parties, including the right to license such 
* rights to further third parties. For sake of clarity, and not by way of limitation, NCI shall have no right of accounting
* or right of payment from You or Your sublicensees for the rights granted under this License. This License is granted at no
* charge to You. 
* 1. Your redistributions of the source code for the Software must retain the above copyright notice, this list of conditions
*    and the disclaimer and limitation of liability of Article 6, below. Your redistributions in object code form must reproduce 
*    the above copyright notice, this list of conditions and the disclaimer of Article 6 in the documentation and/or other materials
*    provided with the distribution, if any. 
* 2. Your end-user documentation included with the redistribution, if any, must include the following acknowledgment: "This 
*    product includes software developed by SAIC and the National Cancer Institute." If You do not include such end-user 
*    documentation, You shall include this acknowledgment in the Software itself, wherever such third-party acknowledgments 
*    normally appear.
* 3. You may not use the names "The National Cancer Institute", "NCI" "Science Applications International Corporation" and 
*    "SAIC" to endorse or promote products derived from this Software. This License does not authorize You to use any 
*    trademarks, service marks, trade names, logos or product names of either NCI or SAIC, except as required to comply with
*    the terms of this License. 
* 4. For sake of clarity, and not by way of limitation, You may incorporate this Software into Your proprietary programs and 
*    into any third party proprietary programs. However, if You incorporate the Software into third party proprietary 
*    programs, You agree that You are solely responsible for obtaining any permission from such third parties required to 
*    incorporate the Software into such third party proprietary programs and for informing Your sublicensees, including 
*    without limitation Your end-users, of their obligation to secure any required permissions from such third parties 
*    before incorporating the Software into such third party proprietary software programs. In the event that You fail 
*    to obtain such permissions, You agree to indemnify NCI for any claims against NCI by such third parties, except to 
*    the extent prohibited by law, resulting from Your failure to obtain such permissions. 
* 5. For sake of clarity, and not by way of limitation, You may add Your own copyright statement to Your modifications and 
*    to the derivative works, and You may provide additional or different license terms and conditions in Your sublicenses 
*    of modifications of the Software, or any derivative works of the Software as a whole, provided Your use, reproduction, 
*    and distribution of the Work otherwise complies with the conditions stated in this License.
* 6. THIS SOFTWARE IS PROVIDED "AS IS," AND ANY EXPRESSED OR IMPLIED WARRANTIES, (INCLUDING, BUT NOT LIMITED TO, 
*    THE IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE) ARE DISCLAIMED. 
*    IN NO EVENT SHALL THE NATIONAL CANCER INSTITUTE, SAIC, OR THEIR AFFILIATES BE LIABLE FOR ANY DIRECT, INDIRECT, 
*    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE 
*    GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
*    LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
*    OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
* 
*/

public class ArraySNPSegmentFact
{
    public final static String DISEASE_TYPE = "diseaseType";
    public final static String INSTITUTION_NAME = "institutionName";
    public final static String SPECIMEN_NAME = "specimenName";
    public final static String SNP_SEGMENT_ID = "snpSegmentId";
    public final static String CHROMOSOME = "chromosome";
    public final static String CHR_SEGMENT_START = "chromosomeStart";
    public final static String CHR_SEGMENT_END = "chromosomeEnd";
    public final static String ANALYSIS_TYPE = "analysisType";
    
  private Long aSnpSegFId;

  private String chromosome;
  
  private Long chromosomeStart;
  
  private Long chromosomeEnd;
  
  private Double segmentMean;

  private Double calculatedCopyNumber;
  
  private Long numberMark;
  
  private String analysisType;
  
  private String specimenType;

  private String specimenName;
 
  private String sampleId;

  private Long diseaseTypeId;
    
  private String diseaseType;

  private Long institutionId;  
  
  private String institutionName;
  
  private Long snpSegmentId;
  
  private Long biospecimenId;
  
  private Long patientDid;
  

/**
 * @return the chromosomeStart
 */
public Long getChromosomeStart() {
	return chromosomeStart;
}

/**
 * @param chromosomeStart the chromosomeStart to set
 */
public void setChromosomeStart(Long chromosomeStart) {
	this.chromosomeStart = chromosomeStart;
}

/**
 * @return the chromosomeEnd
 */
public Long getChromosomeEnd() {
	return chromosomeEnd;
}

/**
 * @param chromosomeEnd the chromosomeEnd to set
 */
public void setChromosomeEnd(Long chromosomeEnd) {
	this.chromosomeEnd = chromosomeEnd;
}

/**
 * @return the aSnpSegFId
 */
public Long getASnpSegFId() {
	return aSnpSegFId;
}

/**
 * @param snpSegFId the aSnpSegFId to set
 */
public void setASnpSegFId(Long snpSegFId) {
	aSnpSegFId = snpSegFId;
}

/**
 * @return the chromosome
 */
public String getChromosome() {
	return chromosome;
}

/**
 * @param chromosome the chromosome to set
 */
public void setChromosome(String chromosome) {
	this.chromosome = chromosome;
}


/**
 * @return the segmentMean
 */
public Double getSegmentMean() {
	return segmentMean;
}

/**
 * @param segmentMean the segmentMean to set
 */
public void setSegmentMean(Double segmentMean) {
	this.segmentMean = segmentMean;
}

/**
 * @return the calculatedCopyNumber
 */
public Double getCalculatedCopyNumber() {
	return calculatedCopyNumber;
}

/**
 * @param calculatedCopyNumber the calculatedCopyNumber to set
 */
public void setCalculatedCopyNumber(Double calculatedCopyNumber) {
	this.calculatedCopyNumber = calculatedCopyNumber;
}

/**
 * @return the numberMark
 */
public Long getNumberMark() {
	return numberMark;
}

/**
 * @param numberMark the numberMark to set
 */
public void setNumberMark(Long numberMark) {
	this.numberMark = numberMark;
}

/**
 * @return the specimenName
 */
public String getSpecimenName() {
	return specimenName;
}

/**
 * @param specimenName the specimenName to set
 */
public void setSpecimenName(String specimenName) {
	this.specimenName = specimenName;
}

/**
 * @return the sampleId
 */
public String getSampleId() {
	return sampleId;
}

/**
 * @param sampleId the sampleId to set
 */
public void setSampleId(String sampleId) {
	this.sampleId = sampleId;
}

/**
 * @return the diseaseTypeId
 */
public Long getDiseaseTypeId() {
	return diseaseTypeId;
}

/**
 * @param diseaseTypeId the diseaseTypeId to set
 */
public void setDiseaseTypeId(Long diseaseTypeId) {
	this.diseaseTypeId = diseaseTypeId;
}

/**
 * @return the diseaseType
 */
public String getDiseaseType() {
	return diseaseType;
}

/**
 * @param diseaseType the diseaseType to set
 */
public void setDiseaseType(String diseaseType) {
	this.diseaseType = diseaseType;
}

/**
 * @return the institutionId
 */
public Long getInstitutionId() {
	return institutionId;
}

/**
 * @param institutionId the institutionId to set
 */
public void setInstitutionId(Long institutionId) {
	this.institutionId = institutionId;
}

/**
 * @return the institutionName
 */
public String getInstitutionName() {
	return institutionName;
}

/**
 * @param institutionName the institutionName to set
 */
public void setInstitutionName(String institutionName) {
	this.institutionName = institutionName;
}

/**
 * @return the snpSegmentId
 */
public Long getSnpSegmentId() {
	return snpSegmentId;
}

/**
 * @param snpSegmentId the snpSegmentId to set
 */
public void setSnpSegmentId(Long snpSegmentId) {
	this.snpSegmentId = snpSegmentId;
}

/**
 * @return the dISEASE_TYPE
 */
public static String getDISEASE_TYPE() {
	return DISEASE_TYPE;
}

/**
 * @return the iNSTITUTION_NAME
 */
public static String getINSTITUTION_NAME() {
	return INSTITUTION_NAME;
}

/**
 * @return the sPECIMEN_NAME
 */
public static String getSPECIMEN_NAME() {
	return SPECIMEN_NAME;
}

/**
 * @return the patientDid
 */
public Long getPatientDid() {
	return patientDid;
}

/**
 * @param patientDid the patientDid to set
 */
public void setPatientDid(Long patientDid) {
	this.patientDid = patientDid;
}

/**
 * @return the biospecimenId
 */
public Long getBiospecimenId() {
	return biospecimenId;
}

/**
 * @param biospecimenId the biospecimenId to set
 */
public void setBiospecimenId(Long biospecimenId) {
	this.biospecimenId = biospecimenId;
}

/**
 * @return the analysisType
 */
public String getAnalysisType() {
	return analysisType;
}

/**
 * @param analysisType the analysisType to set
 */
public void setAnalysisType(String analysisType) {
	this.analysisType = analysisType;
}

/**
 * @return the specimenType
 */
public String getSpecimenType() {
	return specimenType;
}

/**
 * @param specimenType the specimenType to set
 */
public void setSpecimenType(String specimenType) {
	this.specimenType = specimenType;
}



}

