
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class ClinicalInfoStg
{
  private Long ageDx;

  private String dateCut;

  private String diagnosis;

  private String dlfu;

  private String dod;

  private String dodx;

  private String hf;

  private String mib;

  private String rowNames;

  private String sex;

  private Long survivalTime;

  private String tumor;

  private String whoGrade;

  public Long getAgeDx()
  {
     return this.ageDx;
  }
  public void setAgeDx(Long param)
  {
    this.ageDx = param;
  }


  public String getDateCut()
  {
     return this.dateCut;
  }
  public void setDateCut(String param)
  {
    this.dateCut = param;
  }


  public String getDiagnosis()
  {
     return this.diagnosis;
  }
  public void setDiagnosis(String param)
  {
    this.diagnosis = param;
  }


  public String getDlfu()
  {
     return this.dlfu;
  }
  public void setDlfu(String param)
  {
    this.dlfu = param;
  }


  public String getDod()
  {
     return this.dod;
  }
  public void setDod(String param)
  {
    this.dod = param;
  }


  public String getDodx()
  {
     return this.dodx;
  }
  public void setDodx(String param)
  {
    this.dodx = param;
  }


  public String getHf()
  {
     return this.hf;
  }
  public void setHf(String param)
  {
    this.hf = param;
  }


  public String getMib()
  {
     return this.mib;
  }
  public void setMib(String param)
  {
    this.mib = param;
  }


  public String getRowNames()
  {
     return this.rowNames;
  }
  public void setRowNames(String param)
  {
    this.rowNames = param;
  }


  public String getSex()
  {
     return this.sex;
  }
  public void setSex(String param)
  {
    this.sex = param;
  }


  public Long getSurvivalTime()
  {
     return this.survivalTime;
  }
  public void setSurvivalTime(Long param)
  {
    this.survivalTime = param;
  }


  public String getTumor()
  {
     return this.tumor;
  }
  public void setTumor(String param)
  {
    this.tumor = param;
  }


  public String getWhoGrade()
  {
     return this.whoGrade;
  }
  public void setWhoGrade(String param)
  {
    this.whoGrade = param;
  }


}

