
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class CloneAccession
{
  public final static String ACCESSION_NUMBER = "accessionNumber";

  private String accessionNumber;

  private Long cloneId;



  public String getAccessionNumber()
  {
     return this.accessionNumber;
  }
  public void setAccessionNumber(String param)
  {
    this.accessionNumber = param;
  }


  public Long getCloneId()
  {
     return this.cloneId;
  }
  public void setCloneId(Long param)
  {
    this.cloneId = param;
  }


}

