
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class DiffExpressionGeneSFact
{

    public final static String INSTITUTION_ID = "institutionId";
    public final static String GENE_SYMBOL = "geneSymbol";
    private String diseaseType;
    private Double expressionRatio;
    private String unifiedGene;
    private String geneSymbol;
    private Double normalIntensity;
    private Double sampleIntensity;
    private String sampleId;
    private Long degsId;
    private Long institutionId;


    public String getDiseaseType() {
        return diseaseType;
    }

    public void setDiseaseType(String diseaseType) {
        this.diseaseType = diseaseType;
    }

    public Double getExpressionRatio() {
        return expressionRatio;
    }

    public void setExpressionRatio(Double expressionRatio) {
        this.expressionRatio = expressionRatio;
    }

    public String getUnifiedGene() {
        return unifiedGene;
    }

    public void setUnifiedGene(String unifiedGene) {
        this.unifiedGene = unifiedGene;
    }

    public String getGeneSymbol() {
        return geneSymbol;
    }

    public void setGeneSymbol(String geneSymbol) {
        this.geneSymbol = geneSymbol;
    }

    public Double getNormalIntensity() {
        return normalIntensity;
    }

    public void setNormalIntensity(Double normalIntensity) {
        this.normalIntensity = normalIntensity;
    }

    public Double getSampleIntensity() {
        return sampleIntensity;
    }

    public void setSampleIntensity(Double sampleIntensity) {
        this.sampleIntensity = sampleIntensity;
    }


    public Long getInstitutionId() {
        return institutionId;
    }

    public void setInstitutionId(Long institutionId) {
        this.institutionId = institutionId;
    }

    public String getSampleId() {
        return sampleId;
    }

    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }

    public Long getDegsId() {
        return degsId;
    }

    public void setDegsId(Long degsId) {
        this.degsId = degsId;
    }
}

