
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class DiffExpressionGeneGFact
{
    public final static String INSTITUTION_ID = "institutionId";
    public final static String GENE_SYMBOL = "geneSymbol";
    private String diseaseType;
    private Double expressionRatio;
    private String unifiedGene;
    private String geneSymbol;
    private Double normalIntensity;
    private Double sampleIntensity;
    private Double rationStd;
    private Long deggId;
    private Long institutionId;
    private Double ratioPval;
    private Double ratioStd;

    public Double getRatioStd() {
        return ratioStd;
    }

    public void setRatioStd(Double ratioStd) {
        this.ratioStd = ratioStd;
    }

    public String getDiseaseType() {
        return diseaseType;
    }

    public void setDiseaseType(String diseaseType) {
        this.diseaseType = diseaseType;
    }

    public Double getExpressionRatio() {
        return expressionRatio;
    }

    public void setExpressionRatio(Double expressionRatio) {
        this.expressionRatio = expressionRatio;
    }

    public String getUnifiedGene() {
        return unifiedGene;
    }

    public void setUnifiedGene(String unifiedGene) {
        this.unifiedGene = unifiedGene;
    }

    public String getGeneSymbol() {
        return geneSymbol;
    }

    public void setGeneSymbol(String geneSymbol) {
        this.geneSymbol = geneSymbol;
    }

    public Double getNormalIntensity() {
        return normalIntensity;
    }

    public void setNormalIntensity(Double normalIntensity) {
        this.normalIntensity = normalIntensity;
    }

    public Double getSampleIntensity() {
        return sampleIntensity;
    }

    public void setSampleIntensity(Double sampleIntensity) {
        this.sampleIntensity = sampleIntensity;
    }

    public Double getRationStd() {
        return rationStd;
    }

    public void setRationStd(Double rationStd) {
        this.rationStd = rationStd;
    }

    public Long getDeggId() {
        return deggId;
    }

    public void setDeggId(Long deggId) {
        this.deggId = deggId;
    }

    public Long getInstitutionId() {
        return institutionId;
    }

    public void setInstitutionId(Long institutionId) {
        this.institutionId = institutionId;
    }

    public Double getRatioPval() {
        return ratioPval;
    }

    public void setRatioPval(Double ratioPval) {
        this.ratioPval = ratioPval;
    }

}

