
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class DiseaseHistory
{
  private Long diseaseHistoryId;

  private String occurrenceStatus;

  private String occurrenceStatusDesc;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collDifferentialExpressionSfact;

  public Long getDiseaseHistoryId()
  {
     return this.diseaseHistoryId;
  }
  public void setDiseaseHistoryId(Long param)
  {
    this.diseaseHistoryId = param;
  }


  public String getOccurrenceStatus()
  {
     return this.occurrenceStatus;
  }
  public void setOccurrenceStatus(String param)
  {
    this.occurrenceStatus = param;
  }


  public String getOccurrenceStatusDesc()
  {
     return this.occurrenceStatusDesc;
  }
  public void setOccurrenceStatusDesc(String param)
  {
    this.occurrenceStatusDesc = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


}

