
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class Gender
{
  private String genderCode;

  private String genderDesc;

  private java.util.Vector collDifferentialExpressionSfact;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collDifferentialExpressionGfact;

  public String getGenderCode()
  {
     return this.genderCode;
  }
  public void setGenderCode(String param)
  {
    this.genderCode = param;
  }


  public String getGenderDesc()
  {
     return this.genderDesc;
  }
  public void setGenderDesc(String param)
  {
    this.genderDesc = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionGfact()
  {
     return this.collDifferentialExpressionGfact;
  }
  public void setCollDifferentialExpressionGfact(java.util.Vector param)
  {
    this.collDifferentialExpressionGfact = param;
  }


}

