
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class GeneSnp
{
    public final static String SNP_PROBESET_ID  = "snpProbesetId";
    public final static String GENE_SYMBOL  = "geneSymbol";

  private String geneSymbol;

  private String probesetName;

  private Long snpProbesetId;

  private String upGeneSymbol;


  public String getGeneSymbol()
  {
     return this.geneSymbol;
  }
  public void setGeneSymbol(String param)
  {
    this.geneSymbol = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public Long getSnpProbesetId()
  {
     return this.snpProbesetId;
  }
  public void setSnpProbesetId(Long param)
  {
    this.snpProbesetId = param;
  }


  public String getUpGeneSymbol()
  {
     return this.upGeneSymbol;
  }
  public void setUpGeneSymbol(String param)
  {
    this.upGeneSymbol = param;
  }


}

