
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class GeneProbeset
{
  private Long geneId;

  private Long probesetId;

  private gov.nih.nci.rembrandt.dbbean.ProbesetDim aProbesetDim;

  private gov.nih.nci.rembrandt.dbbean.GeneDimOld aGeneDimOld;

  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public Long getProbesetId()
  {
     return this.probesetId;
  }
  public void setProbesetId(Long param)
  {
    this.probesetId = param;
  }


  public gov.nih.nci.rembrandt.dbbean.ProbesetDim getAProbesetDim()
  {
     return this.aProbesetDim;
  }
  public void setAProbesetDim(gov.nih.nci.rembrandt.dbbean.ProbesetDim param)
  {
    this.aProbesetDim = param;
  }


  public gov.nih.nci.rembrandt.dbbean.GeneDimOld getAGeneDimOld()
  {
     return this.aGeneDimOld;
  }
  public void setAGeneDimOld(gov.nih.nci.rembrandt.dbbean.GeneDimOld param)
  {
    this.aGeneDimOld = param;
  }


}

