
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

import gov.nih.nci.rembrandt.queryservice.resultset.ResultSet;

import java.sql.Date;

public class NeuroEvaluation implements ResultSet
{
   public final static String NEURO_EVALUATION_ID = "neuroEvaluationId";
   public final static String PATIENT_DID = "patientDid";  
   public final static String INSTITUTION_ID = "institutionId";
   public final static String DATASET_ID = "datasetId";
   public final static String TIME_POINT = "timePoint";
   public final static String FOLLOWUP_DATE = "followupDate";
   public final static String FOLLOWUP_MONTH = "followupMonth";
   public final static String NEURO_EVALUATION_DATE = "neuroEvaluationDate";
   public final static String KARNOFSKY_SCORE = "karnofskyScore";
   public final static String LANSKY_SCORE = "lanskyScore";
   public final static String NEURO_EXAM= "neuroExam";
   public final static String MRI_CT_SCORE= "mriCtScore";
   public final static String STEROID_DOSE_STATUS= "steroidDoseStatus"; 
   public final static String ANTI_CONVULSANT_STATUS= "antiConvulsantStatus";
  

    private Long neuroEvaluationId;
    
    private Long patientDid;

    private Long institutionId;
    
    private Long datasetId;

    private String timePoint;  

    private Date followupDate;   

    private Long followupMonth;

    private Date neuroEvaluationDate;     
    
    private Long karnofskyScore;
    
    private Long lanskyScore;
    
    private Long neuroExam;  
    
    private Long mriCtScore;
    
    private String steroidDoseStatus;
    
    private String antiConvulsantStatus;

	/**
	 * @return Returns the antiConvulsantStatus.
	 */
	public String getAntiConvulsantStatus() {
		return antiConvulsantStatus;
	}

	/**
	 * @param antiConvulsantStatus The antiConvulsantStatus to set.
	 */
	public void setAntiConvulsantStatus(String antiConvulsantStatus) {
		this.antiConvulsantStatus = antiConvulsantStatus;
	}

	/**
	 * @return Returns the neuroEvaluationId.
	 */
	public Long getNeuroEvaluationId() {
		return neuroEvaluationId;
	}

	/**
	 * @param clinicalEvaluationId The neuroEvaluationId to set.
	 */
	public void setNeuroEvaluationId(Long neuroEvaluationId) {
		this.neuroEvaluationId = neuroEvaluationId;
	}

	/**
	 * @return Returns the datasetId.
	 */
	public Long getDatasetId() {
		return datasetId;
	}

	/**
	 * @param datasetId The datasetId to set.
	 */
	public void setDatasetId(Long datasetId) {
		this.datasetId = datasetId;
	}

	/**
	 * @return Returns the followupDate.
	 */
	public Date getFollowupDate() {
		return followupDate;
	}

	/**
	 * @param followupDate The followupDate to set.
	 */
	public void setFollowupDate(Date followupDate) {
		this.followupDate = followupDate;
	}

	/**
	 * @return Returns the followupMonth.
	 */
	public Long getFollowupMonth() {
		return followupMonth;
	}

	/**
	 * @param followupMonth The followupMonth to set.
	 */
	public void setFollowupMonth(Long followupMonth) {
		this.followupMonth = followupMonth;
	}

	/**
	 * @return Returns the institutionId.
	 */
	public Long getInstitutionId() {
		return institutionId;
	}

	/**
	 * @param institutionId The institutionId to set.
	 */
	public void setInstitutionId(Long institutionId) {
		this.institutionId = institutionId;
	}

	/**
	 * @return Returns the karnofskyScore.
	 */
	public Long getKarnofskyScore() {
		return karnofskyScore;
	}

	/**
	 * @param karnofskyScore The karnofskyScore to set.
	 */
	public void setKarnofskyScore(Long karnofskyScore) {
		this.karnofskyScore = karnofskyScore;
	}

	/**
	 * @return Returns the lanskyScore.
	 */
	public Long getLanskyScore() {
		return lanskyScore;
	}

	/**
	 * @param lanskyScore The lanskyScore to set.
	 */
	public void setLanskyScore(Long lanskyScore) {
		this.lanskyScore = lanskyScore;
	}

	/**
	 * @return Returns the mriCtScore.
	 */
	public Long getMriCtScore() {
		return mriCtScore;
	}

	/**
	 * @param mriCtScore The mriCtScore to set.
	 */
	public void setMriCtScore(Long mriCtScore) {
		this.mriCtScore = mriCtScore;
	}

	/**
	 * @return Returns the neuroEvaluationDate.
	 */
	public Date getNeuroEvaluationDate() {
		return neuroEvaluationDate;
	}

	/**
	 * @param neuroEvaluationDate The neuroEvaluationDate to set.
	 */
	public void setNeuroEvaluationDate(Date neuroEvaluationDate) {
		this.neuroEvaluationDate = neuroEvaluationDate;
	}

	/**
	 * @return Returns the neuroExam.
	 */
	public Long getNeuroExam() {
		return neuroExam;
	}

	/**
	 * @param neuroExam The neuroExam to set.
	 */
	public void setNeuroExam(Long neuroExam) {
		this.neuroExam = neuroExam;
	}

	/**
	 * @return Returns the patientDid.
	 */
	public Long getPatientDid() {
		return patientDid;
	}

	/**
	 * @param patientDid The patientDid to set.
	 */
	public void setPatientDid(Long patientDid) {
		this.patientDid = patientDid;
	}

	/**
	 * @return Returns the steroidDoseStatus.
	 */
	public String getSteroidDoseStatus() {
		return steroidDoseStatus;
	}

	/**
	 * @param steroidDoseStatus The steroidDoseStatus to set.
	 */
	public void setSteroidDoseStatus(String steroidDoseStatus) {
		this.steroidDoseStatus = steroidDoseStatus;
	}

	/**
	 * @return Returns the timePoint.
	 */
	public String getTimePoint() {
		return timePoint;
	}

	/**
	 * @param timePoint The timePoint to set.
	 */
	public void setTimePoint(String timePoint) {
		this.timePoint = timePoint;
	}
      
    
    
}

	

	

	
	
	
    
    
    
  

   


  
  
  


  




