
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class Pathway
{
  public final static String PATHWAY_ID = "pathwayId";
  private String dataSource;

  private Object pathwayDesc;

  private Long pathwayId;

  private String pathwayName;

  public String getDataSource()
  {
     return this.dataSource;
  }
  public void setDataSource(String param)
  {
    this.dataSource = param;
  }


  public Object getPathwayDesc()
  {
     return this.pathwayDesc;
  }
  public void setPathwayDesc(Object param)
  {
    this.pathwayDesc = param;
  }


  public Long getPathwayId()
  {
     return this.pathwayId;
  }
  public void setPathwayId(Long param)
  {
    this.pathwayId = param;
  }


  public String getPathwayName()
  {
     return this.pathwayName;
  }
  public void setPathwayName(String param)
  {
    this.pathwayName = param;
  }


}

