
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class PopulationType
{
  private String populationTypeDesc;

  private Long populationTypeId;

  private String populationTypeName;

  private java.util.Vector collPatient;

  public String getPopulationTypeDesc()
  {
     return this.populationTypeDesc;
  }
  public void setPopulationTypeDesc(String param)
  {
    this.populationTypeDesc = param;
  }


  public Long getPopulationTypeId()
  {
     return this.populationTypeId;
  }
  public void setPopulationTypeId(Long param)
  {
    this.populationTypeId = param;
  }


  public String getPopulationTypeName()
  {
     return this.populationTypeName;
  }
  public void setPopulationTypeName(String param)
  {
    this.populationTypeName = param;
  }


  public java.util.Vector getCollPatient()
  {
     return this.collPatient;
  }
  public void setCollPatient(java.util.Vector param)
  {
    this.collPatient = param;
  }


}

