
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class ProteinFamilyStg
{
  private String probesetName;

  private String proteinFamily;

  private String proteinFamilyId;

  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public String getProteinFamily()
  {
     return this.proteinFamily;
  }
  public void setProteinFamily(String param)
  {
    this.proteinFamily = param;
  }


  public String getProteinFamilyId()
  {
     return this.proteinFamilyId;
  }
  public void setProteinFamilyId(String param)
  {
    this.proteinFamilyId = param;
  }


}

