
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class ProteinFamily
{
  private Long geneId;

  private String proteinFamily;

  private gov.nih.nci.rembrandt.dbbean.GeneDimOld aGeneDimOld;

  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public String getProteinFamily()
  {
     return this.proteinFamily;
  }
  public void setProteinFamily(String param)
  {
    this.proteinFamily = param;
  }


  public gov.nih.nci.rembrandt.dbbean.GeneDimOld getAGeneDimOld()
  {
     return this.aGeneDimOld;
  }
  public void setAGeneDimOld(gov.nih.nci.rembrandt.dbbean.GeneDimOld param)
  {
    this.aGeneDimOld = param;
  }


}

