
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class RefseqProteinIdStg
{
  private String probesetName;

  private Long refseqProteinId;

  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public Long getRefseqProteinId()
  {
     return this.refseqProteinId;
  }
  public void setRefseqProteinId(Long param)
  {
    this.refseqProteinId = param;
  }


}

