
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class RefseqProteinId
{
  private Long geneId;

  private Long refseqProteinId;

  private gov.nih.nci.rembrandt.dbbean.GeneDimOld aGeneDimOld;

  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public Long getRefseqProteinId()
  {
     return this.refseqProteinId;
  }
  public void setRefseqProteinId(Long param)
  {
    this.refseqProteinId = param;
  }


  public gov.nih.nci.rembrandt.dbbean.GeneDimOld getAGeneDimOld()
  {
     return this.aGeneDimOld;
  }
  public void setAGeneDimOld(gov.nih.nci.rembrandt.dbbean.GeneDimOld param)
  {
    this.aGeneDimOld = param;
  }


}

