
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class SampleAgeSurvGrp
{
  private String ageGrp;

  private String sampleId;

  private String survGrp;

  public String getAgeGrp()
  {
     return this.ageGrp;
  }
  public void setAgeGrp(String param)
  {
    this.ageGrp = param;
  }


  public String getSampleId()
  {
     return this.sampleId;
  }
  public void setSampleId(String param)
  {
    this.sampleId = param;
  }


  public String getSurvGrp()
  {
     return this.survGrp;
  }
  public void setSurvGrp(String param)
  {
    this.survGrp = param;
  }


}

