
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class SnpAssociatedGene
{
    public final static String SNP_PROBESET_ID = "snpProbesetId";
    public final static String GENE_SYMBOL = "geneSymbol";
    public final static String ACCESSION_NUMBER = "accessionNumber";

    private Long snpProbesetId;
    private String probesetName;
    private String arrayName;
    private String accessionNumber;
    private String geneSymbol;

    public Long getSnpProbesetId() {
        return snpProbesetId;
    }

    public void setSnpProbesetId(Long snpProbesetId) {
        this.snpProbesetId = snpProbesetId;
    }

    public String getProbesetName() {
        return probesetName;
    }

    public void setProbesetName(String probesetName) {
        this.probesetName = probesetName;
    }

    public String getArrayName() {
        return arrayName;
    }

    public void setArrayName(String arrayName) {
        this.arrayName = arrayName;
    }

    public String getAccessionNumber() {
        return accessionNumber;
    }

    public void setAccessionNumber(String accessionNumber) {
        this.accessionNumber = accessionNumber;
    }

    public String getGeneSymbol() {
        return geneSymbol;
    }

    public void setGeneSymbol(String geneSymbol) {
        this.geneSymbol = geneSymbol;
    }

}

