
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class SnpProbesetDim
{
  public final static String PHYSICAL_POSITION = "physicalPosition";
  public final static String SNP_PROBESET_ID = "snpProbesetId";
  public final static String DB_SNP_ID = "dbSnpId";
  public final static String PROBESET_NAME = "probesetName";  
  public final static String CHROMOSOME = "chromosome";


  private String alleleFrequencyAf;

  private String alleleFrequencyAs;

  private String alleleFrequencyCa;

  private String arrayName;

  private String chromosome;

  private String cytoband;

  private String dbSnpId;

  private Long physicalPosition;

  private String probesetName;

  private Long snpProbesetId;



  public String getAlleleFrequencyAf()
  {
     return this.alleleFrequencyAf;
  }
  public void setAlleleFrequencyAf(String param)
  {
    this.alleleFrequencyAf = param;
  }


  public String getAlleleFrequencyAs()
  {
     return this.alleleFrequencyAs;
  }
  public void setAlleleFrequencyAs(String param)
  {
    this.alleleFrequencyAs = param;
  }


  public String getAlleleFrequencyCa()
  {
     return this.alleleFrequencyCa;
  }
  public void setAlleleFrequencyCa(String param)
  {
    this.alleleFrequencyCa = param;
  }


  public String getArrayName()
  {
     return this.arrayName;
  }
  public void setArrayName(String param)
  {
    this.arrayName = param;
  }


  public String getChromosome()
  {
     return this.chromosome;
  }
  public void setChromosome(String param)
  {
    this.chromosome = param;
  }


  public String getCytoband()
  {
     return this.cytoband;
  }
  public void setCytoband(String param)
  {
    this.cytoband = param;
  }


  public String getDbSnpId()
  {
     return this.dbSnpId;
  }
  public void setDbSnpId(String param)
  {
    this.dbSnpId = param;
  }


  public Long getPhysicalPosition()
  {
     return this.physicalPosition;
  }
  public void setPhysicalPosition(Long param)
  {
    this.physicalPosition = param;
  }


  public String getProbesetName()
  {
     return this.probesetName;
  }
  public void setProbesetName(String param)
  {
    this.probesetName = param;
  }


  public Long getSnpProbesetId()
  {
     return this.snpProbesetId;
  }
  public void setSnpProbesetId(Long param)
  {
    this.snpProbesetId = param;
  }




}

