
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class StudyTimecourseDim
{
  private String timecourseDesc;

  private Long timecourseId;

  private String timecourseName;

  private java.util.Vector collDifferentialExpressionSfact;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collDifferentialExpressionGfact;

  public String getTimecourseDesc()
  {
     return this.timecourseDesc;
  }
  public void setTimecourseDesc(String param)
  {
    this.timecourseDesc = param;
  }


  public Long getTimecourseId()
  {
     return this.timecourseId;
  }
  public void setTimecourseId(Long param)
  {
    this.timecourseId = param;
  }


  public String getTimecourseName()
  {
     return this.timecourseName;
  }
  public void setTimecourseName(String param)
  {
    this.timecourseName = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionGfact()
  {
     return this.collDifferentialExpressionGfact;
  }
  public void setCollDifferentialExpressionGfact(java.util.Vector param)
  {
    this.collDifferentialExpressionGfact = param;
  }


}

