
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class StudyDatasetDim
{
  private String datasetDesc;

  private Long datasetId;

  private String datasetName;

  private java.util.Vector collDifferentialExpressionSfact;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collDifferentialExpressionGfact;

  public String getDatasetDesc()
  {
     return this.datasetDesc;
  }
  public void setDatasetDesc(String param)
  {
    this.datasetDesc = param;
  }


  public Long getDatasetId()
  {
     return this.datasetId;
  }
  public void setDatasetId(Long param)
  {
    this.datasetId = param;
  }


  public String getDatasetName()
  {
     return this.datasetName;
  }
  public void setDatasetName(String param)
  {
    this.datasetName = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionGfact()
  {
     return this.collDifferentialExpressionGfact;
  }
  public void setCollDifferentialExpressionGfact(java.util.Vector param)
  {
    this.collDifferentialExpressionGfact = param;
  }


}

