
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class SurvivalLengthRange
{
  private String groupDesc;

  private Long lowerbound;

  private String survivalLengthRange;

  private Long upperbound;

  private java.util.Vector collDifferentialExpressionSfact;

  private java.util.Vector collArrayGenoAbnFact;

  private java.util.Vector collDifferentialExpressionGfact;

  public String getGroupDesc()
  {
     return this.groupDesc;
  }
  public void setGroupDesc(String param)
  {
    this.groupDesc = param;
  }


  public Long getLowerbound()
  {
     return this.lowerbound;
  }
  public void setLowerbound(Long param)
  {
    this.lowerbound = param;
  }


  public String getSurvivalLengthRange()
  {
     return this.survivalLengthRange;
  }
  public void setSurvivalLengthRange(String param)
  {
    this.survivalLengthRange = param;
  }


  public Long getUpperbound()
  {
     return this.upperbound;
  }
  public void setUpperbound(Long param)
  {
    this.upperbound = param;
  }


  public java.util.Vector getCollDifferentialExpressionSfact()
  {
     return this.collDifferentialExpressionSfact;
  }
  public void setCollDifferentialExpressionSfact(java.util.Vector param)
  {
    this.collDifferentialExpressionSfact = param;
  }


  public java.util.Vector getCollArrayGenoAbnFact()
  {
     return this.collArrayGenoAbnFact;
  }
  public void setCollArrayGenoAbnFact(java.util.Vector param)
  {
    this.collArrayGenoAbnFact = param;
  }


  public java.util.Vector getCollDifferentialExpressionGfact()
  {
     return this.collDifferentialExpressionGfact;
  }
  public void setCollDifferentialExpressionGfact(java.util.Vector param)
  {
    this.collDifferentialExpressionGfact = param;
  }


}

