
// Generated by OJB SchemeGenerator

package gov.nih.nci.rembrandt.dbbean;

public class Swissprot
{
  private Long geneId;

  private String swissprot;

  private gov.nih.nci.rembrandt.dbbean.GeneDimOld aGeneDimOld;

  public Long getGeneId()
  {
     return this.geneId;
  }
  public void setGeneId(Long param)
  {
    this.geneId = param;
  }


  public String getSwissprot()
  {
     return this.swissprot;
  }
  public void setSwissprot(String param)
  {
    this.swissprot = param;
  }


  public gov.nih.nci.rembrandt.dbbean.GeneDimOld getAGeneDimOld()
  {
     return this.aGeneDimOld;
  }
  public void setAGeneDimOld(gov.nih.nci.rembrandt.dbbean.GeneDimOld param)
  {
    this.aGeneDimOld = param;
  }


}

